### ISSUE TITLE
Types are defined in index.d.ts but are not exported

### ISSUE THREAD

**Issue by gurkerl83** [chakra-ui/zag#1005]
Zag defines various types which are important for consumers, e.g. InputValueChangeDetails here https://github.com/chakra-ui/zag/blob/62eeec6bc37e66536d676f926150d3c3cad4cf33/packages/machines/combobox/src/combobox.types.ts#L21

In the build process the types are pushed in the dist/index.d.ts file for each package and so is e.g. InputValueChangeDetails. The problem is that the respective export declaration gets lost in the process making it impossible to use the type for a function callback interface.

```
@zag-js/combobox/dist/index.d.ts
interface HighlightChangeDetails<T extends CollectionItem = CollectionItem> {
    highlightedValue: string | null;
    highligtedItem: T | null;
}
interface InputValueChangeDetails { // export is missing - using it externally is not possible
    value: string;
}
interface OpenChangeDetails {
    open: boolean;
}
```

Thx!

**Comment by segunadebayo** [comment]
Thanks for opening this issue @gurkerl83.

I agree we need to export more types to improve the DX. I pushed a fix for this.

We'll release an update shortly. If the issue persists after upgrading, I'll re-open it.

**Comment by gurkerl83** [comment]
I just executed build locally and the missing types are now in the index.d.ts of the specific machine. Instead of manually exporting them I was wondering if the export declaration in e.g. InputValueChangeDetails can be automatically re-exported by the build tool / plugin used, because there is no any other place in the code where e.g. InputValueChangeDetails is used?
