### ISSUE TITLE
[number input] formatting doesn't trigger value update, and spinners don't persist formatting

### ISSUE THREAD

**Issue by nyerslaszlo** [chakra-ui/zag#1022]
# 🐛 Bug report

With the Number input components ( using VUE SFC ):
- When decimal value updates on blur (when the Intl formatting happens), it doesn't trigger an "onValueUpdate" event.
- When using locales that use decimal commas and not decimal points, incrementing and decrementing will not work correctly.

## 💥 Steps to reproduce

(See CodeSandbox for easy Demo).

First Bug:
1. Create number Input fields. 
2. Set "maximumFractionDigits" format options to a positive value.
3. Type in more decimals than the "maximumFractionDigits" and unfocus the input.
4. Formatting happens, but since onValueChange() event doesn't trigger the underlying value ref stays the same.

Second Bug:
1. Create number Input fields. 
2. Set "locale" to something that uses commas as decimal points. (eg. nl-BE)
3. Type in a number with decimals (eg 1500,55)
4. Trigger incrementing/decrementing or press the buttons.

## 💻 Reproduction
CodeSandbox reproduction: https://codesandbox.io/p/sandbox/sleepy-cache-xly8xv?file=%2Fsrc%2FApp.vue%3A21%2C34

## 🧐 Expected behavior

First Bug: Trigger an onValueChange() event if the formatting changes the value of the field (for example if it does rounding), when input field loses focus.
Second Bug: Correctly increment and decrement values with decimal commas.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |0.27.1|
| Browser          |Microsoft Edge|
| Operating System |Windows 11|

**Comment by segunadebayo** [comment]
Thanks for such a detailed report @nyerslaszlo.

Made it much easier to spot the bug and fix it accordingly.

I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
