### ISSUE TITLE
Collection (and other utilities?) documentation

### ISSUE THREAD

**Issue by vincerubinetti** [chakra-ui/zag#1042]
I'm unable to find anything real about `collection` in the docs page. For example, on the [select page](https://zagjs.com/components/react/select), there's these properties `itemToValue` and `itemToString` but no mention of what they're for.

By experimentation, I see that `itemToValue` is necessary for giving Zag a way to uniquely identify the item (selection wont work without it). Looking at the source code, it seems like `itemToString` is maybe used in type-ahead or search or something like that?

**Comment by segunadebayo** [comment]
Good catch, @vincerubinetti.

I've updated the docs to mention the collection, especially how to use it when you have custom objects.
