### ISSUE TITLE
Select doesn't work with controlled state

### ISSUE THREAD

**Issue by juliomuhlbauer** [chakra-ui/zag#1070]
# 🐛 Bug report

The select component doesn't update when I set a new value with useState.

## 💥 Steps to reproduce

1. Go to https://use-search-param-ark.vercel.app/controlled-select-zag
2. Click on the button to change the value, it won't update the Select state
3. Try to change the value of the Select with the dropdown. It shouldn't update as the value prop didn't change.

## 💻 Link to reproduction

Demo: https://use-search-param-ark.vercel.app/controlled-select-zag
Repo: https://github.com/juliomuhlbauer/use-search-param-ark/tree/main/src/app/controlled-select-zag

## 🧐 Expected behavior

Select value must update the value when value prop is updated and shouldn't be able to set another value if isn't updated from the value prop.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |     0.31.1       |
| Browser          |      Chrome 119      |
| Operating System |      Windows      |

## 📝 Additional information

My use case is that I want a controlled Select to be synced with the searchParam from useSearchPram hook from Nextjs.

https://github.com/chakra-ui/zag/assets/53458125/f8c16afc-9807-4b17-8ba7-3621b5be0a66

**Comment by juliomuhlbauer** [comment]
Also, reading this https://zagjs.com/overview/programmatic-control#controlled-usage-in-react. I think it shouldn't be the default behavior. Because a lot of devs coming from other component libs are used to controllable components.

And I think this should be warned in Ark UI lib as well.

I am open for contribution on this.

**Comment by segunadebayo** [comment]
Hi @juliomuhlbauer,

As shown in the Docs, here's the best way to control the component.

```jsx
  const [state, send] = useMachine(
    select.machine({
     // initial context
      id: useId(),
      collection,
    }, {
     // controlled context
      context: {
        value: value ? [value] : undefined
      }
    })
  );
```

The idea of controlled/uncontrolled is a React construct, and I understand where you're coming from. However, we want to keep the default in a shape that mirrors the DOM and add extra hooks to support React.

In Ark UI, this is handled already. If you experience a bug with it, feel free to move this issue over there and we'll look into it.

**Comment by juliomuhlbauer** [comment]
It doesn't accept a second argument:

![image](https://github.com/chakra-ui/zag/assets/53458125/71cd0eab-db4f-4760-a168-ab1d5b77ca63)

**Comment by vincerubinetti** [comment]
> The idea of controlled/uncontrolled is a React construct

This is not true, unless you are talking about something different. Controlled/uncontrolled, as I understand it, just means whether the parent handles the state and declaratively sets it on the child, or the child handles its state on its own. I work heavily in both React and Vue, and you certainly have controlled/uncontrolled components in Vue. You can pass props to child components, and you can declaratively set `value` on native inputs.
