### ISSUE TITLE
Improve default styling for Indicators

### ISSUE THREAD

**Issue by FilipePfluck** [chakra-ui/zag#1089]
### Description

The SegmentGroup.Indicator come with some unwanted default styles I had to disable by overriding with !important (which I don't want to do)
Specifically, a height and width equal to the item container and a top and left properties equal to the padding of the element. So the indicator is filling the whole Item. 
Imo this goes against ark philosophy of being unstyled. I'm aware there are SOME styles (like display none for hiding or positioning for popover, menu, etc) but in this case I don't think those styles should be there. 

### Link to Reproduction (or Detailed Explanation)

https://github.com/FilipePfluck/PlucoUI

### Steps to Reproduce

Clone the repo
Run the storybook server
Remove the !important on the segment group and see what happens

### Ark UI Version

1.0.1

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

**Comment by cschroeter** [comment]
Fixed with https://github.com/chakra-ui/zag/commit/76115f7a56d90fd84e0154c1ed182b7e2be68f93
