### ISSUE TITLE
examples directory (vue and solidjs) does not work

### ISSUE THREAD

**Issue by uma-uc** [chakra-ui/zag#109]
# 🐛 Bug report

## 💻 Link to reproduction

CodeSandbox reproduction: https://your-codesandbox-link-goes-here.io

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI Core   |            |
| Browser          |            |
| Operating System |            |

**Comment by segunadebayo** [comment]
Make sure to run the `build:fast` or `start` command before starting the vue and solid.js examples.

**Comment by younho9** [comment]
I have tried `build:fast` or `start`, command before starting `start:vue` or `start:solid`.

But, when attempting to navigate to the component path, the following error occurs.

<img width="589" alt="Screen Shot 2022-07-11 at 3 53 10 PM" src="https://user-images.githubusercontent.com/48426991/178205719-69bebf3d-9bf0-47c7-b660-39ee49cf08a2.png">

It seems that cannot find exported type. Is this related to the vite issue? https://github.com/chakra-ui/zag/issues/12#issuecomment-938025838
