### ISSUE TITLE
[Menu] - OptionItem can't be activated by keyboard

### ISSUE THREAD

**Issue by FilipePfluck** [chakra-ui/zag#1090]
### Description

The menu items can be navigated with keyboard, however the OptionItem can't be activated/deactivated with space or enter

### Link to Reproduction (or Detailed Explanation)

https://github.com/FilipePfluck/PlucoUI

### Steps to Reproduce

clone the repo
run he storybook server
check out the Menu component
try to interact with the OptionItems with keyboard

### Ark UI Version

1.0.1

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

**Comment by cschroeter** [comment]
Fixed with https://github.com/chakra-ui/zag/commit/edba75423ad9f347cc115a96efa92fe20d9b9152
