### ISSUE TITLE
Clicking inside a Portal triggers the element behind it on mobile

### ISSUE THREAD

**Issue by juliomuhlbauer** [chakra-ui/zag#1110]
### Description

When clicking inside a Portal it triggers the element behind it on mobile and sometimes on desktop.

I tested on Chrome Android.

### Link to Reproduction

https://portal-mobile-dnwgwmzzp-juliomuhlbauer.vercel.app/mobile-bug

### Steps to reproduce

1. Go to https://portal-mobile-dnwgwmzzp-juliomuhlbauer.vercel.app/mobile-bug on Chrome Android
2. Try to click inside an element in the combobox
3. It will trigger the router push in the button

### Ark UI Version

0.15.0

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Additional Information

Github repo: https://github.com/juliomuhlbauer/portal-mobile-bug

**Comment by juliomuhlbauer** [comment]
Any updates on this?

**Comment by segunadebayo** [comment]
@juliomuhlbauer Feel free to open a PR for this.

**Comment by segunadebayo** [comment]
Thanks for your suggestion, @juliomuhlbauer.

This is now fixed and will release an update shortly.

**Comment by juliomuhlbauer** [comment]
Thanks! I was coming with a PR today too 😂
