### ISSUE TITLE
[Solid][Combobox] not working as expected

### ISSUE THREAD

**Issue by trevorblades** [chakra-ui/zag#1143]
# 🐛 Bug report

When I type something into the input to filter the list of options in the Solid combobox, the list is filtered as expected, but then when i press `down arrow` and then `enter` to select the first option, the first option (not listed in the filtered options) is selected.

I'm using the default combobox example shown in the zag docs under the solid tab.

## 💥 Steps to reproduce

1. Go to https://codesandbox.io/p/devbox/infallible-tereshkova-8q6mfj?file=/src/Combobox.tsx:9,3
2. Type "be" in the input to filter the list to include only "Benin"
3. Press enter
4. "Zambia" is populated in the input field, despite being filtered out of the list of options

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/p/devbox/infallible-tereshkova-8q6mfj?file=/src/Combobox.tsx:9,3

## 🧐 Expected behavior

"Benin" is selected. Perhaps the example code in the zag docs is incorrect? I'm not sure whether the issue is the implementation of zag in my example, or the underlying code in the library itself.

**Comment by segunadebayo** [comment]
Hi @trevorblades,

Yes, you missed something in your code. Please see the diff

```diff
  const collection = createMemo(() =>
    combobox.collection({
      items: options(),
      itemToValue: (item) => item.code,
      itemToString: (item) => item.label,
    }),
  );

+  const context = createMemo(() => ({
+    collection: collection(),
+  }))

  const [state, send] = useMachine(
    combobox.machine({
      id: createUniqueId(),
      collection: collection(),
      onOpenChange() {
        setOptions(comboboxData);
      },
      onInputValueChange({ value }) {
        const filtered = comboboxData.filter((item) =>
          item.label.toLowerCase().includes(value.toLowerCase()),
        );
        setOptions(filtered.length > 0 ? filtered : comboboxData);
      },
    }),
+   { context }
  );
```

https://codesandbox.io/p/devbox/infallible-tereshkova-forked-fm7jgj?file=%2Fsrc%2FCombobox.tsx%3A14%2C1-41%2C5
