### ISSUE TITLE
[React][Dialog] Dialog open state is broken since v0.32.x

### ISSUE THREAD

**Issue by fseglard** [chakra-ui/zag#1184]
# 🐛 Bug report

Hi!

When I use the `open` state from the machine context, it only works the first time the dialog is opened, but then the open state is not updated anymore causing the dialog to stay hidden.

The issue appears since the v0.32.x, prior of that version it's working fine. 

## 💥 Steps to reproduce

1. Click on the "Open dialog" button
2. The dialog should open
3. Close the dialog (click on the backdrop)
4. The dialog should be closed
5. Click again on the "Open dialog" button
6. The dialog does not open but the open state is `true`

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/p/sandbox/zag-dialog-tzwd43?file=%2Fsrc%2FDialog.tsx%3A15%2C8

The same example but with zag v0.31.0: https://codesandbox.io/p/sandbox/zag-dialog-0-31-8lr8tn?file=%2Fsrc%2FDialog.tsx%3A15%2C8

## 🧐 Expected behavior

The dialog should be open when the context props `open` is `true`.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      | 0.33.0           |
| Browser          | Chrome 120           |
| Operating System | Linux           |

**Comment by segunadebayo** [comment]
Thanks for catching this @fseglard

This was caused by a regression in `proxy-compare` for some reason. I've gone ahead and fallen back to the previous version for now.

We'll release a new update shortly.
