### ISSUE TITLE
[Select] Sending multiple values in multi selection mode

### ISSUE THREAD

**Issue by samadadi** [chakra-ui/zag#1204]
# 🐛 Bug report

I am using remix framework and I encountered a strange bug in regard to `Select` component. When multi selection mode is enabled and I select just one option everything is working fine and I am getting the value on the server but when I am selecting multiple options I get `null` on the server.

## 🧐 Expected behavior

I get all values on the server instead of `null`.

## 💻 Link to reproduction

[https://github.com/samadadi/remix-zag-reproduction](https://github.com/samadadi/remix-zag-reproduction)

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |    v0.34.0        |
| Browser          |      Chrome      |
| Operating System |     Linux       |

**Comment by segunadebayo** [comment]
Hi @samadadi ,

This issue doesn't contain a reproduction, and it's hard for us to help.

Please create a CodeSandbox or StackBlitz reproduction, and we'll re-open

**Comment by samadadi** [comment]
Hi. I added a simple github project. Please reopen this issue. For this project I used Ark UI.
 [remix-zag-reproduction](https://github.com/samadadi/remix-zag-reproduction)

**Comment by segunadebayo** [comment]
This is indeed a bug in Zag.js.

Here's a temporary workaround:

- Replace `Select.Control` and manually render hidden `input` fields
- Update the name to the format `frameworks[]`

```tsx
export default function Route() {
  const fetcher = useFetcher()

  const frameworks = ['React', 'Solid', 'Vue']

  return (
    <div>
      <fetcher.Form method="POST">
        <Select.Root multiple items={frameworks}>
          {(api) => (
            <>
              <Select.Label>Framework</Select.Label>
              <div>
                {api.value.map((value) => (
                  <input type="hidden" name="frameworks[]" value={value} />
                ))}
                <Select.Trigger>
                  <Select.ValueText placeholder="Select a Framework" />
                  <Select.Indicator>⯆</Select.Indicator>
                </Select.Trigger>
                <Select.ClearTrigger>Clear</Select.ClearTrigger>
              </div>
              <Portal>
                <Select.Positioner>
                  <Select.Content>
                    <Select.ItemGroup id="framework">
                      <Select.ItemGroupLabel htmlFor="framework">
                        Frameworks
                      </Select.ItemGroupLabel>
                      {frameworks.map((item) => (
                        <Select.Item key={item} item={item}>
                          <Select.ItemText>{item}</Select.ItemText>
                          <Select.ItemIndicator>✓</Select.ItemIndicator>
                        </Select.Item>
                      ))}
                    </Select.ItemGroup>
                  </Select.Content>
                </Select.Positioner>
              </Portal>
            </>
          )}
        </Select.Root>
        <button type="submit" name="intent" value="create">
          Submit
        </button>
      </fetcher.Form>
    </div>
  )
}
```

**Comment by samadadi** [comment]
There is another bug. When I load the page for the first time and there is not default value and there is not selected option  when I submit the form I get the first option. I mean the first option is automatically selected.

**Comment by segunadebayo** [comment]
Yes, I fixed that in Ark already
