### ISSUE TITLE
Select dropdown is not repositioned on resize

### ISSUE THREAD

**Issue by isBatak** [chakra-ui/zag#1212]
# 🐛 Bug report

https://github.com/chakra-ui/zag/assets/4128883/15065d1a-c39f-4df4-bc2c-eae763dc7bb6

Select dropdown is not repositioned on resize.
Same happens for all popover elements.

## 💥 Steps to reproduce

1. Go to Select docs https://zagjs.com/components/react/select
2. Click on Select to open a dropdown
3. Resize viewport

## 🧐 Expected behavior

Dropdown should be repossitioned

## 🧭 Possible Solution

Move `listeners: false,` above `...ctx.positioning` https://github.com/chakra-ui/zag/blob/d5b92271b2011b463067cfe210cef503fd3b9ce8/packages/machines/select/src/select.machine.ts#L369

All machines are affected https://github.com/search?q=repo%3Achakra-ui%2Fzag%20listeners%3A%20false%2C&type=code

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |           0.34.0 |
| Browser          |            Google Chrome  120.0.6099.234 |
| Operating System |           Mac OS Apple M2 Pro |

**Comment by samadadi** [comment]
I have the same problem.
