### ISSUE TITLE
Select strange scroll to selected item

### ISSUE THREAD

**Issue by isBatak** [chakra-ui/zag#1224]
# 🐛 Bug report

When Select component is at the bottom of the large content page and user click on the select the page will scroll to the selected element. 
This happens only when `value` prop is set initially.

https://github.com/chakra-ui/zag/assets/4128883/90d7040a-cac1-4b80-9c07-0e89ad2dcd89

## 💻 Link to reproduction

https://stackblitz.com/edit/stackblitz-starters-xjxhgd?description=React%20%20%20TypeScript%20starter%20project&file=src%2FSelect.tsx,src%2FApp.tsx&title=React%20Starter

## 🧐 Expected behavior

We should be able to disable this behaviour.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      | 0.34.0           |
| Browser          |  Chrome 120.0.6099.234          |
| Operating System |    MacOS Sonoma 14.1       |

**Comment by segunadebayo** [comment]
Good catch @isBatak.

I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
