### ISSUE TITLE
[Editable] cannot delete text when max-length reached

### ISSUE THREAD

**Issue by jeferson-sb** [chakra-ui/zag#1228]
# 🐛 Bug report

I was playing around with Ark components until I've noticed `<Editable>` component doesn't work properly when using `maxLength` prop, even if you keep hitting the backspace it doesn't type or erase anything, I've look in the code and thought this my related to zag:

https://github.com/chakra-ui/zag/assets/30840709/08985ddd-c30b-4a7e-8483-4880516bb657

## 💥 Steps to reproduce

1. Write a component either if `<Editable>` or using `@zag-js/editable` directly
2. Add maxLength `10`
3. Keep typing...
4. Try to delete using backspace

## 💻 Link to reproduction

[Stackblitz](https://stackblitz.com/edit/vitejs-vite-pnrkbn?file=src%2FApp.vue)

## 🧐 Expected behavior

Characters in the editable input should be deleted as I press backspace

## 🧭 Possible Solution

Not entirely sure, but maybe it's related to `TYPE` event in the machine 🤔:
https://github.com/chakra-ui/zag/blob/99c5a68890058b26f1d39ac25081ab8d3a6a96b6/packages/machines/editable/src/editable.machine.ts#L75-L80

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |            |
| Browser          |            |
| Operating System |            |

**Comment by segunadebayo** [comment]
Good catch @jeferson-sb.

I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
