### ISSUE TITLE
Check used HTML element when semantic structure needs it

### ISSUE THREAD

**Issue by Omikorin** [chakra-ui/zag#1229]
# 🐛 Bug report

When passing the mentioned below parts to an HTML element other than `label`, a component doesn't work.

- `root` part of the checkbox and the switch machine
- `item` part of the radio group machine

https://github.com/chakra-ui/ark/issues/1833#issuecomment-1841596904

chakra-ui/ark#1835

## 💥 Steps to reproduce

In the first linked issue

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |      latest      |
| Browser          |      Firefox      |
| Operating System |      Windows      |

**Comment by segunadebayo** [comment]
This is primarily a documentation thing. Let's add a warning to the `AsChildProps` docs about the invalid composition pattern (and the fact that the user will have to handle the rest if they use invalid tags)
