### ISSUE TITLE
Combobox with multiple=true and selectionBehavior=clear doesn't work

### ISSUE THREAD

**Issue by anilanar** [chakra-ui/zag#1276]
# 🐛 Bug report

## 💥 Steps to reproduce

1. Run `pnpm start-react` in this repo.
2. Go to `http://localhost:3000/combobox`
3. Enable `multiple` and set `selectionBehavior` to `clear`
4. Play with combobox.

Result: Combobox input doesn't stay empty. It's not cleared after selections. First interaction behavior is different than follow-up interactions.

## 🧐 Expected behavior

Combobox input always remains empty to allow custom value rendering.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |    5a199fdc8c9de339d766531bf70c584e652ccf3f       |
| Browser          |      chrome, firefox      |
| Operating System |     linux       |

## 📝 Additional information

https://github.com/chakra-ui/zag/assets/753736/1fbb7544-47a4-4099-8d5c-eec8a2e2eeb4

**Comment by TylerAPfledderer** [comment]
Looks like this is a part of [a known notated side-effect](https://github.com/chakra-ui/zag/blob/d27ca591bf8ffc6810985944d99c4c2b243490e9/packages/machines/combobox/src/combobox.machine.ts#L606) when syncing the context of the input value with the value state of the input field. The sync is occurring after invoking the selection change, thereby overriding the selection behavior. (Runs twice if you make the first selection, move away from the component, then go back in to make another selection)
