### ISSUE TITLE
Weird IOS webview bug with the Accordion Component

### ISSUE THREAD

**Issue by emma-r-slight** [chakra-ui/zag#128]
# 🐛 Bug report

 So this is difficult to reproduce  and debug, sorry about that.  I love what you are building here so felt it is important that I let you know what we discovered when our application went to production using your accordion component.  We found that in some situations the accordion won't open.  

## 💥 Steps to reproduce

1. Using an IOS device
2. Open a link to your website from either Instagram, Gmail, FB or LinkeIn
3. The link will open in a webview
4. Try to click the button to open the accordion
5. Nothing happens.

## 💻 Link to reproduction

CodeSandbox reproduction: https://your-codesandbox-link-goes-here.io

## 🧐 Expected behavior

The accordion should open when the button is 'touched'.

## 🧭 Possible Solution

I don't know what could be causing this.  FYI the in app webview for Slack and Twitter work fine 🙄 

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |         beta   |
| Browser        Instagram webview  |  FB webview     | LinkedIn Web VIew
| Operating System |         IOS   |

**Comment by anubra266** [comment]
I'm unable to reproduce this in zagjs @emma-r-slight 

https://user-images.githubusercontent.com/30869823/173517878-1b112007-3d55-49c1-b5f6-c3ea52b2382e.MP4
