### ISSUE TITLE
Add `onEscapeKeydown` handlers to menus

### ISSUE THREAD

**Issue by TGlide** [chakra-ui/zag#1329]
# 🚀 Feature request

Similar to `onPointerDownOutside` events and other similar fns, I'd like to see an `onEscapeKeydown` helper, that can be prevented. 

## 🧱 Problem Statement / Justification

This would be useful in cases you want to override or control the escape keydown behaviour.

## ✅ Proposed solution or API

```ts
onEscapeKeydown(e) {
  e.preventDefault() // prevents closing the menu
}
```

## ↩️ Alternatives

Currently, this is what I do:
```ts
function onEscapeKeydown(event: KeyboardEvent) {
  const target = event.target as HTMLElement
  const isCurrentMenu =
    target.dataset.scope === 'menu' && target.id.includes(state.value.context.id)

  if (event.key !== 'Escape' || !isSubmenu || !isCurrentMenu) return

  event.stopPropagation()
  menu.value.close()

  // focus parent menu instead of body
  const parentId = `menu:${parentMenu?.machine.state.context.id}:content`
  document.getElementById(parentId)?.focus()
}
```

Another option would be to expose a `closeOnEscape` prop, similar to [Melt UI's Dialog](https://melt-ui.com/docs/builders/dialog#disable-close-on-escape)

**Comment by segunadebayo** [comment]
Good idea @TGlide. Big fan of Melt UI

We'll consider adding both the callback and the boolean prop.

**Comment by TGlide** [comment]
> Good idea @TGlide. Big fan of Melt UI
> 
> We'll consider adding both the callback and the boolean prop.

Thank you! That means a lot.

And great, excited to see it!

**Comment by segunadebayo** [comment]
I just pushed this feature. It'll be available in the next release.

**Comment by TGlide** [comment]
Thank you!
