### ISSUE TITLE
Missing attributes in Slider parts

### ISSUE THREAD

**Issue by anubra266** [chakra-ui/zag#133]
-  [Here](https://zagjs.com/components/react/slider#disabled-state) the styles claim `data-part="root"` and `data-part="range"` have a `data-focus` attribute.

But they don’t [here](https://github.com/chakra-ui/zag/blob/5dc747bdb22eec6247d66a7b0ad1ef350ea6de63/packages/machines/slider/src/slider.connect.ts)

We should add this :

```js
"data-focus": dataAttr(isFocused)
```

to `rootProps` and `rangeProps` in that file. Make it follow alphabetical order with the properties in those objects

- [Here](https://zagjs.com/components/react/slider#invalid-state) the styles also claim that `data-part="root"` has a `data-invalid` attribute.

But it doesn't [in that same file](https://github.com/chakra-ui/zag/blob/5dc747bdb22eec6247d66a7b0ad1ef350ea6de63/packages/machines/slider/src/slider.connect.ts)

We should add this:

```js
"data-invalid": dataAttr(isInvalid)
```
to `rootProps` in that file. Don't forget alphabetic order.

**Comment by segunadebayo** [comment]
Done!
