### ISSUE TITLE
Popper elements: Cross-axis in `placement` serves no purpose

### ISSUE THREAD

**Issue by TGlide** [chakra-ui/zag#1341]
# 🐛 Bug report

Currently, due to these lines in [the popper package](https://github.com/chakra-ui/zag/blob/main/packages/utilities/popper/src/get-placement.ts#L49-L52):
```ts
    const { hasAlign } = getPlacementDetails(placement)


    return compact({
      crossAxis: hasAlign ? opts.shift : undefined,
```

The `crossAxis` key that's accepted in `positioning['placement']` serves no purpose. Instead, only the `mainAxis` is used, and for crossAxis you need to instead use the shift attribute, which is only useable with aligned items.

## 💥 Steps to reproduce

With a menu machine with the following options:
```ts
const [state, send, machine] = useMachine(
  zagMenu.machine({
    id: window.crypto.randomUUID(),
    positioning: 'bottom-end',
    offset: {
      mainAxis: 6,
      crossAxis: 6,
    },
  })
)
```

## 💻 Link to reproduction

I believe my explanation is sufficient to track down the issue, but let me know if you'd like a reproduction nonetheless, I'll be glad to provide one

## 🧐 Expected behavior

I expect the menu to be shifted in the crossAxis.

## 🧭 Possible Solution

I'd think the `crossAxis` should naturally work. Alternatively, `placement` should only accept `mainAxis`, or just accept a `number`, as a shorthand for `mainAxis`, and have JSDoc annotations to explain this pattern.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |     0.38.1       |
| Browser          |        Chrome    |
| Operating System |          Mac  |

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
