### ISSUE TITLE
Replace `klona/full` to solve the "Maximum call stack size exceeded" issue in Vue 2.7

### ISSUE THREAD

**Issue by L-orz** [chakra-ui/zag#1360]
# 🚀 Feature request

Replace `klona/full` with deep copy from another library.

## 🧱 Problem Statement / Justification

I'm trying to implement `ark-vue2` based on `ark-vue` (vue3). Most of it feels good, but I encountered the problem of `Maximum call stack size exceeded`. After checking, I found that machine internally uses `klona/full` for deep copying. The `Ref` in `vue2` has a reference property `__ob__`, which will cause `klona` to enter an infinite loop. 

## ✅ Proposed solution or API

`klona/index` / `lodash.cloneDeep`

## 📝 Additional Information

![image](https://github.com/chakra-ui/zag/assets/22721077/11791a6a-b588-4e99-8eca-827012e61995)

**Comment by 0fatihyildiz** [comment]
I have a similar problem in nextjs.

**Comment by segunadebayo** [comment]
Zag.js is primarily built for Vue >=3.

I'll update the docs to make them clearer. I'm sorry about the inconvenience, but I think you should upgrade to Vue 3 instead.

Regarding the issue in Next.js @0fatihyildiz, could you open a new issue with a reproduction? I'm curious to see and fix it. I might consider using `structuredClone` instead.

**Comment by 0fatihyildiz** [comment]
> Zag.js is primarily built for Vue >=3.
> 
> I'll update the docs to make them clearer. I'm sorry about the inconvenience, but I think you should upgrade to Vue 3 instead.
> 
> Regarding the issue in Next.js @0fatihyildiz, could you open a new issue with a reproduction? I'm curious to see and fix it. I might consider using `structuredClone` instead.

Of course, I can create a reprod in a few hours, I will let you know here when it is done. fyi

**Comment by L-orz** [comment]
This may not be specific to `vue2`, as objects with circular dependencies will also cause errors with `klona/full`. @segunadebayo 
https://github.com/lukeed/klona/issues/44
