### ISSUE TITLE
[Circular progress] circle diameter is not correct with --size variable

### ISSUE THREAD

**Issue by iNetJoJo** [chakra-ui/zag#1361]
circle dimeter is not correct when providing size variable.
multiple issues:
 * **r** property is hardcoed to 47 meaning its a magic number and does not apply to different sizes.
* **cx/cy** are bounded to viewbox which is **0 0 100 100** meaning this case works perfectly for cases where size of root is 100 / 100, size like 154px will not work.

![image](https://github.com/chakra-ui/zag/assets/48105082/9cce5d00-8e4c-4eaa-83f1-a341fa37fb2c)

## 🧭 Possible Solution

i wrote a hack on my side to fix this issue, and my question is should i open mr for this.

first thing first.

source of bug:
https://github.com/chakra-ui/zag/blob/main/packages/machines/progress/src/progress.connect.ts#L122

* circle:
circle is an svg, and a workaround i had to do is set this viewBox to use css vars too apply dynamic size. this will enable proportional sizes to stroke width problems with overflowing.

```tsx
viewBox="0 0 var(--size) var(--size)"
```

svgs support only center variant of stroke position.
![image](https://github.com/chakra-ui/zag/assets/48105082/a708b2d6-bdb4-4541-9e26-80778ab361cc)

* circleTrack
to fix cx, r and cy i added this code to solve the issue of dynamic sizes.

```tsx
// in source it is 42px, here i added calc logic which uses half of the size, and subtracts half of the thickness thus fixing the issue of centered stroke, issue that i shown in image above
r: 'calc(var(--size) / 2 - var(--thickness) / 2)',

// in source it is used 50px, since that is half of viewBox of 100 height/width, i added calc here for that.
cx: 'calc(var(--size) / 2)',
cy: 'calc(var(--size) / 2)',
```
   
* circleRange
this was more difficult part for me, so please if you think there is a cleaner way go for it.

```tsx
// this is my quick hack for percentage since null had bug in issue i posted yesterday.
const percentage = api.value !== null ? (api.value / max) * 100 : 0;
//coefficient is value i took from source which is 2.64 which tbh i have no clue where it comes from i just took it a coifficient from height/width of 100
const coefficient = 0.0264;

// determinant is same
const determinant = percentage * coefficient;

//in source code it is 264 hardcoded, i just set it here to keep logic centralised.
const subDeterminant = coefficient * 100;

// determinant is multiplied by size here, since size is variable this is to achieve dynamic diameters, in original code it worked only for diameter of 100

// second part of dashArray we usb subDeterminant and also multiply it with diameter, and subtrack it with scaled determinant
const strokeDashArray = `calc(${determinant} * var(--size)) calc(${subDeterminant} * var(--size) - (${determinant} * var(--size)))`;


// style
// r, cx, cy are same as in track
r: 'calc(var(--size) / 2 - var(--thickness) / 2)',
cx: 'calc(var(--size) / 2)',
cy: 'calc(var(--size) / 2)',
//offset in original logic is hardcoded to 66px, so i just took 0.66 coefficient to make it scalable with size aka dimaeter.
strokeDashoffset: 'calc(0.66 * var(--size))',
strokeDasharray: strokeDashArray,
```

after this result is now accurate, circle actually represents the --size variable.

![image](https://github.com/chakra-ui/zag/assets/48105082/1e964442-262e-495c-b544-c4d41f9813dc)

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |            |
| Browser          |            |
| Operating System |            |

**Comment by segunadebayo** [comment]
@iNetJoJo This looks good to me. Thanks for taking the time to create such a detailed fix suggestion.

Feel free to open a PR

**Comment by isBatak** [comment]
@iNetJoJo I'm guessing that `coefficient`, a.k.a `2.64` magic number is actually `circumference` which is calculated with this formula `circumference = 2 × π × radius`.

 https://www.youtube.com/watch?v=w_sR3DHzTt0&t=212s
