### ISSUE TITLE
Select: hidden select is being set to disabled when readOnly attribute is set

### ISSUE THREAD

**Issue by nmackey** [chakra-ui/zag#1377]
### Description

Hidden select of the Select component has `disabled` attribute set when readOnly is being set.  This causes the select to not be part of form values.  This breaks default HTML behavior for form elements.

### Link to Reproduction (or Detailed Explanation)

https://codesandbox.io/p/devbox/select-readonly-bug-wvw6nr?file=%2Fsrc%2FSelect.tsx

### Steps to Reproduce

Create a select component and set it as `readOnly`.  If you look at the hidden select DOM it will be marked as disabled.

### Ark UI Version

2.2.3

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

Chrome 123

### Additional Information

These are the problematic lines of code:
`hiddenSelectProps` has its `disabled` attribute set to `!isInteractive` - https://github.com/chakra-ui/zag/blob/main/packages/machines/select/src/select.connect.ts#L306
`isInteractive` is set to false if `isDisabled || readOnly` - https://github.com/chakra-ui/zag/blob/main/packages/machines/select/src/select.machine.ts#L43

Ark-UI spreads the `hiddenSelectProps` on the hidden `select` element - https://github.com/chakra-ui/ark/blob/4aad0c95cf7e3fdecc85ec083e16fd586cf7c3ee/packages/frameworks/react/src/select/select-control.tsx#L16

I was only testing in React, but looking at the code it shouldn't work in any framework.

Not sure if there are other form components that this effects or not, but is probably worth looking into to make sure.

**Comment by segunadebayo** [comment]
Good catch @nmackey,

I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
