### ISSUE TITLE
`data-acitve` is not deactivated if the mouse button is released on outside of its element

### ISSUE THREAD

**Issue by spring-raining** [chakra-ui/zag#1395]
# 🐛 Bug report

There is a problem with an element that has `data-active` attribute, if the mouse pointer moves out of the element while the mouse button is held down, the data-active is not deactivated when the mouse button is released. This problem occurs with components that have `active` state in context, such as Switch and Checkbox.

## 💥 Steps to reproduce

1. Go to https://codesandbox.io/p/devbox/distracted-zeh-wcr7yx?file=%2Fsrc%2FApp.tsx
2. Move the cursor out of the button while holding down the mouse button on the button element.
3. Button color is kept when the mouse button is released.

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/p/devbox/distracted-zeh-wcr7yx?file=%2Fsrc%2FApp.tsx

## 🧐 Expected behavior

`data-active` should be removed when the mouse button is released.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      | 0.44.0 |
| Browser          | Chrome 124.0.6367.18 |
| Operating System | macOS 13.6.4 |

**Comment by segunadebayo** [comment]
Good catch @spring-raining

I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.

**Comment by spring-raining** [comment]
I have confirmed that it works perfectly with the latest version. Thank you for your quick response!
