### ISSUE TITLE
[Combobox] Focus input on mount

### ISSUE THREAD

**Issue by fseglard** [chakra-ui/zag#1397]
# 🐛 Bug report

Hi!

When manually setting the focus on the input component on mount, it causes the input to not trigger anything when typing.

On the provided reproduction link, I'm using a `useEffect` with a ref to set the focus on the input on mount (which causes the issue), and I've also added a button to set the focus when clicked (which works).

I know I can use the `autoFocus` property to do that, but I still think it's an issue,

## 💥 Steps to reproduce

1. Go to the [reproduction link](https://codesandbox.io/p/devbox/kind-drake-sjtvzv?file=%2Fsrc%2FApp.tsx%3A20%2C6)
2. When the preview is loaded, the input should have the focus
3. Try to type something
4. The combobox is not working (the menu is not showing)
5. Click outside the input and then click on the "Set focus" button
6. Type something again
7. The combobox is working fine

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/p/devbox/kind-drake-sjtvzv?file=%2Fsrc%2FApp.tsx%3A20%2C6

## 🧐 Expected behavior

I should be able to manually set the focus on mount and the combobox should work fine.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      | 0.44.0           |
| Browser          | Chrome           |
| Operating System | Linux           |

**Comment by segunadebayo** [comment]
Hi @fseglard,

This is not technically a bug. I recommend waiting for the next tick before focusing on the input. This allows enough time for the machine to transition correctly on mount.

Changing it to `setTimeout` or `requestAnimationFrame` should work.

```tsx
useEffect(() => {
    requestAnimationFrame(()=>{
      inputRef.current?.focus();
    })
  }, []);
```

**Comment by fseglard** [comment]
Thanks @segunadebayo! 🙏
