### ISSUE TITLE
MenuItem is not processable with enter key when not Link element

### ISSUE THREAD

**Issue by erm1116** [chakra-ui/zag#1445]
# 🐛 Bug report

When using Menu, the Enter key event is not fired for MenuItem.
This causes an issue if you want to do something as a handler for the Click event.

Specifically, the situation is as follows
- Click event by Enter key is not fired for MenuItem other than a[href].
- In MenuContent, the keydown event is stopped propagation, and it is not possible to set onKeydown handler independently.

## 💥 Steps to reproduce

```tsx
<div {...api.contentProps}>
  <div
    {...api.getItemProps({ value: "value1" })}
    onClick={(e) => {
      alert("div: clicked"); // this is not fired
      e.preventDefault();
    }}
    onKeyDown={(e) => {
      alert("div: enter"); // this is not fired
    }}
  >
    <div
      onKeyDown={(e) => {
        alert("innterDiv: enter"); // this is not fired
      }}
    >
      div
    </div>
  </div>
  <a
    {...api.getItemProps({ value: "value2" })}
    href="#"
    onClick={(e) => {
      alert("link: clicked"); // it is fired because element is matched as a[href]
      e.preventDefault();
    }}
  >
    link(a[href])
  </a>
</div>
```

In the above example(this is same as codesandbox reproduction code)
- first div element's click/keydown event handler is not called with enter key
- second a element's click event handler is called with enter key

https://github.com/chakra-ui/zag/assets/38889285/222c1966-ca3b-4245-b7aa-3622fc536b14

## 💻 Link to reproduction

[CodeSandbox reproduction](https://codesandbox.io/p/sandbox/zagjs-menuitem-keyboard-9pyklm?file=%2Fsrc%2FApp.js%3A25%2C18&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clveoxzdk00063b6gjc8sn0l0%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clveoxzdk00023b6gte2nibae%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clveoxzdk00033b6g0jslppfx%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clveoxzdk00053b6gn6rzsu18%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B63.93636989%252C36.06363011%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clveoxzdk00023b6gte2nibae%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clveoxzdj00013b6gv9et49ic%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clvep79xe00023b6gc9abb68k%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A25%252C%2522startColumn%2522%253A18%252C%2522endLineNumber%2522%253A25%252C%2522endColumn%2522%253A18%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clveoxzdk00023b6gte2nibae%2522%252C%2522activeTabId%2522%253A%2522clvep79xe00023b6gc9abb68k%2522%257D%252C%2522clveoxzdk00053b6gn6rzsu18%2522%253A%257B%2522id%2522%253A%2522clveoxzdk00053b6gn6rzsu18%2522%252C%2522activeTabId%2522%253A%2522clveoxzdk00043b6g7upjl79c%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clveoxzdk00043b6g7upjl79c%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522SANDBOX_INFO%2522%252C%2522id%2522%253A%2522clveoy8et002y3b6guu4faxnx%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clveoxzdk00033b6g0jslppfx%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clveoxzdk00033b6g0jslppfx%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

## 🧐 Expected behavior

I expect one of the following
- Fire the click event even if it is not match with `a[href]`
- Can add own keydown event handler

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |     0.48.0       |
| Browser          |  Chromium Engine Version 124          |
| Operating System |       MacOS 14.3.1     |

**Comment by segunadebayo** [comment]
This is by design. The Menu uses virtual focus to navigate the items. Meaning the focus remains on the menu content all the time.

When an is selected, the onSelect is the best way to listen for selection. See the docs here
https://zagjs.com/components/react/menu#listening-for-item-selection


Links are a special case because they need to trigger navigation, hence the reason they’re manually clicked.

Use the merge props helper to combine the props of the content with your own custom handler

mergeProps(api.contentProps, { onKeyDown: …})

**Comment by erm1116** [comment]
@segunadebayo 
I know that by passing onSelect to Menu, I can detect the user's selection. 
However, this causes the processing to become redundant when handling each item is selected.
For example, let's assume there is a component like the following. Here, you want to call the API when either edit or delete is selected.

```tsx
import * as menu from "@zag-js/menu"
import { useMachine, normalizeProps } from "@zag-js/react"
import { useId } from "react"

export function Menu() {
  const [state, send] = useMachine(menu.machine({ id: useId() }))

  const api = menu.connect(state, send, normalizeProps)

  return (
    <div>
      <button {...api.triggerProps}>
        Actions <span {...api.indicatorProps}>▾</span>
      </button>
      <div {...api.positionerProps}>
        <ul {...api.contentProps}>
          <li {...api.getItemProps({ value: "edit" })}>Edit</li>
          <li {...api.getItemProps({ value: "delete" })}>Delete</li>
        </ul>
      </div>
    </div>
  )
}
```

For this, it is redundant to describe the processing with onSelect.

```tsx
import * as menu from "@zag-js/menu"
import { useMachine, normalizeProps } from "@zag-js/react"
import { useId } from "react"

export function Menu() {
  const [state, send] = useMachine(menu.machine({ 
    id: useId(),
    onSelect(details) {
      switch(details.value) {
        case "edit":
          callEditAPI()
        case "delete":
          callDeleteAPI()
        // If there are more menu items, this would continue
      }
    }
  }))
  ...
}
```

So I think we should be able to pass props like onSelectItem to Item.
(Just like the Radix UI [MenuItem](https://www.radix-ui.com/primitives/docs/components/dropdown-menu#item)'s `onSelect`)

```tsx
export function Menu() {
  ...
  return (
    <div>
      ...
      <div {...api.positionerProps}>
        <ul {...api.contentProps}>
          <li {...api.getItemProps({ value: "edit", onSelectItem: () => callEditAPI() })}>Edit</li>
          <li {...api.getItemProps({ value: "delete", onSelectItem: () => callDeleteAPI() })}>Delete</li>
        </ul>
      </div>
    </div>
  )
}
```

How do you think this??

**Comment by erm1116** [comment]
Perhaps I should have created the issue as a Feature Request instead of a Bug reporting
