### ISSUE TITLE
[React][Carousel] Next / Prev triggers not respecting slidesPerView with loop

### ISSUE THREAD

**Issue by KubaZachacz** [chakra-ui/zag#1447]
### Description

Hi again, I hope it's not the case with v 3 docs this time :) 

It seems like carousel Triggers are not respecting slidePerView prop while loop is true.
For example for `loop={true} slidesPerView={3}` and 9 items, first 2 clicks on **Next btn** moves all three items and then you have to click **Next btn** 7 times (without any effect) and it goes back to `currentIndex=0`.
But it seems to work fine with `loop={false}` when **Prev** and **Next** are disabled on the edges, you can make only 2 moves. 

### Link to Reproduction (or Detailed Explanation)

https://codesandbox.io/p/devbox/pensive-fire-tg3fym

### Steps to Reproduce

Just use last carousel example from docs.

### Ark UI Version

2.2.3

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

Google Chrome

**Comment by PsammystPrime** [comment]
What is the behaviour you expect to see?

**Comment by KubaZachacz** [comment]
@PsammystPrime at the moment, when I got 9 slides, 3 slides per view and loop, I have to click Next button 9 times to get back to begging, where slides changes only at first 2 click, then next 6 does nothing visible and last one goes back to start. 
Which possibly looks fine when you got only 1 slide per view.
So expected behawior for 9 slides and 3 slides per view is to make loop with 3 clicks, instead of 9 (number of slides)

**Comment by PsammystPrime** [comment]
Create a function that takes in a variable X which is the number of buttons (say 9 for this case). Then create another variable for Y ( that creates number of slides) which will be dependent on X hence if buttons are 3, it should should deliver 9slides and if buttons are 9 it should provide 27slides. Ratio is 1:3.

**Comment by PsammystPrime** [comment]
Create a function that takes in a variable X which is the number of buttons (say 9 for this case). Then create another variable for Y ( that creates number of slides) which will be dependent on X hence if buttons are 3, it should should deliver 9slides and if buttons are 9 it should provide 27slides. Ratio is 1:3.

**Comment by coheia** [comment]
Look that https://codesandbox.io/p/devbox/peaceful-montalcini-t5cn96?file=%2Fsrc%2FApp.tsx%3A22%2C24-22%2C37
