### ISSUE TITLE
[Vue][popover] Don't work on Nuxt and portalled is set to true by default

### ISSUE THREAD

**Issue by Theo-Rige** [chakra-ui/zag#1450]
# 🐛 Bug report

In using Nuxt 3 and the popover seems to be portalled by default, contrary to what is stated in the documentation, and it doesn't work with the Vue 3 SFC example and portalled option explicitly set to false.

## 💥 Steps to reproduce

1. Create a Nuxt 3 app
2. Create a Popover.client.vue component by copy pasting the Vue SFC example from the doc
3. Render it in app.vue
4. See the popover component doesn't works

## 💻 Link to reproduction

[CodeSandbox reproduction:](https://codesandbox.io/p/devbox/github/codesandbox/sandbox-templates/tree/main/nuxt?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clviglkvn00073j6htghkeoj3%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clviglkvn00023j6h4ttccmx7%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clviglkvn00043j6hsdb69fe2%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clviglkvn00063j6hpbl87rjj%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clviglkvn00023j6h4ttccmx7%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clviglkvn00013j6hwmt4yt1b%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%255D%252C%2522id%2522%253A%2522clviglkvn00023j6h4ttccmx7%2522%252C%2522activeTabId%2522%253A%2522clviglkvn00013j6hwmt4yt1b%2522%257D%252C%2522clviglkvn00063j6hpbl87rjj%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clviglkvn00053j6hrdb08wkt%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clviglkvn00063j6hpbl87rjj%2522%252C%2522activeTabId%2522%253A%2522clviglkvn00053j6hrdb08wkt%2522%257D%252C%2522clviglkvn00043j6hsdb69fe2%2522%253A%257B%2522id%2522%253A%2522clviglkvn00043j6hsdb69fe2%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clviglkvn00033j6hz7nnju0f%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clviglkvn00033j6hz7nnju0f%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

## 🧐 Expected behavior

The api.portalled be false by default and the popover works.

## 🌍 System information

| Software | Version(s) |
| - | - |
| Zag Version | 0.48.0 |
| Browser | Edge 124.0.2478.67 |
| Operating System | Windows |

## 📝 Additional information

![image](https://github.com/chakra-ui/zag/assets/60381394/87fcdb68-61b5-46f3-9bb6-7c1dc3d75115)
![image](https://github.com/chakra-ui/zag/assets/60381394/48abe511-145a-4f8f-9157-29a9a44a5806)

**Comment by segunadebayo** [comment]
Hi @Theo-Rige,

This is largely a documentation problem. Here's the snippet that should work:

```html
<script setup>
  import * as popover from "@zag-js/popover"
  import { normalizeProps, useMachine } from "@zag-js/vue"
  import { computed, Teleport, Fragment } from "vue"

  const [state, send] = useMachine(popover.machine({ id: "1" }))
  const api = computed(() => popover.connect(state.value, send, normalizeProps))
</script>

<template>
  <div ref="ref">
    <button v-bind="api.triggerProps">Click me</button>
    <Teleport to="body" :disabled="!api.portalled">
      <div v-bind="api.positionerProps">
        <div v-bind="api.contentProps">
          <div v-bind="api.titleProps">Presenters</div>
          <div v-bind="api.descriptionProps">Description</div>
          <button>Action Button</button>
          <button v-bind="api.closeTriggerProps">X</button>
        </div>
      </div>
    </Teleport>
  </div>
</template>
```
