### ISSUE TITLE
Cannot pass JSX to `toast.create`

### ISSUE THREAD

**Issue by tyko0x** [chakra-ui/zag#1486]
# 🐛 Bug report

I'm trying to figure out how to pass JSX to the `toast.create` function. There used to be a `render` method available, but it seems to have been removed as of the latest version (`0.49.0`). If I pass a `ReactNode` to the `description` prop, it causes an unhandled error.

## 💥 Steps to reproduce

1. Set up the toast components using the example: https://zagjs.com/components/react/toast#usage
2. Pass a description to the create function. This works as expected.

```tsx
toast.create({ title: "Hello", placement: "top-end", description: "description" })
```

3. Now pass JSX instead. There is an unhandled error.

```tsx
toast.create({ title: "Hello", placement: "top-end", description: <>description</> })
```

## 💻 Link to reproduction

https://codesandbox.io/p/sandbox/nameless-architecture-dyk99r

Click on the first button ("top-right"). Works as expected because description is a string (`"description"`).

Now click on the second button ("bottom-right"). Breaks because description is a `ReactNode` (`<>description</>`).

<img width="413" alt="image" src="https://github.com/chakra-ui/zag/assets/104043748/0fc2ee6e-b7c7-4508-9df7-b953a4eb3a38">

## 🧭 Possible Solution

Either allow JSX here, or bring back the `render` method.

**Comment by segunadebayo** [comment]
This was removed in favor of explicitly rendering/designing the toasts. The key driver for this decision is to make the toasts work in all frameworks without bias for React.

If you're okay with the TS error, you can still achieve the render function code like so:
https://codesandbox.io/p/sandbox/toast-custom-render-mcjvjf?file=%2Fsrc%2Ftoast.tsx%3A10%2C30

Another approach is to use functions for the title and description, these functions can return JSX if you want.

Thanks for understanding.

**Comment by anubra266** [comment]
@tyko0x This is an example of the function method
https://codesandbox.io/p/sandbox/quirky-fast-zqxph8?file=%2Fsrc%2Ftoast.tsx%3A6%2C20

**Comment by tyko0x** [comment]
I still can't access it. Code sandbox is not simple like it used to be 😞

**Comment by anubra266** [comment]
@tyko0x Try now. 😁

**Comment by tyko0x** [comment]
Got it, and the example makes sense. Thanks.
