### ISSUE TITLE
tooltip is not  interactive by default

### ISSUE THREAD

**Issue by wizardAEI** [chakra-ui/zag#1506]
# 🐛 Bug report

this is the doc:

![image](https://github.com/chakra-ui/zag/assets/61337085/2797bc54-27ea-4768-a793-963ab16c93e8)

when I use it in solidjs, I found that tooltip is non-interactive by default, I need to set it true

![image](https://github.com/chakra-ui/zag/assets/61337085/dd6abaae-f04f-4b66-a3e9-1169ad1b847b)

## 💻 Link to reproduction
[sandbox](https://codesandbox.io/p/github/wizardAEI/solid-zag-test/main?import=true&embed=1&file=%2Fpackage.json&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clwg19mft00063b6l934eeg76%2522%252C%2522sizes%2522%253A%255B60%252C40%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clwg19mft00023b6lemog5qq5%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clwg19mft00043b6l8lpxtpub%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clwg19mft00053b6ln6nzyzra%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clwg19mft00023b6lemog5qq5%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwg19mfs00013b6ld387czyw%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%255D%252C%2522id%2522%253A%2522clwg19mft00023b6lemog5qq5%2522%252C%2522activeTabId%2522%253A%2522clwg19mfs00013b6ld387czyw%2522%257D%252C%2522clwg19mft00053b6ln6nzyzra%2522%253A%257B%2522id%2522%253A%2522clwg19mft00053b6ln6nzyzra%2522%252C%2522activeTabId%2522%253A%2522clwg1dljj00p03b6l66hyiotv%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A3100%252C%2522id%2522%253A%2522clwg1dljj00p03b6l66hyiotv%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clwg19mft00043b6l8lpxtpub%2522%253A%257B%2522id%2522%253A%2522clwg19mft00043b6l8lpxtpub%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwg19mft00033b6lh7olw5ec%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clwg19mz9000pdlhr7pou1td3%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522CSB_RUN_OUTSIDE_CONTAINER%253D1%2520devcontainer%2520templates%2520apply%2520--template-id%2520%255C%2522ghcr.io%252Fdevcontainers%252Ftemplates%252Ftypescript-node%255C%2522%2520--template-args%2520%27%257B%257D%27%2520--features%2520%27%255B%255D%27%2522%252C%2522id%2522%253A%2522clwg1ad6j004p3b6lj81rxq6a%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522id%2522%253A%2522clwg1cz3v00ne3b6l9h16s6vx%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clwg1czg50018dlhrhkgj84z6%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clwg1ad6j004p3b6lj81rxq6a%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

and thank you for providing the component library; it has been very helpful to me!

**Comment by segunadebayo** [comment]
Good catch @wizardAEI. I've updated the docs accordingly.
