### ISSUE TITLE
[toast] No ghost element found in toast. Render the `ghostBefore` and `ghostAfter` elements

### ISSUE THREAD

**Issue by haoval** [chakra-ui/zag#1539]
Component: Toast
```JavaScript
...
toastApi.create({ type: 'error', title: 'AAA', description: 'BBB' })
```
It works!

But i have no idea why i got a warning message in console:
![warning](https://github.com/chakra-ui/zag/assets/39382437/10a634da-00ae-4a18-af8f-df89eb25d7ae)

Did i miss anything?
Thank you.

**Comment by cschroeter** [comment]
@haoval 

To prevent ui flickering you have to render this ghost elements like shown beloew

```jsx
    <div {...api.rootProps}>
      <span {...api.ghostBeforeProps} />
       ...
      <span {...api.ghostAfterProps} />
    </div>
    ```
