### ISSUE TITLE
[popover] `autoFocus` does not work

### ISSUE THREAD

**Issue by tsukkee** [chakra-ui/zag#1544]
# 🐛 Bug report
When I looking into packages/machines/popover, I found `autoFocus` is not refereed from anywhere.

 I don't use it in my usecase, but report this just because found above.

## 💥 Steps to reproduce

NaN

## 💻 Link to reproduction
NaN

## 🧐 Expected behavior
`autoFocus` work as expected but I don't know much about the spec...

## 🧭 Possible Solution
`autoFocus` will be handled properly.

## 🌍 System information

@zag-js/popover 0.51.2

**Comment by segunadebayo** [comment]
That's a good catch @tsukkee.

Pushed a fix for this.
