### ISSUE TITLE
NumberInput breaks on SSR on solid

### ISSUE THREAD

**Issue by indietyp** [chakra-ui/zag#1548]
# 🐛 Bug report

Using SolidStart and SSR, any interaction with the input is prevented if the component is rendered on the server.

## 💥 Steps to reproduce

Try to insert a number into the number field.

## 💻 Link to reproduction

https://codesandbox.io/p/devbox/repro-346q7w?file=%2Fsrc%2Froutes%2Findex.tsx%3A3%2C20

## 🧐 Expected behavior

SSR does not break the NumberInput

## 🧭 Possible Solution

You can force `NumberInput` to render on the client only using [`clientOnly`](https://docs.solidjs.com/solid-start/reference/client/client-only)

**Comment by segunadebayo** [comment]
Interesting. This is somewhat related to a [bug in solid start](https://github.com/solidjs/solid-start/issues/1522)

In the meantime, I've resolved it for now within Zag.js.

Will release a new version shortly.
