### ISSUE TITLE
Bug: Anchor as menu item hijacks focus

### ISSUE THREAD

**Issue by Jonas-C** [chakra-ui/zag#1583]
# 🐛 Bug report

If an anchor tag is included as one of the children (or grandchildren) of a menu, it automatically gains focus as the menu is opened. This messes up stuff like screen readers. 

## 💥 Steps to reproduce

1. Open the Codesandbox
2. Open the menu
3. Optionally, navigate to it with a screen reader.

## 💻 Link to reproduction
[Codesandbox](https://codesandbox.io/p/sandbox/awesome-architecture-2rvt85?file=%2Fsrc%2FApp.tsx%3A24%2C16&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clx972qcj00062e6a8ycdggnj%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clx972qcj00022e6anmphbj45%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clx972qcj00032e6a7u4z8n6o%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clx972qcj00052e6a8zaootu7%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clx972qcj00022e6anmphbj45%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clx972qcj00012e6aa5ivdt4b%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clx9732x200352e6ados1s9en%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A15%252C%2522startColumn%2522%253A29%252C%2522endLineNumber%2522%253A15%252C%2522endColumn%2522%253A29%257D%255D%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clx97o0rc00022e6anzzn7lj2%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A24%252C%2522startColumn%2522%253A16%252C%2522endLineNumber%2522%253A24%252C%2522endColumn%2522%253A16%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clx972qcj00022e6anmphbj45%2522%252C%2522activeTabId%2522%253A%2522clx97o0rc00022e6anzzn7lj2%2522%257D%252C%2522clx972qcj00052e6a8zaootu7%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clx972qcj00042e6ao0ub24kn%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clx972qcj00052e6a8zaootu7%2522%252C%2522activeTabId%2522%253A%2522clx972qcj00042e6ao0ub24kn%2522%257D%252C%2522clx972qcj00032e6a7u4z8n6o%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clx972qcj00032e6a7u4z8n6o%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)
## 🧐 Expected behavior

I'd like for the different states to be kept in sync, regardless of what the underlying menu item is.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      | 0.55.0           |
| Browser          |  Firefox, Chromium, Safari          |
| Operating System | MacOS           |

**Comment by Jonas-C** [comment]
I thought this was a dupe, but it actually looks like a regression

**Comment by segunadebayo** [comment]
Good catch @Jonas-C.

I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
