### ISSUE TITLE
[React][Tooltip]: Tooltip doesn't when when you tab to a button that's outside the viewport

### ISSUE THREAD

**Issue by abdel-17** [chakra-ui/zag#1589]
# 🐛 Bug report

When you navigate to a button that's outside of viewport, the tooltip doesn't show up due to the browser scroll.

## 💥 Steps to reproduce

1. Go to https://stackblitz.com/edit/vitejs-vite-khtf65
2. Use tab to navigate to the buttons
3. Observe how the button that's out of view doesn't show its tooltip

## 💻 Link to reproduction

Stackblitz Reproduction: https://stackblitz.com/edit/vitejs-vite-khtf65

(Not sure if using Stackblitz will be an issue. By the time I opened the issue, I had already finished the reproduction. I can redo it in CodeSandbox if needed.)

## 🧐 Expected behavior

The tooltip should show up.

## 🧭 Possible Solution

Probably detect if the trigger element is outside the viewport first when opening via tab before triggering the "close on scroll" behavior.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      | 0.56.1 |
| Browser          | Chrome Version 125.0.6422.142 (Official Build) (x86_64) |
| Operating System | macOS Sonoma 14.5 |

**Comment by segunadebayo** [comment]
This is by design. The tooltip closes when the overflow parent scrolls.

I've exposed `closeOnScroll` as a machine property you can use to disable this behavior so that your use case can work.

Will do a new release shortly
