### ISSUE TITLE
[React][TreeView] api throwing "`selectedValue.includes` is not a function" error for several methods

### ISSUE THREAD

**Issue by victorvianaom** [chakra-ui/zag#1603]
Hello there, if you go to the [React Machine Tree View Example](https://zag-nextjs-git-lit-components-chakra-ui.vercel.app/tree-view), you'll see that clicking in "Callapse All" and "Deselect All" will throw an error in below line:

https://github.com/chakra-ui/zag/blob/d06197a3ec70498c3b3168deaad798cb3e1d48d9/packages/machines/tree-view/src/tree-view.connect.ts#L29

Furthermore I tested selecting, deselecting, collapsing and expanding a single tree node, and all of them throw the same error.

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.

**Comment by victorvianaom** [comment]
> I just pushed a fix for this. We'll release an update shortly.
> 
> If the issue persists after upgrading, I'll re-open it.

Right! Thanks a lot @segunadebayo
