### ISSUE TITLE
Button

### ISSUE THREAD

**Issue by bstro** [chakra-ui/zag#163]
# 🚀 Feature request

I posted this as a discussion a few months ago but thought I would instead submit it as a proper feature request. Zag looks like a pretty sweet library and I'm thinking of switching out React-ARIA with Zag on a project. One thing for me that Zag.js is missing (understandably as the library was just released) is a button component that handles accessibility/keyboard navigation like React-ARIA.

## 🧱 Problem Statement / Justification

Buttons are a basic component for any component library. Even though they seem simple on the surface, there's a lot of work involved with smoothing out behavior across different kinds of devices (touch/mouse/keyboard) while supporting a pleasant developer experience. Pitching a headless framework to my team is a hard sell without a button

## 📝 Additional Information

https://react-spectrum.adobe.com/react-aria/useButton.html
https://react-spectrum.adobe.com/blog/building-a-button-part-1.html
https://mui.com/base/react-button/#the-usebutton-hook

**Comment by segunadebayo** [comment]
Closing in favor of #250
