### ISSUE TITLE
Combobox Tasks

### ISSUE THREAD

**Issue by segunadebayo** [chakra-ui/zag#164]
- [ ] support screen reader announcements (with and without section)
- [ ] user can provide objects as values
- [ ] user can decide what gets rendered in the input value
- [ ] user can control when the popup opens
- [ ] support for error message and help text
- [ ] Move event handling to the combobox popup instead of option items (for performance)
- [ ] Add `openOnFocus` prop (If it's not readonly)
- [ ] Add `closeOnSelect` prop

**Comment by anilanar** [comment]
Suggestion: An alternative combobox mode (or a separate machine) that behaves more like a menu with text filtering. The main difference is that combobox would be open as long as input is focused.

**Comment by anubra266** [comment]
> Suggestion: An alternative combobox mode (or a separate machine) that behaves more like a menu with text filtering. The main difference is that combobox would be open as long as input is focused.

@anilanar Could you shed more context and give a use case

**Comment by anilanar** [comment]
The use case is select/multi-select combobox where 
1. user potentially doesn't have enough knowledge to input text without seeing combobox options. for example, github labels.
2. there are too many options, thus requiring text filtering.

**Comment by anubra266** [comment]
@anilanar Isn't this what you're looking for?
<img width="403" alt="CleanShot 2022-08-14 at 12 29 21@2x" src="https://user-images.githubusercontent.com/30869823/184534643-461b0c7b-2ab9-46c8-a0ca-ad7d6af01808.png">

**Comment by anilanar** [comment]
That isn't sufficient, because it doesn't open on focus.

**Comment by anilanar** [comment]
The use case is select/multi-select combobox where 
1. user potentially doesn't have enough knowledge to input text without seeing combobox options. for example, github labels.
2. there are too many options, thus requiring text filtering.

In addition, with multi-selection, it's sometimes more preferable to not close combobox on select.

**Comment by anubra266** [comment]
@anilanar The way I see it a `openOnFocus` and `closeOnSelect` prop should be okay right?

**Comment by anilanar** [comment]
Yes, but it's harder to then imagine if there's any state that is `focused` but not `open`.
It would be simpler to introduce a mode that makes `isOpen = isFocused`.

**Comment by anubra266** [comment]
@anilanar I think it's better to leave the latter part to developers. You might want it to be open when focused and want it to close once selected. And in your usecase, there's no way you want it to be focused and close.

**Comment by anilanar** [comment]
Bug report:

Reproduction:

1. In next-ts example project, click on toggle button.
2. Immediately hit TAB.

It crashes with:

```
TypeError: ctx2.selectionData is null
```

In `selectOption` action, the following line fails because it assumes (with the `!` operator) that there's a selection when there's none:

```
          if (ctx.selectionBehavior === "set") {
            value = ctx.selectionData!.label
          }
```

**Comment by anilanar** [comment]
Bug or not?

Reproduction:

1. Set `selectOnTab: false`
2. Click toggle button
3. Hit arrow down couple times to highlight an option.
4. Hit tab 

Outcome: State stays in `interacting` (so it thinks it still has focus), focuses listbox element.
Expected: State switches to `idle`, focuses the next element in page.

**Comment by anubra266** [comment]
> Bug or not?
> 
> Reproduction:
> 
> 1. Set `selectOnTab: false`
> 2. Click toggle button
> 3. Hit arrow down couple times to highlight an option.
> 4. Hit tab
> 
> Outcome: State stays in `interacting` (so it thinks it still has focus), focuses listbox element. Expected: State switches to `idle`, focuses the next element in page.

@anilanar It's a bug, please open an issue.

**Comment by anilanar** [comment]
Potential problem:

After `closeOnSelect: false` is implemented, implementing doesn't feel natural because the last selection is stored in `context.selectionData` and `onSelect` is triggered with a watch on that. So clicking on the same option doesn't trigger an `onSelect` because `context.selectionData` doesn't change.

**Comment by anilanar** [comment]
Another case of double emitting click events similar to #237:

When `closeOnSelect: false` is implemented, option click events are emitted twice, breaking the use case of toggleable options. It's due to `onPointerUp` event handler, which manually triggers an additional `click` event.

**Comment by segunadebayo** [comment]
Hi @anilanar, It'll be helpful if you also attach a minimal reproduction for these issues. or at least a screen recording that captures the bug.

**Comment by anilanar** [comment]
@segunadebayo I implemented `closeOnSelect: false` myself, so there's no reproduction on existing code yet. I edited above posts and added reproductions anyways.

**Comment by anilanar** [comment]
Feature request:

Imagine a case where there's an existing form component library. To integrate combobox into such a such library, the plan is to integrate it similar to an `input`, `select` etc. Labels and auto-id generation comes from the library itself. It passes `id` to the input component.

In such a scenario, the current combobox implementation is incompatible because it generates its own id for the input. Thus, a label outside cannot use `for` attribute to refer to the combobox.

My request is to let combobox machine take a custom id for input as an option, or rethink how ids are handled in general.

**Comment by anubra266** [comment]
> I implemented `closeOnSelect: false` myself, so there's no reproduction on existing code yet. I edited above posts and added reproductions anyways.

Hi @anilanar would be nice for you to open a different issue, to track your specific case.

**Comment by segunadebayo** [comment]
I'll open separate issues and PRs for this task
