### ISSUE TITLE
`closeOnSelect: true` not respected when `multiple: true`

### ISSUE THREAD

**Issue by iyefrat** [chakra-ui/zag#1644]
# 🐛 Bug report

`closeOnSelect: true` not respected when `multiple: true`, due to this:
https://github.com/chakra-ui/zag/blob/49bf73b7119bdd5dfd40d33119c3543626e201f0/packages/machines/select/src/select.machine.ts#L368-L371 

## 💥 Steps to reproduce

1. Select multiple items in the codesandbox
2. note that the select menu stays open

## 💻 Link to reproduction
https://codesandbox.io/p/sandbox/zag-close-on-select-j2ff4z

## 🧐 Expected behavior

For the select screen to close

## 🧭 Possible Solution

If you agree that my expected behavior is more intuitive, removing the override

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |      0.59.0      |
| Browser          |    Firefox 127.0.2        |
| Operating System |      MacOS 14.5      |

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
