### ISSUE TITLE
Slider Thumb calculation wrong when included in closed Accordion Item

### ISSUE THREAD

**Issue by maxch-aa** [chakra-ui/zag#1648]
# 🐛 Bug report

## 💥 Steps to reproduce

1. Include Slider in Accordion Item
2. Set Accordion to be closed by default
3. Open the page and click on a closed accordion item
4. See error that the thumb position is incorrect

## 💻 Link to reproduction
https://stackblitz.com/edit/vitejs-vite-ztem1l

## 🧐 Expected behavior

Slider should have means to recalculate the thumb position when its parent display property changes.

## 🧭 Possible Solution

Calculate the thumb inset position only when the slider is visible.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| @ark-ui/react      |      ^3.5.0      |
| Browser          |    any        |
| Operating System |     any      |

## 📝 Additional information
![thumb position bug](https://github.com/chakra-ui/zag/assets/45965282/eab92bb9-254f-4095-a583-27499f02aa63)

**Comment by segunadebayo** [comment]
Looking into this.

In the meantime, I recommend adding the thumbSize

```jsx
<Slider thumbSize={{ width: 20, height: 20 }} />
```

**Comment by segunadebayo** [comment]
Looking at this a bit deeper. I wouldn't add more code to Zag to observe the accordion content.

The solution to this:

- Adding the static `thumbSize` like above
- Use the `lazyMount` option in Ark UI
- Set `thumbAlignment` to `center` and add an extra padding-x to the slider root
