### ISSUE TITLE
Bug: Pasting in combobox tagsinput composition calls onValueChange twice

### ISSUE THREAD

**Issue by Jonas-C** [chakra-ui/zag#1661]
# 🐛 Bug report
When pasting a value into the combobox and tag-input composition example, certain values causes `onValueChange` to be called twice, leading to the value being added twice. This is with `addOnPaste` disabled.

## 💥 Steps to reproduce

1. Copy a word, for instance "part"
4. Go to https://zag-nextjs-git-changeset-release-main-chakra-ui.vercel.app/composition/combo-tags 
5. Paste and press enter.
6. The value is added twice.

## 🧐 Expected behavior

The value should only be added once.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |  0.61.0          |
| Browser          | Firefox            |
| Operating System | MacOS           |

## 📝 Additional information

This does not happen for all words. "at" works, "rat" works, but "ark" does not. 

There's a lot of inconsistent behavior when pasting with this composition. Let me know if I should add a couple of more things to this issue.

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

Feel free to list out any other inconsistencies you found. Curious to see
