### ISSUE TITLE
TagsInput: deleting a pasted value completely disables pasting

### ISSUE THREAD

**Issue by Jonas-C** [chakra-ui/zag#1662]
# 🐛 Bug report

After pasting a value and pressing enter, deleting the created tag causes pasting to be disabled altogether

1. Go to https://zagjs.com/components/react/tags-input
2. Paste an arbitrary value. Press enter.
3. Delete the value and paste again.
4. Pasting does not work

## 🧐 Expected behavior

Pasting should keep on working.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      | 0.61.0           |
| Browser          | Firefox           |
| Operating System | MacOS           |

## 📝 Additional information
This happens regardless of `addOnPaste` status

**Comment by segunadebayo** [comment]
Good catch! Most likely, the machine is in a state that doesn't handle the paste event.

Should be a quick fix.

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
