### ISSUE TITLE
Bug: TagsInput does not allow for repeat pasting and undo.

### ISSUE THREAD

**Issue by Jonas-C** [chakra-ui/zag#1665]
# 🐛 Bug report

You're only allowed to paste a value once in TagsInput without pressing enter. The paste action cannot be undone like any other text action.

## 💥 Steps to reproduce

1. Go to https://zagjs.com/components/react/tags-input
2. Paste a value. Try to paste it again without pressing enter. Nothing happens.
3. Try to undo the paste action. Nothing happens.

## 🧐 Expected behavior

I'd expect that pasting "foo" twice would result in the input field having "foofoo" as its value. I would also expect that undoing a paste results in the pasted content being removed.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      | 0.61.0           |
| Browser          | Firefox           |
| Operating System | MacOS           |

**Comment by segunadebayo** [comment]
Good catch @Jonas-C.

Indeed calling `e.preventDefault` on the paste event was a little naive which prevented some editing capabilities.

Switched to handling events from the `onChange` callback instead. Will publish a new release shortly
