### ISSUE TITLE
docs: typo

### ISSUE THREAD

**Issue by Hugos68** [chakra-ui/zag#1694]
# 🐛 Bug report

There is a typo in the following sentence:
> Now, let's say you'd like to udpate the selected accordion based on props passed to the Accordion component, here is how to do that in React:

(See the word `udpate`, it should probably be `update`)

## 💥 Steps to reproduce

1. Go to https://zagjs.com/overview/programmatic-control#using-exposed-methods
2. View the typo
3. 
## 💻 Link to reproduction

https://zagjs.com/overview/programmatic-control#using-exposed-methods

## 🧐 Expected behavior

It should be spelled correctly.

## 🧭 Possible Solution

Not relevant.

## 🌍 System information

Not relevant.

## 📝 Additional information

Not relevant.

**Comment by segunadebayo** [comment]
Good catch.

I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
