### ISSUE TITLE
Switch useMachine type error

### ISSUE THREAD

**Issue by endigo9740** [chakra-ui/zag#1698]
# 🐛 Bug report

While implementing the Zag Switch `useMachine` in both [React](https://zagjs.com/components/react/switch) and [Svelte components](https://github.com/chakra-ui/zag/blob/main/website/data/snippets/svelte/switch/usage.mdx). , we're seeing the following type errors:

![Screenshot 2024-07-26 at 1 15 40 PM](https://github.com/user-attachments/assets/4c1d67e8-4351-4bdc-886c-f9110e2d85c8)

![Screenshot 2024-07-26 at 1 15 54 PM](https://github.com/user-attachments/assets/db9c23cb-a870-4d57-b7e9-644aced9512c)

## 💥 Steps to reproduce

Implement the Switch component `useMachine` in React or Svelte per the documentation. The components operate as expected, we just see the red squiggles in VS Code!

## 💻 Link to reproduction

This was identified as part of a pending PR for our current library migration to use Zag:
https://github.com/skeletonlabs/skeleton/pull/2778

Though the issues should be present for any implementation of the Switch component.

## 🧐 Expected behavior

We've also tested Accordion and Avatar components without issue, so the type issue is limited to Switch so far.

## 🧭 Possible Solution

Likely a type or documentation issue.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |  0.62.1 |
| Browser          | (not a browser issue) |
| Operating System | macOS Senoma 14.5 |

## 📝 Additional information

As a small aside, the Switch component import statement is prefixed with `zagSwitch` rather than `switch`, which breaks from the convention seen in other components in the Zag documentation website.

```ts
import * as zagSwitch from "@zag-js/switch"
```

**Comment by endigo9740** [comment]
Quick update - we've been in the process of updating several dependencies in our monorepo project, and surprisingly this issue is no longer present. Even though we did not update our Zag Switch dependency itself. We're now able to remove the "ignore" comments and all is behaving as expected. I might still recommend testing to confirm, but otherwise this may have been a misconfig on our end (sorry!)

That said, I'll leave this issue open merely for the follow up item reported in "Additional Information" - the alias naming. Just let me know if you would like me to break that out to it's own dedicated issue. I'm happy to do so!

Either way, thanks for providing Zag. It's wonderful!

**Comment by segunadebayo** [comment]
I was going to say this as well. It's probably related to mismatching versions.

The general recommendation is to use the same version for all zag-js/* packages.
