### ISSUE TITLE
NumberInput stops responding to up/down/enter once enter is pressed

### ISSUE THREAD

**Issue by thekarel** [chakra-ui/zag#1710]
### Description

When I go to https://ark-ui.com/react/docs/components/number-input, click on the example input, press enter, I expect the up/down keys to still work but instead these keys stop working.

Also noticed that pressing enter in the input removes the `data-focus` attribute from HTML.

Thing work again after blur/focus.

### Link to Reproduction (or Detailed Explanation)

https://ark-ui.com/react/docs/components/number-input

### Steps to Reproduce

1. Go to https://ark-ui.com/react/docs/components/number-input
2. Click inside the number input
3. Press enter
4. Press up or down
5. The number is not changing

### Ark UI Version

latest

### Framework

- [ ] React
- [ ] Solid
- [ ] Vue

### Browser

Brave (latest), Safari (latest)

### Additional Information

Noticed in my own setup that the custom `onKeyDown` handler also stops working

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update in Zag and then Ark shortly.

If the issue persists after upgrading, I'll re-open it.
