### ISSUE TITLE
Progress Circle indeterminate mode animation not working as expected

### ISSUE THREAD

**Issue by endigo9740** [chakra-ui/zag#1716]
# 🐛 Bug report

We're currently trying to implement the React and Svelte version of the [Progress Circle component](https://zagjs.com/components/react/circular-progress#methods-and-properties). We're using indeterminate mode by setting `value={null}`. Unfortunately it's unclear how the animation is supposed to trigger. If this is owned by Zag, or something we have to implement on our end?

Here's what we see currently. When value is `null` the meter is filled 100% and no animation is present.

![Screenshot 2024-08-01 at 2 51 39 PM](https://github.com/user-attachments/assets/ef3e6907-934b-474b-8255-5d4576dc0e2d)

## 💥 Steps to reproduce

1. Visit the [Progress Circle documentation](https://zagjs.com/components/react/circular-progress#methods-and-properties)
2. View the live example rendered at the top of the page
3. Tap the "indeterminate" button
4. A spinning animation will be displayed.

## 💻 Link to reproduction

Here's the source for our implementation, which aside from some small adjustments, should operate nearly 1:1 with your documentation example:

- [React component](https://github.com/skeletonlabs/skeleton/blob/c07f5140ad48d6fca0332fa35d2bbee3d75bf59a/packages/skeleton-react/src/lib/components/ProgressRing/ProgressRing.tsx)
- [Svelte component](https://github.com/skeletonlabs/skeleton/blob/87f4f8929d717dd9e2b34ebd90711914fea09729/packages/skeleton-svelte/src/lib/components/ProgressRing/ProgressRing.svelte)

## 🧐 Expected behavior

Per the documentation, the animation seems to run automatically when `value` is `null`. We've even taken time to inspect the component example implemented on the doc site here:
https://github.com/chakra-ui/zag/blob/main/website/components/machines/progress-circular.tsx

There's nothing here indicating any additional effort needed for the component to animate when in indeterminate mode.

## 🧭 Possible Solution

Two things:

1. Let us know if our expectations of Zag providing this animation is accurate
2. Consider [updating your documentation](https://zagjs.com/components/react/circular-progress#using-the-indeterminate-state) to describe how indeterminate animations should operate
    - Option 1: Controlled by Zag
    - Option 2: Controlled on our side (ideally with an example of how!)

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      | 0.63.0 |
| Browser          | Chrome 127.0.6533.89 |
| Operating System | macOS Senoma 14.5 |

## 📝 Additional information

This is [Chris from Skeleton](https://github.com/chakra-ui/zag/discussions/1714). I knew we would be causing some "trouble" sooner or later here :)

**Comment by segunadebayo** [comment]
Hey Chris, It's a pleasure to connect. Excited about the collaboration with Skeleton.

Regarding the indeterminate state, this should be styled in the userland code. Zag doesn't handle style/animation-related css code.

You can get some styling ideas from here:
https://github.com/chakra-ui/zag/blob/main/shared/src/css/progress.css

If you have some time, feel free to open a PR to improve the progress docs to address this

**Comment by endigo9740** [comment]
Thanks Segun, will do.
