### ISSUE TITLE
Closing a nested dialog focuses the first focusable element in the parent dialog.

### ISSUE THREAD

**Issue by Jonas-C** [chakra-ui/zag#1718]
# 🐛 Bug report

When nesting a dialog within another dialog, closing the nested dialog causes the first focusable element in the root dialog to gain focus.

## 💥 Steps to reproduce

1. Navigate to the dialog trigger by tabbing to it. Press it.
2. Navigate to the nested dialog trigger. Press it.
3. Close the nested dialog. Focus should be on "open nested", but is on "close"

## 💻 Link to reproduction
https://codesandbox.io/p/sandbox/little-pine-9kfpmp

## 🧐 Expected behavior

Dialog triggers should regain focus, unless `finalFocusEl` is specified.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |  0.64.0          |
| Browser          |  Firefox          |
| Operating System |  MacOS          |

**Comment by segunadebayo** [comment]
Might be related to how to focus trap pauses/resumes between the parent and child dialog.

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
