### ISSUE TITLE
Clicking outside of a dialog on mobile passes click events through

### ISSUE THREAD

**Issue by Jonas-C** [chakra-ui/zag#1720]
# 🐛 Bug report

When clicking outside of `DialogContent` on a mobile device (or mobile emulation in the browser), click events are passed through to the actual element that is being clicked. If you have a full-screen dialog with overlapping close and open triggers in the z-axis, you're pretty much forced to reload the entire page.

1. Use a mobile device or mobile emulation in your favourite browser.
2. Open the dialog.
3. Press one of the visible (and interactive) elements still visible on the screen. 

## 💻 Link to reproduction
https://zagjs.com/components/react/dialog

## 🧐 Expected behavior

The Dialog backdrop should prevent click events from being passed down to the elements the dialog "covers"

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      | 0.64.0           |
| Browser          | Firefox/Chrome/Safari           |
| Operating System |  MacOS/iOS          |

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
