### ISSUE TITLE
Popover trigger does not regain focus when closing with close trigger.

### ISSUE THREAD

**Issue by Jonas-C** [chakra-ui/zag#1746]
# 🐛 Bug report

When closing a popover with a popover close trigger, the popover trigger does not regain focus.

## 💥 Steps to reproduce

1. Tab to the popover. Open it with your keyboard.
2. Tab to the popover close trigger. Press it with keyboard. 
3. Focus is not on trigger.

## 💻 Link to reproduction
https://zagjs.com/components/react/popover

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |  0.65.0          |
| Browser          |  Firefox           |
| Operating System |  MacOS          |

**Comment by segunadebayo** [comment]
As always, I appreciate you catching these bugs.

I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
