### ISSUE TITLE
Controlled popovers does not return focus to popover trigger when closed

### ISSUE THREAD

**Issue by Jonas-C** [chakra-ui/zag#1747]
# 🐛 Bug report

When marking a popover as controlled, focus is not returned to the popover trigger when the popover trigger is closed.

## 💥 Steps to reproduce

1. Tab to the popover trigger. Press it with your keyboard.
2. Press ESC. The popover trigger is not focused.

## 💻 Link to reproduction
https://codesandbox.io/p/sandbox/mystifying-fire-forked-5mwqnd?workspaceId=c039803d-1cb1-4768-bc74-3b365d95b325

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |  0.65.0          |
| Browser          | Firefox           |
| Operating System |  MacOS          |

## 📝 Additional information

The source is more or less ripped from ark. If the example is wrong, I'm assuming this is an issue that needs to be fixed in ark instead.

**Comment by segunadebayo** [comment]
Good catch @Jonas-C.

I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
