### ISSUE TITLE
Menu: lazyMounting causes first menu item to not be focused

### ISSUE THREAD

**Issue by Jonas-C** [chakra-ui/zag#1771]
### Description

When setting `lazyMount` on `Menu.Root`, the first item of the menu is not automatically focused. `unmountOnExit` is only to make it more explicit. 

### Link to Reproduction (or Detailed Explanation)

https://codesandbox.io/p/sandbox/hopeful-mountain-g9mjsy

### Steps to Reproduce

1. Tab to the menu. Press enter to open it.
2. The first menu item is not focused. 

### Ark UI Version

3.6.2

### Framework

- [X] React
- [X] Solid
- [ ] Vue

### Browser

Firefox

### Additional Information

Might actually be a bug in zag that's only reproducible when using `lazyMount`. However, since `lazyMount` is an ark concept I decided to open it here.

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
