### ISSUE TITLE
`@zag-js/svelte` `peerDependencies` is misconfigured

### ISSUE THREAD

**Issue by Hugos68** [chakra-ui/zag#1772]
# 🐛 Bug report

The `peerDependencis` in the `@zag-js/svelte` package specifies the following:
```json
  "peerDependencies": {
    "svelte": ">=5.0.0"
  },
```

This is not correct as Svelte 5 is not out yet.

I know the `svelte` package is technically not officially public but so far it's been working very well.

## 💥 Steps to reproduce

1. Go to [the package.json of `@zag-js/svelte`](https://github.com/chakra-ui/zag/blob/main/packages/frameworks/svelte/package.json)
2. Go down to the [`peerDependencies`](https://github.com/chakra-ui/zag/blob/main/packages/frameworks/svelte/package.json#L38C1-L40C5) field
3. View the wrongly configured `svelte` version

## 💻 Link to reproduction

Not Relevant

## 🧐 Expected behavior

It should be configured correctly until Svelte releases 5.0.0

## 🧭 Possible Solution

Since Svelte 5 is currently still in RC it uses `next` versioning, so the `peerDependencies` should actually be:
```json
  "peerDependencies": {
    "svelte": "^5.0.0-next.1"
  },
```

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      | 0.65.0 |
| Browser          | n/a |
| Operating System | n/a |

## 📝 Additional information

It causes npm warnings:
![image](https://github.com/user-attachments/assets/419bb373-3d11-4d48-b2e3-2e23f0ef3661)

**Comment by segunadebayo** [comment]
Good catch @Hugos68.

Feel free to open a PR. Will file a release once it's merged.

**Comment by Hugos68** [comment]
Submitted a PR: #1785
