### ISSUE TITLE
Tree View: programmatic selection does not account for singular selection

### ISSUE THREAD

**Issue by Jonas-C** [chakra-ui/zag#1787]
# 🐛 Bug report

Selecting an item programmatically with the `select` function does not account for singular selection. It always retains the already selected value.

## 💻 Link to reproduction

No reproduction, but see https://github.com/chakra-ui/zag/blob/b697c965064f6dfec7797c673f67b3348d595eea/packages/machines/tree-view/src/tree-view.connect.ts#L69

## 🧐 Expected behavior

You shouldn't be able to add more than one item when selection mode is singular.

## 🧭 Possible Solution

The obvious solution is to to check `state.context.selectionMode` before deciding whether to append or replace the already selected value. This could either be done in `connect` or `machine`, depending on where you feel it fits the best. If we choose the latter, we'd have to simply choose the last value in the set.

I'm not sure what kind of repercussions this might have. If the above solution sounds alright to you I'll submit a PR.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      | 0.65.1           |
| Browser          |  Firefox           |
| Operating System | MacOS           |

**Comment by segunadebayo** [comment]
Feel free to open a PR @Jonas-C.

For single selection mode, let's warn and choose the last value in the set.

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
