### ISSUE TITLE
Allow special characters on Pin Input

### ISSUE THREAD

**Issue by damienroche** [chakra-ui/zag#179]
# 🚀 Feature request

When using Pin Input component in numeric, I would like to allow user to paste specials characters (like "-")

## 🧱 Problem Statement / Justification

I've received the following email :

<img width="587" alt="Capture d’écran 2022-06-30 à 14 10 22" src="https://user-images.githubusercontent.com/1529058/176673993-de13811f-edb5-4d5c-bd71-2304485a4fdd.png">

When i copy paste `063-569` my code input component doesn't work because of the `-` character.

## ✅ Proposed solution or API

```ts
// pin-input.types.ts

type PublicContext = DirectionProperty & {
   ...
   whiteList: string
}
```

```ts
// pin-input.machine.ts

export function machine(ctx: UserDefinedContext = {}) {
  return createMachine<MachineContext, MachineState>({
    ...,
    context: {
      whiteList: ''
     }
  })
})

function isValidType(value: string, type: MachineContext["type"], whiteList: MachineContext["whiteList"]) {
  if (!type) return true
  const filteredValue = [...value].filter(char => !whiteList.includes(char)).join()
  return !!REGEX[type]?.test(filteredValue)
}
```

and use it like this :
```ts
useMachine(pinInput.machine({ whiteList: '-' }))
```

## ↩️ Alternatives

There is no alternative, because alphanumeric doesn't allow special characters.

**Comment by segunadebayo** [comment]
Thanks for requesting this. After much thought, we've decided to provide a `pattern` property in the machine's context to help achieve this.

See: https://github.com/chakra-ui/zag/blob/main/.changeset/nice-buses-provide.md

It'll be made available in the next release.
