### ISSUE TITLE
File Upload doesn't set proper aria-invalid state

### ISSUE THREAD

**Issue by Fazla-GroM** [chakra-ui/zag#1819]
### Description

When using `accept` property, `aria-invalid` on Dropzone doesn't change to `true` when dropping a file.

Example: 
Let's say  we set `accept="image/*"`. When dragging and dropping an invalid file format `onFileReject` will be triggered properly but `aria-invalid` will stay `false`.

### Link to Reproduction (or Detailed Explanation)

[repro link](https://codesandbox.io/p/sandbox/friendly-knuth-2qrjf4)

### Steps to Reproduce

1. Go to repro
2. Try uploading let's say json file via drag and drop
3. Observe how aria-invalid didn't change on Dropzone

### Ark UI Version

3.9.0

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

Chrome

**Comment by segunadebayo** [comment]
I recommend overriding the `aria-invalid` state in your code based on the `rejectedFiles`.

I'll remove the `aria-invalid` prop in favor of an explicit `invalid` prop which can be controlled by a form or state.

**Comment by segunadebayo** [comment]
Done.
