### ISSUE TITLE
`persistentElements` on dismissable doesn't work as expected when the elements are appended and removed multiple times

### ISSUE THREAD

**Issue by tsukkee** [chakra-ui/zag#1840]
# 🐛 Bug report

In case that I use 3rd party libraries which use `Teleport` to show some popover or dialog like components with Zag.js Dialog, Popover, or other components which use dismissable, I need to set up `persistentElements` to tell Zag.js to which DOM elements should be ignored.

Here, the 3rd party's one can show and hide the popover like elements multiple times but Zag.js assigns `pointer-events: auto` to elements indicated by `persistentElements` only when Zag.js's Dialog or Popover is just shown. Then, after second time, persisted elements does not have `pointer-events: auto` so that users can not interact with them.

## 💥 Steps to reproduce

Here are the steps to reproduce on my CodeSandbox.

1. Click 'Open Dialog' to show a dialog (white background), which is based on Zag.js's one
3. Click 'toggle' to show a popover (yellow background), which is NOT based on Zag.js's one
4. Click 'click me' on the popover
5. You can see an alert dialog as expected
6. Click 'OK' on the alert dialog
7. Click 'toggle' twice to hide and show again the yellow popover 
8. Click 'click me again'
9. The dialog and the popover will close, which is unexpected behavior

https://github.com/user-attachments/assets/86c7ed3f-e130-434b-a484-ce5250a71c26

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/p/devbox/433pp8

## 🧐 Expected behavior

`persistentElements` works also when the elements are appended and removed multiple times.

## 🧭 Possible Solution

Now, Zag.js assigns `pointer-events: auto` by using `waitForElements` and this might cause unexpected behavior described above. 
https://github.com/chakra-ui/zag/blob/4ff0f8e94a9b254b08a7904e930b573fc74b075f/packages/utilities/dismissable/src/pointer-event-outside.ts#L16-L32

One possible solution is using `MutationObserver` (I found `observeChildren` utility method in dom-query) to watch newly appended elements and check whether those ones include `persistentElements`.

Or, current work around is just adding `pointer-events: auto !important` to the specific elements in the 3rd party's components directly.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |  0.66.1 |
| Browser          |  Chrome 128  |
| Operating System |  macOS 14.6.1 |

**Comment by segunadebayo** [comment]
Thanks for this issue and for opening a PR.

Observing the body mutations is quite an expensive operation that would affect large DOM trees. Here's what I recommend instead:

- In the index.html, create a dedicated portal target for these Teleport items
- Use the portal target as the persistentElement selector instead.

Here's what I tried

Create a dedicated, persistent container
![CleanShot 2024-09-19 at 20 13 26@2x](https://github.com/user-attachments/assets/e612fca4-da13-4111-a6bb-e77a269b43c1)

Next, Update the persistentElements
![CleanShot 2024-09-19 at 20 14 01@2x](https://github.com/user-attachments/assets/97a6f6b1-fe30-41c3-aca3-14886de67476)

Next, Update the persistentElements
![CleanShot 2024-09-19 at 20 14 24@2x](https://github.com/user-attachments/assets/d6dad9b6-4a74-4c05-9353-d91ef79f1d9a)


Here's the CodeSandbox
https://codesandbox.io/p/devbox/433pp8

> BONUS: If you're worried about DOM hierarchy, create a dedicated container for your portals in the HTML file and point all Teleports to that portal container. It's faster and more performance

**Comment by tsukkee** [comment]
@segunadebayo Thank you very much for your review & advice!

The 3rd party library that I'm using doesn't allow to customize the portal container, which means `to="body"`is hard-coded unfortunately 😢 
So, I'll try to make PR for that 3rd party library in order that its portal target is to be customizable.
