### ISSUE TITLE
[vue] Keyboard input is not working for DatePicker

### ISSUE THREAD

**Issue by Andrewnt219** [chakra-ui/zag#1846]
### Description

In vue, users cannot enter dates using numeric values from keyboard. For example, entering "12/31/2024" on input, and the selected date should be "12/31/2024"

### Link to Reproduction (or Detailed Explanation)

https://stackblitz.com/edit/vitejs-vite-gga1tj?file=src%2FApp.vue

### Steps to Reproduce

1. Go to date picker example (Vue) https://ark-ui.com/react/docs/components/date-picker
2. Copy the example
3. Type "12/31/2024" to the input

Expect: input to display "12/31/2024" and the date picker to select the same date
Actual: cannot type anything to the input

### Ark UI Version

3.6.0

### Framework

- [ ] React
- [ ] Solid
- [X] Vue

### Browser

Chrome v126

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update in Zag and Ark shortly.

If the issue persists after upgrading, I'll re-open it.
