### ISSUE TITLE
Datepicker min changed dynamically error

### ISSUE THREAD

**Issue by eduardocque** [chakra-ui/zag#1847]
### Description

seems to be that when i change `min` attribute in runtime, the datepicker just crash
![image](https://github.com/user-attachments/assets/af866450-caee-4318-b120-e1ef9a856c2e)
![image](https://github.com/user-attachments/assets/88cfd1e9-73dd-494f-b2a1-5b5d0fbc9714)

### Link to Reproduction (or Detailed Explanation)

not provided

### Steps to Reproduce

add a datepicker with a min date, and in runtime change it, and should crash, tested with days in september 2024

### Ark UI Version

3.10.0

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update for Zag.js and Ark shortly.

If the issue persists after upgrading, I'll re-open it.
