### ISSUE TITLE
Change max prop of Slider after creation

### ISSUE THREAD

**Issue by Trevald** [chakra-ui/zag#1867]
# 🚀 Feature request
Add possibility to change max value of slider after it has been created

## 🧱 Problem Statement / Justification
I'm using the slider to filter a list of items based on a numerical property. As these items are loading async the maximum possible value can increase as more items are loaded. The slider would then need to adapt it's maximum value to the highest value that any item have.

**Comment by segunadebayo** [comment]
Using the controlled context, you can achieve this.

Here's an example
https://stackblitz.com/edit/xfpdhm?file=src%2FApp.tsx,src%2FSlider.tsx&showSidebar=0

Notice these things:
- The use of `slider.splitProps` to extract out the props that the slider machine needs
- Adding the controlled `{ context: sliderProps }`

**Comment by Trevald** [comment]
Thanks! Took some time to figure out how to replicate it in Vue but in the end all what was needed was to have  an object with the sliderProps wrapped in a computed value. Then set that to the context prop:

`const sliderProps = computed(() => {
    return {
        max: props.max
    };
});`
