### ISSUE TITLE
FileUpload directory prop not work

### ISSUE THREAD

**Issue by alckordev** [chakra-ui/zag#1871]
### Description

The directory prop does not work as expected.

### Link to Reproduction (or Detailed Explanation)

https://codesandbox.io/p/sandbox/vh9zkr

### Steps to Reproduce

1. Click on Choose file(s)

### Ark UI Version

3.11.1

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

Google Chrome

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

In the meantime, please pass the `webkitdirectory ` prop to the `FileUpload.HiddenInput`

If the issue persists after upgrading, I'll re-open it.
