### ISSUE TITLE
Checkbox does not set `data-focus` on click

### ISSUE THREAD

**Issue by marviobezerra** [chakra-ui/zag#1873]
### Description

When I click on a checkbox, I expect it to set the data-attribute `data-focus` but it does not happen.

> Note that pressing tab sets the focus properly.

### Link to Reproduction (or Detailed Explanation)

https://codesandbox.io/p/devbox/frosty-glitter-qmnnpp

### Steps to Reproduce

Click on the checkbox and inspect the element. There is no focus attribute.

### Ark UI Version

3.12.1

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

All

**Comment by segunadebayo** [comment]
I just pushed a fix for this in Zag.js. We'll release an update and propagate it to Ark UI shortly.

If the issue persists after upgrading, I'll re-open it.
