### ISSUE TITLE
Deleting a tag with `delete` breaks focus handling

### ISSUE THREAD

**Issue by Jonas-C** [chakra-ui/zag#1911]
# 🐛 Bug report

When deleting a tag with the `delete` key, the remaining tags are no longer focusable with arrow keys. This resolves itself by pressing the down key.

## 💥 Steps to reproduce

1. Focus the input. Press left and then delete.
2. Focus is not moved to next tag. Left and right arrow keys no longer work.

## 💻 Link to reproduction
https://zagjs.com/components/react/tags-input

## 🧐 Expected behavior

Delete and backspace should have somewhat similar behavior w.r.t focus handling.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      | 0.73.1           |
| Browser          | Firefox           |
| Operating System |  MacOS          |

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
