### ISSUE TITLE
[NumberInput] Add option to disable long press action

### ISSUE THREAD

**Issue by gperdomor** [chakra-ui/zag#1916]
# 🚀 Feature request

Add option to disable long press/click on NumberInput 

## 🧱 Problem Statement / Justification

There are some cases where we need to increase quantities one by one, maybe to do some validations or fetch some data from server on every value change

## ✅ Proposed solution or API

Add a new config option to disable long press and force the user to click the up/down buttons multiple times

## ↩️ Alternatives
N/A

## 📝 Additional Information
N/A

**Comment by segunadebayo** [comment]
Please set `spinOnPress: false` for this. Will update the docs to reflect this

**Comment by gperdomor** [comment]
:o thank you, I was not aware of that option... Thanks for the quick response ❤️
