### ISSUE TITLE
Popover Does Not Apply [data-focus-visible] to First Element

### ISSUE THREAD

**Issue by elson-currentcorp** [chakra-ui/zag#1950]
# 🐛 Bug report

When I open a popover with interactive elements inside, I expect to be able to tab through all the elements and have the outline defined by data-focus-visible show up on each tabbed element. 

Currently, the popover always skips applying [data-focus-visible] to the first element (but still focuses it).

## 💥 Steps to reproduce

1. Visit reproduction
2. Open popover
3. Start pressing tab
4. Notice that all the child elements have the focus-visible outline except for the first element.

## 💻 Link to reproduction

https://stackblitz.com/edit/r2vdha?file=src%2FApp.tsx

## 🧐 Expected behavior

I expect the first element to have the focus-visible outline when tabbing through all the elements.

## 🧭 Possible Solution

Since this bug does not apply [data-focus-visible] to the first element, the alternatives are to either use [data-focus] or the native focus-visible css selector.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |   0.74.1        |
| Browser          |      Chrome      |
| Operating System |        Windows    |

**Comment by segunadebayo** [comment]
We didn’t design the popover to apply this attribute, but I see where you’re going. We’ll consider this in the future.

Please use the native css focus visible instead.
