### ISSUE TITLE
Hover Card: Unable to preventDefault inside passive event listener

### ISSUE THREAD

**Issue by akkie** [chakra-ui/zag#1951]
# 🐛 Bug report

When using the hover card component on a mobile device, it throws an error when tapping on the trigger element.

The thrown error is:

```
Unable to preventDefault inside passive event listener 
  | onTouchStart | @ | @zag-js_hover-card.js?v=91a36e88:95
  | handle_event_propagation | @ | chunk-LHE3EEFJ.js?v=91a36e88:128
```

## 💥 Steps to reproduce

1. Open developer console
2. Switch to mobile mode
3. Go to 'https://zagjs.com/components/react/hover-card'
4. Click on 'the trigger element'
5. See error

## 💻 Link to reproduction

https://zagjs.com/components/react/hover-card

## 🧐 Expected behavior

No error should be thrown

## 🧭 Possible Solution

Either the card opens on touch event or now error should be thrown.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      | 0.75.0     |
| Browser          | Arc        |
| Operating System | MacOS      |

## 📝 Additional information

<img width="1397" alt="image" src="https://github.com/user-attachments/assets/5b431e4c-1ee7-46ed-9e7e-6396b8326485">

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
