### ISSUE TITLE
[TagInput] useTagsInput() addValue(item) not working

### ISSUE THREAD

**Issue by renchris** [chakra-ui/zag#1953]
# 🐛 Bug report

When I pass the const tagsInput = useTagsInput() hook to the TagInput.RootProvider and use the hook to add items out side the TagsInput component with tagsInput.addValue(item) it does not add the value to the tag input field box

The tagsInput.addValue(item) function doesn't seem to work even in the most basic example even though other functions such as tagsInput.setValue(item) do

## 💥 Steps to reproduce

Create a basic TagInput component with a RootProvider and the useTagInput() hook
```
import { TagsInput, useTagsInput } from '@ark-ui/react/tags-input'

export const RootProvider = () => {
  const tagsInput = useTagsInput()

  return (
    <>
      <button onClick={() => tagsInput.focus()}>Focus</button>

      <TagsInput.RootProvider value={tagsInput}>
        <TagsInput.Context>
          {(tagsInput) => (
            <>
              <TagsInput.Label>Frameworks</TagsInput.Label>
              <TagsInput.Control>
                {tagsInput.value.map((value, index) => (
                  <TagsInput.Item key={index} index={index} value={value}>
                    <TagsInput.ItemPreview>
                      <TagsInput.ItemText>{value}</TagsInput.ItemText>
                      <TagsInput.ItemDeleteTrigger>Delete</TagsInput.ItemDeleteTrigger>
                    </TagsInput.ItemPreview>
                    <TagsInput.ItemInput />
                  </TagsInput.Item>
                ))}
              </TagsInput.Control>
              <TagsInput.Input placeholder="Add Framework" />
              <TagsInput.ClearTrigger>Clear all</TagsInput.ClearTrigger>
            </>
          )}
        </TagsInput.Context>
        <TagsInput.HiddenInput />
      </TagsInput.RootProvider>
    </>
  )
}
```

Try to invoke the tagsInput.addValue(item) function and does not do anything despite other functions such as tagsInput.setValue(item) working

## 💻 Link to reproduction

CodeSandbox reproduction: https://your-codesandbox-link-goes-here.io

## 🧐 Expected behavior

I expect the value to be added

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |0.74.2 (Ark 4.1.2)|
| Browser          |Chrome Version 129.0.6668.101 (Official Build) (arm64)|
| Operating System |MacOS Sonoma 14.6.1|

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
