### ISSUE TITLE
[TagInput] onInputValueChange invoked on onValueChange

### ISSUE THREAD

**Issue by renchris** [chakra-ui/zag#1954]
# 🐛 Bug report

Need a way to invoke the onInputValueChange tagsInput hook not be invoked when the the onValueChange tagsInput hook is invoked

 Ie. When we submit a tag by input keyboard enter instead of clicking the dropdown, both of the callbacks get called and we cannot handle the dropdown filter logic properly. onInputValueChange I just want to filter based of the input text so far and onValueChange I want to filter based of off what options there are left

Even the paid example has this bug with the filtering not working properly. If you select a number of options, then delete them all, and select another option again, all of the deleted options show up along with the new selected option

```ts
  const tagInput = useTagsInput({
    onInputValueChange: handleInputChange,
    onValueChange: handleValueChange,
    validate: (details) => initialItems.includes(details.inputValue)
    && !details.value.includes(details.inputValue),
  })
```

https://www.loom.com/share/f33c9412b21f43cbbefb0ab951ac8b21

## 💻 Link to reproduction

CodeSandbox reproduction: https://your-codesandbox-link-goes-here.io

## 🧐 Expected behavior

I expect to be able to properly filter the dropdown items upon select as well as input type

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      | 0.74.2 (Ark 4.1.2) |
| Browser          |Chrome Version 129.0.6668.101 (Official Build) (arm64)|
| Operating System |MacOS Sonoma 14.6.1|

**Comment by segunadebayo** [comment]
I'd recommend moving the `onInputValueChange ` logic to the `TagsInput.Input` directly  as `onChange`

In the future, we'll consider exposing some `actionMeta` information to all events.

> We'll update Ark Plus shortly
