### ISSUE TITLE
Overlapping Toast Placement Broken When Calling toast.create()

### ISSUE THREAD

**Issue by elson-currentcorp** [chakra-ui/zag#1965]
# 🐛 Bug report

If I call `toast.create()` with placement as `bottom` or placement as `undefined`, the toast is overlapped and positioned correctly. The moment I call the function with a different value, etc. `bottom-start`, the toast no longer overlaps correctly.

## 💥 Steps to reproduce

1. Go to App.tsx in reproduction link.
2. Try commenting/uncommenting lines 12-14.
3. See that the overlapping placement is broken for any placement value other than `undefined` or `bottom`

## 💻 Link to reproduction

https://stackblitz.com/edit/zndwtj?file=src%2FToast.tsx,src%2Fmain.tsx,src%2FApp.tsx&showSidebar=0

## 🧐 Expected behavior

Toast should overlap correctly no matter what placement value is given to `toast.create()`.

## 🧭 Possible Solution

I noticed that the initial placement declared in `ToastProvider` has to match the placement declared in `toast.create()`  for the toast to position correctly, but this does not match the documentation at https://zagjs.com/components/react/toast, and defeats the purpose of exposing the placement option in `toast.create()`, which is why I think this is a bug.

```
export function ToastProvider({ children }: { children: React.ReactNode }) {
  const [state, send] = useMachine(
    toast.group.machine({ id: '1', overlap: true, placement: 'bottom-start' })
  );

  const api = toast.group.connect(state, send, normalizeProps);

  return (
    <ToastContext.Provider value={api}>
      {api.getPlacements().map((placement) => (
        <div key={placement} {...api.getGroupProps({ placement })}>
          {api.getToastsByPlacement(placement).map((toast) => (
            <Toast key={toast.id} actor={toast} />
          ))}
        </div>
      ))}
      {children}
    </ToastContext.Provider>
  );
}
```

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |      0.75.0      |
| Browser          |     Chrome       |
| Operating System |         Windows   |

## 📝 Additional information

Inspecting element shows that the bugged toasts all have index = -1 even if there are multiple of them.

**Comment by segunadebayo** [comment]
This isn't a bug per se. The docs need some rework, esp. for the overlap feature.

When using overlap, the toast's placement must match the `placement` of the toast group (which is bottom by default).

I might consider removing the placement option for `toast.create` methods in the future.
