### ISSUE TITLE
[TagInput] onInputValueChange does not reference updated values

### ISSUE THREAD

**Issue by renchris** [chakra-ui/zag#1967]
# 🐛 Bug report

Any value used in the `onInputValueChange` function is not up to date despite being called after variable value change or update.

## 💥 Steps to reproduce

Update a value and see that that current value is not being used in the ``onInputValueChange` function

```ts
export const ShareCombobox = ({
  shareList,
}: {
  shareList: Share[],
}) => {
  console.log('==COMPONENT==')
  console.log(shareList) //shows here
  console.log('==')
  const handleInputChange = (details: Combobox.InputValueChangeDetails) => {
    console.log('==HANDLE INPUT CHANGE==')
    console.log(shareList) //SHOWS EMPTY LIST HERE
    console.log('==')
  }
  const handleValueChange = (details: Combobox.ValueChangeDetails) => {
    console.log('==HANDLE VALUE CHANGE==')
    console.log(shareList) //shows here
    console.log('==')
  }
//...

  const tagInput = useTagsInput({
    onValueChange: handleValueChange,
    onInputValueChange: handleInputChange,
  })
```

## 💻 Link to reproduction

CodeSandbox reproduction: https://your-codesandbox-link-goes-here.io

## 🧐 Expected behavior

I expect any variable value used in the `onInputValueChange` function to be the current value

## 🧭 Possible Solution

Update the `onInputValueChange` method in the Zag source code to update upon the function call

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |0.75.0|
| Browser          |Chrome|
| Operating System |MacOS|

**Comment by segunadebayo** [comment]
I assume this is happening because the `shareList` is fetched and updated when the component mounts. This is a common stale closure problem.

For this scenario, I recommend storing the share list in a "live ref" and reading from that live ref in your code.

![CleanShot 2024-10-26 at 15 03 49@2x](https://github.com/user-attachments/assets/27489027-7208-4467-9e56-cb40a4adba89)
