### ISSUE TITLE
[TagInput] data-highlighted is passed to the next tag after deletion using the “delete” button on keyboard

### ISSUE THREAD

**Issue by oowliq** [chakra-ui/zag#1999]
# 🐛 Bug report
If you select not the last tag with the mouse and press delete, the tag is deleted, but the data-highlighted is passed to the next tag and it seems that it can also be deleted with delete, but it won't work in this case.

## 💥 Steps to reproduce

1. Go to https://stackblitz.com/edit/qa7x1z?file=src%2FApp.tsx,src%2FTagsInput.tsx&showSidebar=0
2. Click on text input
3. Press "LeftArrow" button 2 times
4. Press "Delete" button on keyboard
5. See error

## 💻 Link to reproduction

Reproduction: https://stackblitz.com/edit/qa7x1z?file=src%2FApp.tsx,src%2FTagsInput.tsx&showSidebar=0

## 🧐 Expected behavior

The highlighting should not go to the next tag when deleting to the “Delete” key

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |  0.77.0          |
| Browser          |  Edge 130.0.2849.56 (Official build) (64-bit)  |
| Operating System |  Windows 11 24H2          |

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
