### ISSUE TITLE
Switch onCheckedChange Handler Not Triggering After Closing Dialog

### ISSUE THREAD

**Issue by elson-currentcorp** [chakra-ui/zag#2057]
# 🐛 Bug report

I have a controlled `Switch` and controlled `Dialog`. Clicking the `Switch` prompts up a warning `Dialog`. If the user accepts the warning, the `Switch` turns on. If the user declines the warning, the `Switch` remains off.

The bug is that if the user declines the warning and closes the `Dialog`, the `Switch` needs to be clicked twice for the change handler to retrigger and open the Dialog again.

## 💥 Steps to reproduce

1. Go to reproduction
2. Click `Switch`
3. Click cancel button on `Dialog`
4. Click `Switch` again (nothing will happen, this is the bug)
5. Click `Switch` again (`Dialog` finally opens)

## 💻 Link to reproduction

https://stackblitz.com/edit/h4fpxy?file=src%2FApp.tsx

## 🧐 Expected behavior

The `Switch` should invoke the `onCheckedChange` handler on click after closing the `Dialog`, but it isn't doing that.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |   0.77.1         |
| Browser          |     Chrome       |
| Operating System |      Windows      |

## 📝 Additional information

If I comment out the `Dialog` component completely, i can click the `Switch` as many times as I want, and the correct controlled state is reported back through `onCheckedChange` handler every time.

**Comment by segunadebayo** [comment]
I've looked at the code. You should probably wait for the next tick to synchronize the state.

```tsx
 const onCheckedChange = useCallback(({ checked }: { checked: boolean }) => {
    queueMicrotask(() => {
      if (checked) {
        setIsConfirmDialogOpen(true);
      } else {
        setIsChecked(false);
      }
    });
  }, []);
```

https://stackblitz.com/edit/h4fpxy-mrlo2h?file=src%2FApp.tsx
