### ISSUE TITLE
`@zag-js/angle-slider` 404 can't download from NPM

### ISSUE THREAD

**Issue by babakfp** [chakra-ui/zag#2059]
```
 pnpm add -D "@zag-js/angle-slider"
 ERR_PNPM_FETCH_404  GET https://registry.npmjs.org/@zag-js%2Fangle-slider: Not Found - 404
```

https://zagjs.com/components/react/angle-slider

Is this waiting for https://github.com/chakra-ui/zag/pull/2035?

These too? Not documented.

floating-panel
time-picker

**Comment by anubra266** [comment]
@babakfp It's not released yet, I've hidden the docs for now

**Comment by anubra266** [comment]
Released now
