### ISSUE TITLE
[SignaturePad] getDataUrl seems not working properly on Firefox

### ISSUE THREAD

**Issue by hyanmandian** [chakra-ui/zag#2080]
# 🐛 Bug report

I was testing `getDataUrl` and on Firefox it seems not working as expected. I think it is because of `scale` transform logic we have before we generate the image.

This is the expected output, as you can see it correctly render the corners

![Screenshot 2024-12-04 at 12 41 36](https://github.com/user-attachments/assets/81c506c1-fbe8-4d16-ac8a-cc39f7774454)

This is the output on Firefox. It is not the same image but you can see it only renders the half part of it

![image](https://github.com/user-attachments/assets/2df43dfe-b163-46b6-b558-534a9416b778)

I did a patch in my app to remove the `win.devicePixelRatio` and always uses `1` I also changed `context!.drawImage(image, 0, 0)` to also includes width and height like this `context!.drawImage(image, 0, 0, canvas.width, canvas.height)`

**Comment by segunadebayo** [comment]
That's an interesting finding @hyanmandian. Feel free to open a PR for this

**Comment by hyanmandian** [comment]
I’m going to do it right now!

**Comment by hyanmandian** [comment]
There you go @segunadebayo https://github.com/chakra-ui/zag/pull/2081

**Comment by segunadebayo** [comment]
I looked into this more and figured it doesn't work because we don't have an explicit view box set.

I've pushed a fix for this.
