### ISSUE TITLE
[number-input]: input value not updating correctly on first interaction

### ISSUE THREAD

**Issue by acd02** [chakra-ui/zag#2083]
# 🐛 Bug report

When using the number input machine, the input value does not update as expected after pressing the backspace key during the first interaction.

## 💥 Steps to reproduce

1. the initial value is `""`, step value is `1`
2. increment the value using the `getIncrementTriggerProps()`
3. the input value will be `1`
4. hit the backspace key
  a. the input is now empty
  b. we expect `api.value` to be empty as well, but it's still set to `1`
  c. and if we check the devtools, we can also see that input html element still holds a value of `1`

## 💻 Link to reproduction

Stacblitz reproduction: https://stackblitz.com/edit/stackblitz-starters-zmtev1?file=pagesContent%2Findex.tsx

## 🧐 Expected behavior

Following the steps described above, I expected `api.value` to be set to `0` after step 4

## 🧭 Possible Solution

I cloned the repo and tried to play with the `number-input` machine, but I could not figure out the cause of the bug.
However, inside `packages/machines/number-input/src/number-input.connect.ts`, in the `getInputProps` function, the `onChange` callback is not called when reaching the step 4.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |   0.78         |
| Browser          |   brave         |
| Operating System |    macos        |

**Comment by segunadebayo** [comment]
This was surprising to see as well. It must be something with React's onChange handler not getting called.

Switched it to `onInput` since it's more resilient across frameworks. I will cut a new release shortly.
