### ISSUE TITLE
Dialog unexpectedly closes on a touch device

### ISSUE THREAD

**Issue by dannylin108** [chakra-ui/zag#2084]
### Description

see this old issue which was closed, not fixed actually (I was able to reproduce it for all releases from 3.9 to 4.2).

https://github.com/chakra-ui/ark/issues/2816  

### Link to Reproduction (or Detailed Explanation)

https://stackblitz.com/~/github.com/dannylin108/parkui-bug-report

### Steps to Reproduce

1. Open the page on a touch device (Chrome emulation also works)
2. Open the drawer
3. Choose a date in the date picker
4. The drawer unexpectedly closes, but should remain open showing the chosen date.

### Ark UI Version

4.2.0

### Framework

- [ ] React
- [X] Solid
- [ ] Vue

**Comment by segunadebayo** [comment]
This was fixed in a recent commit. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.

https://github.com/user-attachments/assets/7465e355-3fca-42c4-9573-57b2f498c969
