### ISSUE TITLE
Hover from the React testing library in the Tooltip component is not working

### ISSUE THREAD

**Issue by elbrante** [chakra-ui/zag#2134]
### Discussed in https://github.com/chakra-ui/zag/discussions/2133

<div type='discussions-op-text'>

<sup>Originally posted by **elbrante** December 23, 2024</sup>
Hello everyone. I'm trying to write a test using the React Testing Library to view a hint on hover. When using hover from UserEvent zag.js does not change the state of the Tooltip in any way, that is, the tooltip does not open. I also tried to use fireEvent using the MouseEvent('mouseover') event and used fireEvent.focus(), but the situation persists. What to do?</div>

**Comment by segunadebayo** [comment]
Let's keep this as a discussion. Will have a look
