### ISSUE TITLE
Radio group didn't work as expected

### ISSUE THREAD

**Issue by bluzky** [chakra-ui/zag#2135]
# 🐛 Bug report

## 💥 Steps to reproduce

I created this issue because it hasn't solved in #2103 
I follow the example on the website and radio group didn't work as described.

## 💻 Link to reproduction

Even in the example by @segunadebayo it doesn' work
https://stackblitz.com/edit/sb1-5ezeyc1m?file=src%2Fcomponents%2FRadioGroup%2FRadioGroup.tsx

## 🧐 Expected behavior

The radio button get checked when click on the control or label

## 🧭 Possible Solution

I found that after adding addition context, it worked.

![image](https://github.com/user-attachments/assets/bab6f9d4-db76-4644-863e-b39287fa5d0c)

Thanks

**Comment by segunadebayo** [comment]
Hey! It works as expected. The only thing missing are the styles for `data-state=checked` not `data-checked`

![CleanShot 2024-12-23 at 22 18 51@2x](https://github.com/user-attachments/assets/10ce440b-1971-4af6-8efb-37d7a03e671d)


```css
[data-state='checked'] {
  display: block;
  background: blue;
  color: white;
}
```
