### ISSUE TITLE
Slider cannot be dynamically disabled

### ISSUE THREAD

**Issue by tyko0x** [chakra-ui/zag#230]
# 🐛 Bug report

Dynamically changing the `disabled` option of the slider machine does not affect its enabled/disabled state. It seems like the only way to change it is to remount/rekey the slider with `disabled` set to the desired value. There are situations where this is less than ideal and could cause other bugs.

## 💥 Steps to reproduce

1. Set up slider per the docs
2. Set the `disabled` option of the slider machine to a boolean piece of state
3. Change the state from `false` to `true` or vice versa after the slider has mounted. Notice that the slider's enabled status is not affected

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/billowing-forest-21bvc4?file=/src/App.tsx

## 🧐 Expected behavior

If `disabled` is dynamically changed to `true`, I expect the slider to be disabled and no longer respond to user events

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |  0.1.13 react / 0.1.11 slider          |
| Browser          |   latest Chrome          |
| Operating System |     Mac OS Monterey       |

**Comment by anubra266** [comment]
@tyko0x Machines cannot be mutated from the component, all state changes have to happen in the machine, the way to solve this is to expose a `setDisabled` method in the component API, so you an do `api.setDisabled(false)`

**Comment by anubra266** [comment]
A workaround before that is fixed is to use a fieldset, because the slider machine can track the disabled state of fieldsets.
```tsx
export function DynamicallyDisabledSlider() {
  const [checked, setChecked] = useState(false);

  const [state, send] = useMachine(
    slider.machine({ id: "dynamically-disabled-slider"})
  );

  const handleChange = () => {
    setChecked(!checked)
  };

  const api = slider.connect(state, send, normalizeProps);

  return (
    <>
      <label>
        <input type="checkbox" checked={checked} onChange={handleChange} />
        Is slider disabled
      </label>
      <fieldset disabled={checked} {...api.rootProps}>
        <div>
          <label {...api.labelProps}>Slider Label</label>
          <output {...api.outputProps}>{api.value}</output>
        </div>
        <div {...api.controlProps}>
          <div {...api.trackProps}>
            <div {...api.rangeProps} />
          </div>
          <div {...api.thumbProps}>
            <input {...api.inputProps} />
          </div>
        </div>
      </fieldset>
    </>
  );
}
```

**Comment by segunadebayo** [comment]
This most convenient way to control context values based on `props` or `state` is by using [this approach](https://zagjs.com/overview/programmatic-control#transient-updates) mentioned in the docs.

```jsx
const [state, send] = useMachine(
    slider.machine({ id: "dynamically-disabled-slider" }),
    { context: { disabled: checked } }
 )
 ```
