### ISSUE TITLE
[popover] do not manage positioning by default for popover-like machines

### ISSUE THREAD

**Issue by izznatsir** [chakra-ui/zag#266]
# 🚀 Feature request

Disable managed-positioning by default for popover-like machines.

## 🧱 Problem Statement / Justification

Currently, popover-like machines are auto positioned by default via the style attribute. But, there is no way to disable it.

This make it impossible to customize the positioning using CSS classes.

For example, I want to position the popover differently based on viewport width. Using Tailwind CSS, I could simply add device width variant classes to change the positioning.

Zag is intended to be low-level for easy integration. This positioning complicate positioning customization using CSS, therefore complicate integration in some cases.

## ✅ Proposed solution or API

Make positioning off by default. So, if users do not provide positioning context configuration or undefined, disable the auto-positioning.

This will be a breaking change.

```javascript
// disabled
const [state, send] = useMachine(menu.machine({ id: "menu", "aria-label": "Menu" }))

// enabled
const [state, send] = useMachine(menu.machine({ id: "menu", "aria-label": "Menu", positioning: { placement: 'bottom', gutter: 8 } }))
```

## ↩️ Alternatives

I could modify the menu machine by copy paste it from the source.

Or, I could use Headless UI that fully delegate positioning to users. [Headless UI Popover](https://headlessui.com/react/popover)

But, I want to use zag because the logic is easier to understand.

**Comment by segunadebayo** [comment]
When you don't render the positioner, the positioning logic is disabled by default.

```diff
    <div>
      <button {...api.triggerProps}>Click me</button>
-      <div {...api.positionerProps}>
        <div {...api.contentProps}>
          <div {...api.titleProps}>Presenters</div>
          <div {...api.descriptionProps}>Description</div>
          <button>Action Button</button>
          <button {...api.closeButtonProps}>X</button>
        </div>
-     </div>
    </div>
```

**Comment by izznatsir** [comment]
Ahh, I see! Thanks!
