### ISSUE TITLE
[editable] on mobile device virtual keyboard is not always triggered

### ISSUE THREAD

**Issue by pawelblaszczyk5** [chakra-ui/zag#292]
# 🐛 Bug report

When I'm triggering editable the virtual keyboard is not always opened. I found out that when I click anywhere on the page after cancel/save it won't open virtual keyboard next time. 

## 💥 Steps to reproduce

1. Go to docs [example of editable](https://zagjs.com/components/react/editable) 
2. Click on the edit button/placeholder, virtual keyboard won't open this time
3. Click on the cancel/save button
4. Without clicking anything click the edit button/placeholder again, virtual keyboard will open this time

## 💻 Link to reproduction

[I was testing in docs example](https://zagjs.com/components/react/editable)

## 🧐 Expected behavior

The behaviour should be identical whether I click somewhere else or not. I suspect the virtual keyboard should open on both cases

## 🧭 Possible Solution

I have no clue unfortunately

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |      0.1.14 (at the time of writing)      |
| Browser          |      Chrome 104.0.5112.97      |
| Operating System |     Android       |

## 📝 Additional information

Reproduction video (I tried to show clicking somewhere else with clicking the settings checkbox):

https://user-images.githubusercontent.com/54995479/188317559-d7e81584-2ad9-477a-a705-63aa041d314e.mp4

**Comment by segunadebayo** [comment]
Hi @pawelblaszczyk5. After days of debugging, this is a user-agent decision we don't control. 

When the [Virtual Keyboard API](https://www.w3.org/TR/virtual-keyboard/) is widely supported, we'll revisit this.
