### ISSUE TITLE
[toast] progress bar incorrectly reflecting time to disappear after pausing

### ISSUE THREAD

**Issue by pawelblaszczyk5** [chakra-ui/zag#295]
# 🐛 Bug report

When you pause a toast the progress bar is being reset every time. It doesn't look to be the case in reality, because sometimes toast disappear just after unpausing them.

## 💥 Steps to reproduce

1. Go to docs [example of toast](https://zagjs.com/components/react/toast#pausing-the-toasts) 
2. Open a toast
3. Wait a bit and hover it, repeat few times
4. It'll disappear just after unpausing with nearly full progress bar

## 💻 Link to reproduction

[I was testing in docs example](https://zagjs.com/components/react/toast)

## 🧐 Expected behavior

I'm not sure whether the time should reset after pausing or just paused. Progress bar should show the actual time to disappear either way

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |       0.1.14 (at the time of writing)     |
| Browser          |      Chrome 105.0.5195.52      |
| Operating System |       MacOS     |

## 📝 Additional information

Reproduction: 

https://user-images.githubusercontent.com/54995479/188319037-f761a920-dc81-4d03-9a6c-c4fcbe909cd2.mov

**Comment by segunadebayo** [comment]
Good catch @pawelblaszczyk5!

We decided to remove the progress bar from the core of the toast for now. Zag will provide the details needed to create a progress bar but not the props anymore.

We don't want to be in the business of UI and CSS within Zag.

**Comment by pawelblaszczyk5** [comment]
Thank you very much for solving those issues, you're doing awesome job with Zag ⚡
