### ISSUE TITLE
Dialog NEED onCloseButtonClick

### ISSUE THREAD

**Issue by 9j** [chakra-ui/zag#302]
# 🚀 Feature request

> Please describe your request in one or two sentences.

OnClickEvent such as onEsc(), onOutsideClick() is required for closeButton.

## 🧱 Problem Statement / Justification

> Please provide valid reason(s) why this should added to Chakra UI.
>
> If this feaure is related to a problem you've noticed. Mention it as well

I want to handle logging of clicks on machine.
I can log backdrop clicks using onOutsideClick() in Dialog, but this is not possible in closeButton.

## ✅ Proposed solution or API

> Please provide code snippets, gists, or links to the ideal design or API

add onCloseButtonClick props

```
const [state, send] = useMachine(
    dialog.machine({
      ...
      onCloseButtonClick: () => {
        sendLog(..)
      }
    }
```

## ↩️ Alternatives

> What alternative solutions have you considered before making this request?

```
const onClick = () => {
  sendLog(...)
  api.close()
}
....
<button {...api.closeButtonProps} onClick={onClick}>
  close
</button>
```

but It's not cool

## 📝 Additional Information

> What resources (links, screenshots, etc.) do you have to assist this effort?

**Comment by anubra266** [comment]
@9j You can achieve this with [mergeProps](https://zagjs.com/overview/composition#event-composition)
