### ISSUE TITLE
Maximum update depth exceeded when context value is object or array

### ISSUE THREAD

**Issue by malangcat** [chakra-ui/zag#303]
# 🐛 Bug report

```tsx
  const [state, send] = useMachine(
    rangeSlider.machine({
      id: useId(),
      name: "quantity",
      values: [10, 60]
    }),
    { context: { values: [0, 100] } }
  );
```

Runs into `Maximum update depth exceeded` error.

Not only `values` in range slider, passing any object or array to context runs into same error.

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/weathered-silence-hi2g6o

## 🧐 Expected behavior

Passing `values` into context is required when we implement controlled range slider.

## 🧭 Possible Solution

It seems like related to `useSnapshot()`, but I failed to figure out where infinite loop occurs.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |    @zag.js/react: 0.1.16        |
| Browser          |  Chrome 104.0.5112.101          |
| Operating System |    MacOS 12.3        |

**Comment by malangcat** [comment]
@anubra266 I am wrapping components like:

```tsx
<RangeSlider value={[0, 100]} onChange={...} />
```

and wrote a custom hook sending props to machine context
```tsx
export function useRangeSlider(props: RangeSliderProps) {
  const onChange = useCallback(wrapZagChange(props.onChange), [props.onChange]);
  const onChangeStart = useCallback(wrapZagChange(props.onChangeStart), [
    props.onChangeStart,
  ]);
  const onChangeEnd = useCallback(wrapZagChange(props.onChangeEnd), [
    props.onChangeEnd,
  ]);

  const [state, send] = useMachine(
    rangeSlider.machine({
      id: React.useId(),
      values: props.value ??
        props.defaultValue ?? [props.minValue ?? 0, props.maxValue ?? 100],
    }),
    {
      context: {
        orientation: props.orientation ?? "horizontal",
        "aria-label": props["aria-label"],
        "aria-labelledby": props["aria-labelledby"],
        disabled: props.isDisabled,
        step: props.step ?? 1,
        min: props.minValue ?? 0,
        max: props.maxValue ?? 100,
        onChange,
        onChangeStart,
        onChangeEnd,
        values: props.value,
      },
    },
  );
  const api = rangeSlider.connect(state, send, normalizeProps);

  return { api };
}
```

I want to avoid controlling all contexts with api, and calling `api.setValue()` for each render also runs into `Maximum update depth exceeded`.

**Comment by segunadebayo** [comment]
This has to do with referential equality in React, so you might need to useMemo or useCallback if you pass a function or object type to the context.

All that's happening internally is:

```jsx
useEffect(()=>{
  machine.setContext(context) // this will trigger a re-render
}, [context])
```

As you can expect, this will cause infinite re-renders if you pass non-primitive types.

**Comment by malangcat** [comment]
@segunadebayo I think `useMemo` does not resolve this issue. Code below still occurs `Maximum update depth exceeded` error.

```tsx
import * as slider from "@zag-js/range-slider";
import { normalizeProps, useMachine } from "@zag-js/react";
import { useId } from "react";

const values = [0, 100];

export default function App() {
  const [state, send] = useMachine(
    slider.machine({
      id: useId(),
      name: "quantity",
      values: [10, 60]
    }),
    { context: { values: values } }
  );
  return (
    <div className="App">
    </div>
  );
}
```

https://codesandbox.io/s/weathered-silence-hi2g6o

**Comment by anilanar** [comment]
@malangcat Seems not reproducible in latest version.

**Comment by malangcat** [comment]
@anilanar Seems like this issue is resolved by https://github.com/chakra-ui/zag/pull/390
