### ISSUE TITLE
combobox: popup does not flip when there's no space at the bottom

### ISSUE THREAD

**Issue by anilanar** [chakra-ui/zag#353]
See: https://popper.js.org/docs/v2/modifiers/flip/

![2022-10-12-11-10-26](https://user-images.githubusercontent.com/753736/195301497-603779c1-0536-40d7-b18e-5553fdf93e7a.png)

**Comment by anilanar** [comment]
Perhaps allow us to pass popper specific options to combobox such as `flip`, `sameWidth`?
I'd prefer not to use `sameWidth` in my use case, which tries to mimic native system select dropdowns as much as possible.

**Comment by anubra266** [comment]
@anilanar You can manage the positioning with any solution that works best for you. https://github.com/chakra-ui/zag/issues/266#issuecomment-1214301293
SO feel free to plug in popper.

**Comment by anilanar** [comment]
@anubra266 Shouldn't there be a way to disable built-in positioning because position calculations are somewhat heavy due to internal usage of `getBoundingClientRect` in `floating-ui`/`popper`?

**Comment by anubra266** [comment]
> @anubra266 Shouldn't there be a way to disable built-in positioning because position calculations are somewhat heavy due to internal usage of `getBoundingClientRect` in `floating-ui`/`popper`?

@anilanar The link in my previous comment shows how to do just that. 😁

**Comment by anilanar** [comment]
@anubra266 Yes but even if I don't use `positionerProps`, `positionerProps` will be still calculated.

**Comment by anubra266** [comment]
@anilanar it does get computed, there's nothing to compute if the positionerEl does not exist. https://github.com/chakra-ui/zag/blob/main/packages/utilities/popper/src/get-placement.ts#L23

**Comment by anilanar** [comment]
Ah ok thanks.

**Comment by anubra266** [comment]
> Ah ok thanks.
@anilanar 
I'll still go ahead to fix the flip issue in the default positioning logic.

**Comment by anilanar** [comment]
Kinda makes sense, I actually used `var(--reference-width)` for a custom min-width behavior. I'd have to copy paste that middleware if I wanted to roll my own positioning.
