### ISSUE TITLE
examples/solid-ts can not working

### ISSUE THREAD

**Issue by BeanWei** [chakra-ui/zag#377]
# 🐛 Bug report

I'm new user for zag-js and solid-js. I copied the toggle.tsx code form https://github.com/chakra-ui/zag/blob/main/examples/solid-ts/src/pages/toggle.tsx ,but is is not working.

Only working as below:
```diff
import { normalizeProps, useMachine } from "@zag-js/solid"
import * as toggle from "@zag-js/toggle"
import { createMemo, createUniqueId } from "solid-js"

export default function Page() {
  const [state, send] = useMachine(toggle.machine({ id: createUniqueId(), label: "toggle italic" }))

  const api = createMemo(() => toggle.connect(state, send, normalizeProps))
+ const btnProps = api().buttonProps

  return (
    <div>
-     <button class="toggle" {...api().buttonProps}>
+     <button class="toggle" {...btnProps}>
        B
      </button>
      {api().isPressed ? 'Yes' : 'No'}
    </div>
  )
}
```

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |      0.2.0      |
| Browser          |      Edge Latest      |
| Operating System |      Windows      |
| Solid Version      |      1.6.1     |

**Comment by segunadebayo** [comment]
Hi @BeanWei,

I just tried this, and it works as expected.

Not sure what happened on your end that didn't make it work.

https://stackblitz.com/edit/solidjs-templates-y6xfgv?file=src/App.jsx
