### ISSUE TITLE
[tabs] No implementation found for action: `deleteValue`

### ISSUE THREAD

**Issue by oSethoum** [chakra-ui/zag#393]
![image](https://user-images.githubusercontent.com/88779394/201516329-f07fa23d-b9ad-4560-97ab-af044e41eddf.png)

**Comment by segunadebayo** [comment]
Hi @oSethoum,

We currently didn't implement a way to delete a tab, I'll remove that action/transition.

You might have to implement this using some local state and mapping through the state values to render the tabs. At best, we can consider adjusting the selected value automatically when a tab is removed from the DOM. However, that's a feature, not a bug.

The original intent behind that transition was "CLEAR_VALUE" not "deleteValue". I'll update it as needed.
