### ISSUE TITLE
[Select] Pressing Tab on open select moves focus to wrong element

### ISSUE THREAD

**Issue by visualjerk** [chakra-ui/zag#428]
# 🐛 Bug report

Pressing "Tab" when a select is open results in the wrong element being focused.

## 💥 Steps to reproduce

1. Click on select trigger to open the select menu
2. Press "Tab"
3. The button next to the select trigger does not receive focus

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/sharp-scooby-tlq38i?file=/src/App.vue

## 🧐 Expected behavior

The button next to the select trigger receives focus

## 🧭 Possible Solution

Move focus to the trigger element and let browsers handle default tab behavior.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |  0.1.2  |
| Browser          |  Chrome 107.0.5304.121  |
| Operating System |  MacOS  |

**Comment by visualjerk** [comment]
Most likely invoking `event.preventDefault()` on Keydown Tab in `select.connect.ts ` causes this issue.

**Comment by segunadebayo** [comment]
I just pushed a fix for this. Will release an update shortly.
