### ISSUE TITLE
Combobox doesn't work with touch on Firefox

### ISSUE THREAD

**Issue by jer3m01** [chakra-ui/zag#481]
# 🐛 Bug report

When using touch on the combobox in Firefox (on desktop and on mobile) the UI flickers:

https://user-images.githubusercontent.com/33844379/212753762-eecff3b0-2d4b-4903-9ca3-e4d95e62ef4c.mp4

The dropdown doesn't show properly and you can't select an option (can only do it with enter).

## 💥 Steps to reproduce

https://zagjs.com/components/solid/combobox on Firefox with a touch screen.

## 🧐 Expected behavior

Should work the same way than in Chromium.

## 🧭 Possible Solution

Probably an inconstancy in events between Firefox and Chromium. 

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |0.2.8|
| Browser          |Firefox|
| Operating System |Android 13 / Windows 11|

**Comment by segunadebayo** [comment]
Good catch! @jer3m01 

I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
