### ISSUE TITLE
Unable to trigger popover state programmatically

### ISSUE THREAD

**Issue by bstro** [chakra-ui/zag#502]
# 🐛 Bug report

I need to be able to trigger a popover when focusing an `Editable` input. I would expect that calling the programmatic popover API methods like `api.open()` and `api.close()` from `Editable`'s callbacks would open and close the popover when called from other zag machine callbacks. However, I cannot get the popover to open unless it is from clicking an element with the `api.triggerProps` attributes spread directly on the rendered element. 

## 💻 Link to reproduction

stackbiltz reproduction: https://stackblitz.com/edit/solidjs-templates-uzhcoj?file=src%2FInputWithPopover.tsx

Click inside the `Editable` input. If you open the web inspector, you may notice that the `console.log` firing from `onOpenChange` of the `Popover` machine does report that the `open` prop is `true` for a brief moment, before being reset to `false`.

## 🧐 Expected behavior

I would expect that calling `popoverApi.open()` from within an `Editable` machine's `onEdit()`callback would trigger the popover to open.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Browser          |  Chrome           |
| Operating System | MacOS 11.6.7            |
```
"solid-js": "^1.6.9",
"@zag-js/editable": "^0.2.8",
"@zag-js/popover": "^0.2.7",
"@zag-js/solid": "^0.2.5",
```

**Comment by visualjerk** [comment]
There are a few issues with the provided composition example:

1. It misses a trigger element for the popover to position against
2. Triggering popoverApi methods from editable callbacks:
```ts
      onEdit() {
        popoverApi().open();
      },
      onSubmit() {
        popoverApi().close();
      },
```
This results in the following behavior:

Editable gets focused
-> Editable onEdit triggers
-> Popover opens
-> Popover gets focused automatically
-> Editable looses focus
-> Editable onSubmit triggers
-> Popover closes

A possible solution is to provide the same trigger element for both editable and popover. In addition you can use popover's `initialFocusEl` option to set focus to the editable input:

https://stackblitz.com/edit/solidjs-templates-aygzbe?file=src%2FInputWithPopover.tsx

**Comment by bstro** [comment]
Ah, I see. Many thanks @visualjerk — that was super helpful.
