### ISSUE TITLE
Zag menu react dependency error

### ISSUE THREAD

**Issue by timmaier** [chakra-ui/zag#509]
# 🐛 Bug report

React dependency error is thrown when using example Vue 3 SFC Menu in Vue 3 project. 

## 💥 Steps to reproduce
1. npm install @zag-js/menu @zag-js/vue
2. Create a component wrapping the Vue 3 SFC example here: https://zagjs.com/components/react/menu
3. Use the wrapped component in App.vue

## 💻 Link to reproduction
Here's a reproduction link in stackblitz showcasing the error:

CodeSandbox reproduction: https://stackblitz.com/edit/github-gdgttl-rlh8hc?file=package-lock.json

## 🧐 Expected behavior

React not be a dependency

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
