### ISSUE TITLE
[Pin Input] Multiple characters in input

### ISSUE THREAD

**Issue by hadar759** [chakra-ui/zag#512]
# 🐛 Bug report

When a character is entered in a `pin-input` input which already contains the same character, the character gets doubled.

Afterwards, when another character gets inputted to the same input, the input contents would contain to a single instance of the first character, and another input would contain the new character.

This bug cannot be reproduced in the last input.

## 💥 Steps to reproduce

1. Go to https://zagjs.com/components/react/pin-input
2. Fill either the 1st or 2nd input with a character
3. Re-focus that input and enter the same character again

To see the character jumping:
4. Re-focus that input, and enter a different character

## 💻 Link to reproduction

https://codesandbox.io/s/serverless-water-n9q7ox

## 🧐 Expected behavior

The input will be overriden with the character entered.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |      0.2.8 (from site)      |
| Browser          |       Chrome 106.0.5249.119     |
| Operating System |      Mac      |

## 📝 Additional information

https://user-images.githubusercontent.com/23258552/217195776-51a72f8c-e1cc-4c6f-911c-38ce1bf6b636.mov

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
