### ISSUE TITLE
Add option to change locale of seperator / delimiter

### ISSUE THREAD

**Issue by elmarvr** [chakra-ui/zag#523]
# 🚀 Feature request

> Add option to change locale of seperator / delimiter

**Comment by segunadebayo** [comment]
I don't understand this. I guess you're referring to the tags-input component.

You can change the delimiter yourself.

```js
useMachine(tagsInput.machine({ delimiter: "<my-custom-one>" }))
```

**Comment by elmarvr** [comment]
I meant in the number input, I want to use a comma instead of a dot as a decimal separator. I tried to set it up with the format / parse functions but i can't get it to work...
