### ISSUE TITLE
[Combobox] `openOnClick` with `blurOnSelect` not registering after select

### ISSUE THREAD

**Issue by hadar759** [chakra-ui/zag#528]
# 🐛 Bug report
With the `openOnClick` and `blurOnSelect` options turned on after selection of an option the input is blurred, however refocusing into that input won't trigger the combobox options opening, instead requiring a manual blur to trigger that behavior.

## 💥 Steps to reproduce

1. Go to the [codesandbox reproduction](https://codesandbox.io/s/cool-payne-qzoy5e?file=/src/App.js)
2. Open the combobox input
3. Select an option
4. Attempt to refocus into the input to open the combobox options

## 💻 Link to reproduction

https://codesandbox.io/s/cool-payne-qzoy5e?file=/src/App.js

## 🧐 Expected behavior

The combobox options are displayed.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |     0.3.9      |
| Browser          |    Chrome 109.0.5414.119        |
| Operating System |     MacOS Ventrua 13.2      |

## 📝 Additional information

https://user-images.githubusercontent.com/23258552/218423025-86db64d1-c051-47ed-95eb-3e90bb9f10b2.mov

**Comment by hadar759** [comment]
Not filing another issue because I believe this stems from the same place, however `blurOnSelect` with `selectInputOnFocus` is also problematic

https://user-images.githubusercontent.com/23258552/218434518-3e6b7780-7412-4880-a439-1134bfbf11dc.mov

**Comment by segunadebayo** [comment]
Good catch @hadar759.

Pushed a fix for this. We'll release an update shortly
