### ISSUE TITLE
`selectInputOnFocus` with `blurOnSelect` not registering after select

### ISSUE THREAD

**Issue by hadar759** [chakra-ui/zag#530]
# 🐛 Bug report

With `selectInputOnFocus` and `blurOnSelect` on and `openOnClick` off, selecting an option will blur the combobox, and when refocusing the input content won't get selected.

With `openOnClick` option turned on, this behavior is fixed. However another bug arises - after selecting an option that is currently selected, the combobox will be blurred and refocusing the input will cause the content to get selected and then immediately unselected.

Also outlined in [my previous issue](https://github.com/chakra-ui/zag/issues/528#issuecomment-1427703503)

### with `openOnClick: false`
1. Go to https://codesandbox.io/s/without-open-on-click-6zzkgn?file=/src/App.js
2. Focus the combobox
3. Enter 'test' and select the option that comes up
4. Re-focus the combobox

### with `openOnClick: true`
1. Go to https://codesandbox.io/s/with-open-on-click-uvynjm?file=/src/App.js
2. Focus the combobox
3. Enter 'test' and select the option that comes up
4. Re-focus the combobox
5. Select the 'test' option again
6. Re-focus the combobox

## 💻 Link to reproduction

with `openOnClick: false`: https://codesandbox.io/s/without-open-on-click-6zzkgn?file=/src/App.js

with `openOnClick: true`: https://codesandbox.io/s/with-open-on-click-uvynjm?file=/src/App.js
## 🧐 Expected behavior

Input consistently gets selected.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |      0.0.0-dev-20230214091932      |
| Browser          |       Chrome 109.0.5414.119     |
| Operating System |    MacOS Ventura 13.2    |

### with `openOnClick: false`

https://user-images.githubusercontent.com/23258552/218762438-9e45e985-6aea-4273-a242-9a3ed2232361.mov

### with `openOnClick: true`
First showing the correct behavior, then the bug

https://user-images.githubusercontent.com/23258552/218762562-ce3b4349-4b55-4411-9b2b-903d0c596622.mov

**Comment by anubra266** [comment]
@hadar759 do you still face this issue?

**Comment by hadar759** [comment]
> @hadar759 do you still face this issue?

Yeah, just tested on `zag-js/react: 0.5.0` and `zag-js/combobox: 0.6.0`
