### ISSUE TITLE
slider value jumps when clicking thumb

### ISSUE THREAD

**Issue by stefanprobst** [chakra-ui/zag#541]
# 🐛 Bug report

when clicking a slider thumb (without moving the mouse), the slider thumb moves and the slider value changes.

## 💥 Steps to reproduce

1. Go to https://zagjs.com/components/react/range-slider
2. Click on a slider thumb
3. Observe the slider value change, and the slider thumb move, even though the pointer device did not move

## 💻 Link to reproduction

https://zagjs.com/components/react/range-slider

## 🧐 Expected behavior

the slider thumb should only move when the pointer device moves

## 🧭 Possible Solution

not sure, maybe this is happening because the click event also registers on the slider track?

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |  0.2.13      |
| Browser          |  Firefox 109 |
| Operating System |  Linux       |

## 📝 Additional information

https://user-images.githubusercontent.com/20753323/221188147-462200f6-80f0-4d39-9613-e3cef0090025.mp4

**Comment by segunadebayo** [comment]
Hey @stefanprobst,

This is by design, not a bug. The event listeners are attached to the slider track for quick feedback when the pointer-down event is triggered anywhere along the track.

Essentially, the slider value updates when there's a pointer down along the track and when the pointer moves.

I hope this is clear.

Cheers.

**Comment by stefanprobst** [comment]
thanks for your answer!

hmm it definitely was unexpected behavior for me. does that mean anytime the slider thumb is not clicked exactly in the center, the slider value will change on pointerdown? i also checked with [react spectrum's slider](https://react-spectrum.adobe.com/react-spectrum/Slider.html) and they don't seem to have that behavior.
