### ISSUE TITLE
onValuesChange type error for @zag-js/menu

### ISSUE THREAD

**Issue by jonathanwilke** [chakra-ui/zag#546]
# 🐛 Bug report

In the latest version of @zag-js/menu there seems to be a type issue.

The docs say onValuesChange, but the type has onValueChange.

<img width="641" alt="Bildschirm­foto 2023-02-26 um 13 57 06" src="https://user-images.githubusercontent.com/1453455/221411763-10f68eac-1f2a-4692-a0bd-0cb7ddf7a382.png">

**Comment by anubra266** [comment]
Use what's provided by the types, the docs will be updated accordingly. Thanks for catching this @jonathanwilke

**Comment by jonathanwilke** [comment]
The strange thing is, that it only works with onValuesChange 😅
