### ISSUE TITLE
Select and menu dropdown not opening when another select or menu is already open if trigger is button

### ISSUE THREAD

**Issue by timmaier** [chakra-ui/zag#548]
# 🐛 Bug report

I'm using zag with vue been great thankyou! 

I found an issue when the trigger element is a button the select and menu machines don't seem to open if a different select or menu is open. Only the focus state is applied.

## 💥 Steps to reproduce

1. Go to https://stackblitz.com/edit/github-gdgttl-xqdew4?file=src/App.vue
2. Click on Select 1
3. Click on Select 2
4. Select 2 is not open

CodeSandbox reproduction:  https://stackblitz.com/edit/github-gdgttl-xqdew4?file=src/App.vue

## 🧐 Expected behavior

1. Click on Select 1
2. Click on Select 2
3. Select 2 menu or select is open

## 🧭 Possible Solution

Updating the <button> element in Select component to a div fixes the issue as a workaround for now.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version (vue)      |     ^0.2.10       |
| @zag-js/select | ^0.1.14 |
| Browser          |         Chrome Version 110.0.5481.177 (Official Build) (arm64)   |
| Operating System |       MacOs     |

**Comment by segunadebayo** [comment]
Had a quick look into this. This is happening because we always restore focus to the trigger when the menu/select closes, we need to be smart about this when to "close and restore focus", and when to "close only"

**Comment by hwmaier** [comment]
> For the select component, we intend to make it modal by default, so this behavior is fine.

I would have expected that the zag/select behaves the same as a native select meaning you can click on the trigger and the content appears straight away without having to click again. I think the double click is really counter-intuitive.

**Comment by timmaier** [comment]
> For the select component, we intend to make it modal by default, so this behavior is fine.

Thanks for the quick response! While I understand that the select component is intended to be modal by default, I was hoping that the select component would behave like a native select, where clicking on the trigger immediately shows the content without requiring a second click. I believe this would make the user experience more intuitive and less confusing, especially when coming from libraries like headless ui.

**Comment by timmaier** [comment]
I added some more diagnostic with an onOpen() and onClose() callback which logs those events. It appears that the second select opens but closes straight away with the same mouse click: https://stackblitz.com/edit/github-gdgttl-asfao4?file=src/components/Select.vue

**Comment by segunadebayo** [comment]
I understand your point, @timmaier, and it's valid.

This issue must be related to the focus event coordination. Will look into it pretty soon.

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
