### ISSUE TITLE
Support Xstate visualizer

### ISSUE THREAD

**Issue by segunadebayo** [chakra-ui/zag#56]
In an ideal world, I'd really love for Zag to work seamlessly with XState. I'm more than happy to switch to `@xstate/fsm` when it has the key features we need.

For now, we'll focus on supporting XState Visualizer. Here are the tasks that come to mind:

- Write a code mod or script to convert the machine's configuration to XState (we can skip the machine options)
- Write a script to convert the machine configuration to a PNG/SVG format
- Setup a CI action on PRs that tracks changes in the `.machine` files and shows the before/after logic changes

**Comment by xgenvn** [comment]
Hi @segunadebayo, when in search for the fsm implementation in `zag.js`, I thought it was `@xstate/fsm`, but actually the implementation is not the same. What are the key features not available in `@xstate/fsm`?
Is there any work for implementing the features you need in `@xstate/fsm` through PR or sort of discussion?

**Comment by segunadebayo** [comment]
Hi @xgenvn,

Yes, the implementation is not the same but we tried to keep the machine API somewhat similar.

Here are some features we needed:

- Delayed transitions
- Activities / Services
- Guard combinations (and, or, not)
- Computed properties
- Spawning actors / machines

These are features that exists in core XState itself but we couldn't use it for bundle size concerns. Even at the current state, we need need to slim down the bundle size of Zag.

I'd love to contribute back to xstate/fsm sometime in the future.

**Comment by tomByrer** [comment]
> I'd love to contribute back to xstate/fsm sometime in the future.

I wondered if the main XState could be more component driven or can import only as-needed like lodash.
