### ISSUE TITLE
Transient updates not working in Solid Slider

### ISSUE THREAD

**Issue by binajmen** [chakra-ui/zag#568]
# 🚀 Feature request

I would like to be able to update the `min` and `max` values of a slider

## 🧱 Problem Statement / Justification

I'm using Solid for a tiny app. I have two number inputs to define a range. This range is then used for the slider. At the moment, when I change the range values, I can't reflect these changes in the slider.

## ✅ Proposed solution or API

Add two methods: `setMin(value: number)` and `setMax(value: number)`
```ts
type SliderProps = {
  label: string;
  defaultValue: number;
  min: number;
  max: number;
  class: string;
  onChange?: (details: { value: number }) => void;
  onChangeEnd?: (details: { value: number }) => void;
};

export function Slider(props: SliderProps) {
  const [state, send] = useMachine(
    slider.machine({
      id: createUniqueId(),
      value: props.defaultValue,
      min: props.min,
      max: props.max,
      onChange: props.onChange,
      onChangeEnd: props.onChangeEnd,
    })
  );

  const api = createMemo(() => slider.connect(state, send, normalizeProps));

  createEffect(() => api().setMax(props.max)); 👈 👈 👈 👈 

  ...
}
```

## ↩️ Alternatives

Because of how Solid works, I'm unsure if I have an alternative.

**Comment by segunadebayo** [comment]
Hi @binajmen, you can pass a controlled context to the `useMachine`. This will remove the need for more `api` helpers like `setMin`, `setMax`, etc.

```ts
type SliderProps = {
  label: string;
  defaultValue: number;
  min: number;
  max: number;
  class: string;
  onChange?: (details: { value: number }) => void;
  onChangeEnd?: (details: { value: number }) => void;
};

export function Slider(props: SliderProps) {
  const [state, send] = useMachine(
    slider.machine({
      id: createUniqueId(),
      value: props.defaultValue,
    }),
   {
   context: {
      min: props.min,
      max: props.max,
      onChange: props.onChange,
      onChangeEnd: props.onChangeEnd,
    }
   }
  );

  const api = createMemo(() => slider.connect(state, send, normalizeProps));

  ...
}
```

**Comment by binajmen** [comment]
Hi @segunadebayo, thank you for mentioning the context, I was not aware of that. Nevertheless, I can't find the right way to update the max value.

Here a simple reproduction:
https://codesandbox.io/s/cool-tamas-463thu?file=/index.js

The first input is supposed to set the max value. I would expect the slider to update the range accordingly, but it doesn't. This is most probably due to how Solid works: the useMachine is executed only one time.

**Comment by binajmen** [comment]
In React this would work because updating the `max` value would re-render the `Slider` component. It is not the case in Solid.

Is there a way to update the context by emitting some kind of event to the machine? So you don't need to expose additional api helpers, while allowing flexibility for specific use cases. I feel my use case is valid (in Solid terms).

**Comment by anubra266** [comment]
@binajmen https://codesandbox.io/s/solid-zag-slider-forked-z2yd1i?file=/index.js
