### ISSUE TITLE
Number input machine settings are not updated when new arguments are passed

### ISSUE THREAD

**Issue by xvvvyz** [chakra-ui/zag#569]
# 🐛 Bug report

https://discord.com/channels/964648323304808488/964648323304808496/1086776846387007639

## 💥 Steps to reproduce

https://discord.com/channels/964648323304808488/964648323304808496/1086783649594232914

## 💻 Link to reproduction

https://codesandbox.io/s/sleepy-fast-5rb0zf?file=/src/App.tsx

## 🧐 Expected behavior

I expect the machine to respect the new arguments.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      | ^0.3.10 & ^0.2.14   |
| Browser          | ff 112.0b3 (64-bit)           |
| Operating System | macOS 13.2.1 (22D68)           |

**Comment by segunadebayo** [comment]
Hi @xvvvyz,

We need to emphasize this more in the docs. You can use the transient `context` property in the `useMachine` hook to dynamically update the context property.

```jsx
const [state, send] = useMachine(
      numberInput.machine({
        id: name,
        name,
        value: String(value)
      }),
      {
        context: {
          max: Number(max),
          min: Number(min)
        }
      }
    );
```

Here's the code:
https://codesandbox.io/s/exciting-farrell-17ubsl?file=/src/NumberInput.tsx

**Comment by xvvvyz** [comment]
I figured there was some simple solution. Thank you!
