### ISSUE TITLE
[Number Input] Not working on iOS 13 Safari

### ISSUE THREAD

**Issue by malangcat** [chakra-ui/zag#574]
# 🐛 Bug report

## 💥 Steps to reproduce

(Reproduce in iOS 13 Safari)

1. Go to [https://zagjs.com/components/react/checkbox](https://zagjs.com/components/react/checkbox)
2. Type number in demo Number Input component
```
[Error] TypeError: e.hasTag is not a function. (In 'e.hasTag("focus")', 'e.hasTag' is undefined) — 208-24053afed3b390ac.js:1:186862
	du (framework-b3ca2e9a9574e304.js:1:71888)
	(anonymous function) (framework-b3ca2e9a9574e304.js:1:72405)
	Ua (framework-b3ca2e9a9574e304.js:1:53530)
	ki (framework-b3ca2e9a9574e304.js:1:101304)
	bi (framework-b3ca2e9a9574e304.js:1:100872)
	yi (framework-b3ca2e9a9574e304.js:1:100408)
	(anonymous function) (framework-b3ca2e9a9574e304.js:1:112245)
	ws (framework-b3ca2e9a9574e304.js:1:112758)
	is (framework-b3ca2e9a9574e304.js:1:106479)
	is
	jl (framework-b3ca2e9a9574e304.js:1:46914)
	cs (framework-b3ca2e9a9574e304.js:1:106783)
	Le (framework-b3ca2e9a9574e304.js:1:16057)
	Hr (framework-b3ca2e9a9574e304.js:1:38733)
	Kn (framework-b3ca2e9a9574e304.js:1:23129)
	Qn (framework-b3ca2e9a9574e304.js:1:22913)
	Qn
	dispatchEvent
	a (208-24053afed3b390ac.js:1:155136)
	dispatchChangeEvent (208-24053afed3b390ac.js:1:185799)
	(anonymous function) (208-24053afed3b390ac.js:1:58469)
	(anonymous function) (208-24053afed3b390ac.js:1:54111)
	(anonymous function) (208-24053afed3b390ac.js:1:52121)
	(anonymous function) (208-24053afed3b390ac.js:1:295794)
	promiseReactionJob
[Error] TypeError: undefined is not an object (evaluating 'e.toString')
	Ur (framework-b3ca2e9a9574e304.js:1:37485)
	(anonymous function) (framework-b3ca2e9a9574e304.js:1:42881)
	ss (framework-b3ca2e9a9574e304.js:1:106549)
	Le (framework-b3ca2e9a9574e304.js:1:16008)
	Hr (framework-b3ca2e9a9574e304.js:1:38733)
	Kn (framework-b3ca2e9a9574e304.js:1:23129)
	Qn (framework-b3ca2e9a9574e304.js:1:22913)
	Qn
	dispatchEvent
	a (208-24053afed3b390ac.js:1:155136)
	dispatchChangeEvent (208-24053afed3b390ac.js:1:185799)
	(anonymous function) (208-24053afed3b390ac.js:1:58469)
	(anonymous function) (208-24053afed3b390ac.js:1:54111)
	(anonymous function) (208-24053afed3b390ac.js:1:52121)
	(anonymous function) (208-24053afed3b390ac.js:1:295794)
	promiseReactionJob
```

## 💻 Link to reproduction

(in iOS 13 Safari)
[https://zagjs.com/components/react/checkbox](https://zagjs.com/components/react/checkbox)

## 🧭 Possible Solution

When I log state object before error, `Proxy {}` is printed. Seems like Proxy in @zag-js/store is related.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |     number-input 0.2.14      |
| Browser          |   iOS 13 Safari         |
| Operating System |    iOS        |

**Comment by anubra266** [comment]
@malangcat I don't understand this. Your title says Number input, but you point to Checkbox.
I'm unable to reproduce this in any of them though. 
Please feel free to reopen, when the issue is clearer.

**Comment by malangcat** [comment]
@anubra266 Sorry about wrong description and lack of information. Fixed description and added video about current behavior.

**Comment by anubra266** [comment]
@malangcat I'm unable to reproduce

https://user-images.githubusercontent.com/30869823/228478582-37f44ea9-25af-4a4d-a0bd-dd64cb0033b0.MP4


https://user-images.githubusercontent.com/30869823/228479444-5876f95a-7839-46c1-ae71-24ee5fcedad9.mp4

**Comment by malangcat** [comment]
@anubra266 This video is using iOS 16.2. Could you try again on iOS 13.6, or is there browser support coverage in the documentation?
