### ISSUE TITLE
Method `setValue` is missing for Rating

### ISSUE THREAD

**Issue by christianhegedues** [chakra-ui/zag#576]
# 🚀 Feature request

While the current value for the most input-like components can be changed externally using the `setValue` method, this method is missing for the rating component API

## 🧱 Problem Statement / Justification

In addition to being consistent with other input-like interfaces, such rating components are often used in single page applications where data is bound via two ways. If the current value changes independently of the user's input, e.g. via a more recent api call, there is no way to communicate this to the component

## ✅ Proposed solution or API

```ts
// rating-group.connect.ts

const api = {
  ...

  /**
   * Function to set the value of the rating group
   */
  setValue(value: string) {
    send({ type: "SET_VALUE", value, manual: true })
  },

  ...
}
```

**Comment by segunadebayo** [comment]
Good catch @christianhegedues.

I just pushed a fix for this. We'll release an update shortly.
