### ISSUE TITLE
[vue] normalizeProps emits "avoid passing non-primitive value as children" warnings

### ISSUE THREAD

**Issue by klaemo** [chakra-ui/zag#579]
# 🐛 Bug report

I built a `Tooltip` component in vue using `@zag-js/tooltip` and `@zag-js/vue` by pretty much copy & pasting the example from the documentation.

I'm seeing `[Vue Normalize Prop] : avoid passing non-primitive value as children` warnings in the browser console and I don't know what I'm doing wrong.

## 💥 Steps to reproduce

1. Go to https://codesandbox.io/p/sandbox/zagjs-tooltip-warning-22ehf5?file=%2Fsrc%2Fcomponents%2FTooltip.vue
2. Open the browser dev tools
3. Hover over "Hover me" and wait for the tooltip to appear
4. You will see the warning `[Vue Normalize Prop] : avoid passing non-primitive value as children` multiple times

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/p/sandbox/zagjs-tooltip-warning-22ehf5?file=%2Fsrc%2Fcomponents%2FTooltip.vue

## 🧐 Expected behavior

No warnings

## 🧭 Possible Solution

As far as I understand `normalizeProps` wants to make sure that `children` is a string. A little digging showed me that the `label` part has `children` set to `undefined`. So, `children` is in the `props` object, but is not a `string` -> warning

```js
{
  "children": undefined,
  "data-scope": "tooltip",
  "data-part": "label",
  "id": "tooltip:g_HyDL:content",
  "role": "tooltip",
  "style": {
    "border": "0",
    "clip": "rect(0 0 0 0)",
    "height": "1px",
    "margin": "-1px",
    "overflow": "hidden",
    "padding": "0",
    "position": "absolute",
    "width": "1px",
    "whiteSpace": "nowrap",
    "wordWrap": "normal"
  }
}
```

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |   0.2.10 / 0.2.13         |
| Browser          |    all        |
| Operating System |      macOS      |

## 📝 Additional information

Thank you for building this library and taking the time to look at this bug report 🙏

**Comment by segunadebayo** [comment]
Thanks for reporting this @klaemo.

You're not doing anything wrong, it's a false warning that's incorrect. Will fix that shortly.

**Comment by segunadebayo** [comment]
Pushed a fix for this. We'll publish an update shortly.

**Comment by klaemo** [comment]
Thank you for the super quick fix, @segunadebayo! 🚀
