### ISSUE TITLE
Does `<Environment />` or `getRootNode` works in browser extension shadowDOM?

### ISSUE THREAD

**Issue by michael-land** [chakra-ui/zag#585]
# 🐛 Bug report

I use @ark-ui/react, but the dom lookup/mount logic seems related to zag

I can't seem to get `<Environment />` / `getRootNode` work in chrome extension environment. The zag-portal still mount inside `body` even when i pass a custom shadowRoot via `<Environment />` / `getRootNode` 

## 💥 Steps to reproduce

1. clone repo
2. pnpm i / npm i
3. pnpm dev / npm dev
4. loading the extension.  ( for how to see https://docs.plasmo.com/framework/workflows/dev )
5. goto google.com
6. click open dialog button

## 💻 Link to reproduction

it's a browser extension, unable to do a reproduction in CodeSandbox. please see provided github repo.

https://github.com/michael-land/zag-issue

https://user-images.githubusercontent.com/33362998/228428519-4b2bcee9-1603-4826-8373-79c3e1a35013.mov

## 🧐 Expected behavior

it mount zag-portal inside shadow dom

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |            |
| Browser          |     chrome     |
| Operating System |       macOs     |

**Comment by anubra266** [comment]
Hi @michael-land curious about the querySelector you're using to get the shadowRoot. Doesn't seem to match anything in your codebase.
Maybe try this way: https://github.com/chakra-ui/zag/blob/2ca9c9dcda0ddc0410852d57df457c1b829bc825/examples/shadow-dom/src/Menu.tsx#L13
