### ISSUE TITLE
Switch but externally controlled check prop

### ISSUE THREAD

**Issue by nephix** [chakra-ui/zag#586]
# 🚀 Feature request

Recently `@zag-js/switch` has been released. I'm looking for an option to externally (via props) control the `checked` state

## 🧱 Problem Statement / Justification

While it's possible to define `defaultChecked` which sets the initial state of the machine, it's not possible to update the switch's state from the outside (via props)

## ✅ Proposed solution or API

I tried to use `useEffect` together with `api.setChecked` but the state won't change:

```tsx
import type { FC } from 'react';
import * as zagSwitch from '@zag-js/switch';
import { useMachine, normalizeProps } from '@zag-js/react';

interface SwitchProps {
  checked: boolean;
  disabled?: boolean;
}

export const SwitchTmp: FC<SwitchProps> = ({ checked, disabled }) => {
  const [state, send] = useMachine(
    zagSwitch.machine({
      disabled,
      id: generateId(),
    }),
  );
  const api = zagSwitch.connect(state, send, normalizeProps);

  useEffect(() => {
    api.setChecked(defaultChecked);
  }, [checked]);

  return <>...</>;
};
```

**Comment by anubra266** [comment]
@nephix Please attach a codesandbox reproduction of what you're trying to do.

**Comment by nephix** [comment]
@anubra266 I got it to work now, was a mistake on my end 😅
