### ISSUE TITLE
[Popover] using defaultOpen in Portal does not render correctly

### ISSUE THREAD

**Issue by malangcat** [chakra-ui/zag#595]
# 🐛 Bug report

## 💥 Steps to reproduce

1. Open `examples/next-ts/pages/popover.tsx`.
2. Insert `defaultOpen: true` under `id: React.useId()` (line 14)
3. `pnpm start-react` and open http://localhost:3000/popover

https://user-images.githubusercontent.com/102206520/229860287-4450c831-caa7-443d-9f8b-6fb29fda0a5c.mov

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/musing-pike-2n3jl2?file=/src/App.tsx

`defaultOpen` is set true, initial transform of `popper` part is `transform: translate3d(0px, -200%, 0px);`, so it is not rendered in screen.

## 🧐 Expected behavior

Popover should be rendered on Anchor element.

## 🧭 Possible Solution

```
[@zag-js/dismissable] node is `null` or `undefined`
```
warning occurs, because `dom.getPositionerEl(ctx)` is `undefined` on initial `trackPositioning` call, if Positioner is rendered in portal.

I am using following workaround:

1. wrap `trackPositioning` activity with `nextTick()`.

https://github.com/chakra-ui/zag/blob/571bb18d990a3d05cf4e3502307531f8a9517188/packages/machines/popover/src/popover.machine.ts#L78-L90

```ts
        trackPositioning(ctx) {
          return nextTick(() => {
            ctx.currentPlacement = ctx.positioning.placement;
            const anchorEl = dom.getAnchorEl(ctx) ?? dom.getTriggerEl(ctx);

            return getPlacement(anchorEl, dom.getPositionerEl(ctx), {
              ...ctx.positioning,
              onComplete(data) {
                ctx.currentPlacement = data.placement;
              },
              onCleanup() {
                ctx.currentPlacement = undefined;
              },
            });
          });
```

This approach works, but `currentPlacement` is initialized after first render, which causes flickering.

https://user-images.githubusercontent.com/102206520/229863095-10e3b38c-9fd3-4621-afd0-befca6bf9900.mov

So, I added following code inside my react integration layer:

2. Programmatically call setPositioning on initial `useLayoutEffect` call.

```ts
  // FIXME: This is a workaround for a bug in `@zag-js/popover`
  // where the popover is not positioned correctly on the first render.
  useLayoutEffect(() => {
    apiRef.current.setPositioning({});
  }, []);
```

I didn't tested about this workaround in other frameworks.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |     @zag-js/popover: 0.2.15, @zag-js/react: 0.3.12       |
| Browser          |    Chrome 111.0.5563.64 arm64       |
| Operating System |     MacOS 12.6       |

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
