### ISSUE TITLE
[Dialog] Dynamic Vue component causes dialog to close

### ISSUE THREAD

**Issue by jiblett1000** [chakra-ui/zag#596]
# 🐛 Bug report

I mentioned this on discord but posting here to better track it.

This is an issue where a dynamic Vue component changing is causing the dialog to close unwantedly.

```html
<component
  :is="api.isPressed ? LightModeIcon : DarkModeIcon"
 />
```

Oddly, wrapping the dynamic component in a Vue transition alleviates the issue:

```html
<TransitionFade :duration="300">
  <component
    :is="api.isPressed ? LightModeIcon : DarkModeIcon"
    class="absolute h-8 w-8"
  />
</TransitionFade>
```

## 💥 Steps to reproduce

In reproduction:

1. Click on the open dialog button.
2. Click on the "component one" button.
3. See dialog close.

## 💻 Link to reproduction

This isn't a codesandbox reproduction, but I can redo there if need be.

 https://github.com/jiblett1000/zag-dialog

## 🧐 Expected behavior

The dialog should not be closing prematurely when a dynamic component switches.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |     @zag-js/vue 0.2.12       |
| Browser          |   Chrome - Latest    |
| Operating System |  Fedora  37   |

**Comment by jiblett1000** [comment]
I've noticed something further when messing around with this. It's only when the dynamic component is clicked on specifically that the dialog is closed prematurely. For example, if you click on the edge of the button (not on the dynamic component), the component will switch and everything seems to work as expected.

**Comment by anubra266** [comment]
@jiblett1000 could you create a codesandbox repro please. It's easier to collaborate with that.

**Comment by jiblett1000** [comment]
@anubra266 Here ya go. https://codesandbox.io/p/github/jiblett1000/zag-dialog/master?file=%2Fcomponents%2FThemeToggle.vue&selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A9%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A9%7D%5D&workspace=%257B%2522activeFilepath%2522%253A%2522%252Fcomponents%252FThemeToggle.vue%2522%252C%2522openFiles%2522%253A%255B%2522README.md%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522spaces%2522%253A%257B%2522clg6xmfvh000x2v6iad675hbe%2522%253A%257B%2522key%2522%253A%2522clg6xmfvh000x2v6iad675hbe%2522%252C%2522name%2522%253A%2522Default%2522%252C%2522devtools%2522%253A%255B%257B%2522key%2522%253A%2522clg6y2i8100142v6idktf5f2i%2522%252C%2522type%2522%253A%2522PROJECT_SETUP%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522key%2522%253A%2522clg6xmwr7006d2v6i01r2ljto%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522key%2522%253A%2522clg6xmvjb003s2v6ij3vls4p6%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D%257D%252C%2522currentSpace%2522%253A%2522clg6xmfvh000x2v6iad675hbe%2522%252C%2522spacesOrder%2522%253A%255B%2522clg6xmfvh000x2v6iad675hbe%2522%255D%252C%2522hideCodeEditor%2522%253Afalse%257D


So, the plot thickens.... I noticed that the bug wasn't happening when I was in responsive design mode. So when you're in the codesandbox, if you open the preview in a new tab and use responsive design mode in the developer tools, the bug should happen. I've tried with both Chrome and Firefox as well as on my phone. The bug seems to only be in mobile browsers.

**Comment by segunadebayo** [comment]
This has already been fixed in the last release.

If the issue persists after the updating, I'll re-open this issue.

**Comment by jiblett1000** [comment]
@segunadebayo Yep, seems to be working fine in the codesandbox now. Awesome!
