### ISSUE TITLE
[Toggle] State naming

### ISSUE THREAD

**Issue by jiblett1000** [chakra-ui/zag#597]
# 🐛 Bug report

This is not a huge deal, but the name of the current state in the toggle component is `isPressed`. Seems like it should be `isToggled`....just better semantically.

## 💻 Link to reproduction

CodeSandbox reproduction: https://your-codesandbox-link-goes-here.io

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |            |
| Browser          |            |
| Operating System |            |

**Comment by segunadebayo** [comment]
Hi @jiblett1000,

Thanks for bringing this up. We thought about this and intend to keep the current naming for now.

"Toggle" implies an action that can either be in or out. It leaves to meaning as to whether it's actually "in" or "out"

Using the "isPressed" helps to understand whether it's actually "in" or not.

**Comment by jiblett1000** [comment]
@segunadebayo Fair enough. Thanks for the response. 😁
