### ISSUE TITLE
Combobox: stay open on selection

### ISSUE THREAD

**Issue by anilanar** [chakra-ui/zag#604]
As I described [before](https://github.com/chakra-ui/zag/issues/164#issuecomment-1214346370), need a way to keep the combobox open on selection. The use case is multi-select combobox, where user wants to select/deselect multiple options before dropdown closes. Using `blurOnSelect: false` isn't sufficient because when combobox is focused, it doesn't necessarily have the dropdown content open.

See [my solution](https://github.com/anilanar/zag/commit/7a2c3b416138973f6b395de0423cb6624db7f4c0).

**Comment by anilanar** [comment]
With my solution, clicking options triggers double click events because options listen to both `click` and `pointerUp` events. See:

https://github.com/chakra-ui/zag/blob/2ebe3841b81de497aee17c6784101adedf00a3c4/packages/machines/combobox/src/combobox.connect.ts#L299-L306

So this needs to be fixed too.

**Comment by srflp** [comment]
I added the closeOnSelect flag in #833.

And the problem with double click events seems to does not longer exist, at least I'm unable to reproduce it.
It looks like it has been fixed somewhere along the way.
