### ISSUE TITLE
Combobox doesn't seem to detect non-ASCII characters input

### ISSUE THREAD

**Issue by x86chi** [chakra-ui/zag#622]
# 🐛 Bug report

## 💥 Steps to reproduce

https://user-images.githubusercontent.com/5278201/235395969-05bf3f2c-ba2e-4ab0-8f0f-88aa7117c861.mp4

In the case of Korean, it detects only when backspace input occurs, and Japanese input is not detected at all.

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/p/sandbox/3ei5s3?file=%2Fsrc%2FApp.tsx

## 🧐 Expected behavior

Combobox doesn't seem to detect non-ASCII characters input

## 🧭 Possible Solution

- Debugging on `onInputChange` event
- Add typing e2e test for non-ASCII characters

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |       latest     |
| Browser          |       FireFox     |
| Operating System |     MacOS lastest       |

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
