### ISSUE TITLE
[Checkbox] [React] The checkbox is triggered by double-clicking.

### ISSUE THREAD

**Issue by ryuhangyeong** [chakra-ui/zag#625]
### Description

checkbox component is triggered by double-clicking. Is it intentional?

It is different from triggering with a single click in the chartra ui or other component libraries.

### Link to Reproduction

https://ark-ui.com/docs/react/components/checkbox

### Steps to reproduce

1. Go to Link

### Ark UI Version

recent

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

Google Chrome 112.0.5615.138

### Additional Information

Window 11

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
