### ISSUE TITLE
When close the dialog, throw a error

### ISSUE THREAD

**Issue by yzh990918** [chakra-ui/zag#631]
# 🐛 Bug report

![image](https://github.com/chakra-ui/zag/assets/46418596/cd2bd171-579a-4be2-9c64-afadbe1afb10)

## 💻 Link to reproduction

CodeSandbox reproduction: https://your-codesandbox-link-goes-here.io

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |      0.7.0      |
| Browser          |    chrome 112.0.5615.137       |
| Operating System |      mac      |

**Comment by yzh990918** [comment]
By the way, during the usage process, it was found that there were some Typescript type errors when using the examples in the document, such as:
<img width="1168" alt="image" src="https://github.com/chakra-ui/zag/assets/46418596/16b9196f-ae8c-4ad3-be1a-f4655d6c985a">
<img width="1073" alt="image" src="https://github.com/chakra-ui/zag/assets/46418596/d3e426bf-f359-45b1-8502-f742327090a3">
<img width="985" alt="image" src="https://github.com/chakra-ui/zag/assets/46418596/7cef0295-be38-4579-bde8-30e2452a92e4">
<img width="1126" alt="image" src="https://github.com/chakra-ui/zag/assets/46418596/e4e0cf06-0a22-4c1d-8d77-683e5413d85f">

**Comment by segunadebayo** [comment]
I just fixed the issue with `setReturnFocus` console error.
