### ISSUE TITLE
[NumberInput] Input allowed to enter non-ASCII characters

### ISSUE THREAD

**Issue by flex-boram** [chakra-ui/zag#632]
# 🐛 Bug report

Allowed to enter non-ASCII characters in NumberInput, including [official examples](https://zagjs.com/components/react/number-input).

## 💥 Steps to reproduce

https://github.com/chakra-ui/zag/assets/90584493/58ee9c3e-7845-4c52-965d-d98a498fa8f5

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |            |
| Browser          | Chrome 112.0.5615.137 |
| Operating System | Mac |

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
