### ISSUE TITLE
Fix an issue where machines did not behave correctly when the page was scrolled

### ISSUE THREAD

**Issue by florian-lefebvre** [chakra-ui/zag#651]
### Description

See https://twitter.com/isnhp/status/1658713662910234624?s=20

I can also reproduce on Windows 11

### Link to Reproduction

See https://twitter.com/isnhp/status/1658713662910234624?s=20

### Steps to reproduce

1. Go to homepage
2. Try components
	a. color picker moving dot stays at the top
	b. slider stays at the left

### Ark UI Version

Not applicable (docs)

### Framework

- [ ] React
- [ ] Solid
- [ ] Vue

### Browser

Brave Version 1.51.114 Chromium: 113.0.5672.92 (Official Build)  (64-bit)

**Comment by cschroeter** [comment]
The issue shown only occurs when the page has been scrolled. @segunadebayo

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
