### ISSUE TITLE
[Editable] Resetting to the previous value when exiting the edit mode doesn't work well

### ISSUE THREAD

**Issue by wns3645** [chakra-ui/zag#658]
# 🐛 Bug report

In `Editable` component, resetting to the previous value when exiting from the edit mode doesn't work for some cases
1. When the first time that edit mode is activated, setting the previous value in the context is not invoked when the activation mode is 'dbclick' or calling the `edit` method
2. If the previous value is empty string(''), it is ignored. 

## 💥 Steps to reproduce

https://zagjs.com/components/vue-jsx/editable
You can reproduce the bug on the `Editable` document page.
Case #1
1. Enter edit mode on the element, type something, and press `Esc`.
2. You can see the value doesn't go back to the initial value('')

Case #2
1. Enter some text into the element and save it.
2. You can check resetting work well at this time.
3. Remove all text and save it with an empty string
4. You can find that resetting to the empty string doesn't work.

## 🧐 Expected behavior

Case #1: We should reset to the initial value when exiting from the first edit mode.
Case #2: We should reset to the previous value thought the previous value is an empty string.

## 🧭 Possible Solution

1. Also invoke `setPreviousValue` actions for both 'EDIT' and 'DBLCLICK'. For now, `setPreviousValue` is invoked when only for the 'FOCUS' transition.
	https://github.com/chakra-ui/zag/blob/91d2e95ada4284b27f499b64a8deaa17fd8bac33/packages/machines/editable/src/editable.machine.ts#L55-L68
2. Don't ignore `ctx.previousValue` even though the previous value is an empty string in the `resetValueIfNeeded`
	https://github.com/chakra-ui/zag/blob/91d2e95ada4284b27f499b64a8deaa17fd8bac33/packages/machines/editable/src/editable.machine.ts#L176-L179

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |     0.9.2       |
| Browser          |            |
| Operating System |            |

**Comment by segunadebayo** [comment]
Hi @wns3645,

Thanks for digging into this issue and providing such a detailed report. I appreciate this.

Solution 2 is the more appropriate fix, and I've implemented it.

We'll release an update shortly.

**Comment by nirajarun** [comment]
This same issue is occurring in react. On first edit and then cancel, value is not reverting to previous one. If value field is not provided to the machine then it works fine.
