### ISSUE TITLE
Performance overhead of state machine of simple components

### ISSUE THREAD

**Issue by Code2Life** [chakra-ui/zag#668]
Hi team, I found there is performance overhead, especially for simple component. Not sure which parts cause the overhead,  may be the xstate EFSM or additional accessibility attributes.

TL;DR;
- Benchmark case: render 10000 simple toggle button with @zag-js/toggle & @zag-js/react & native react
- Benchmark result: 5x scripting time of CPU; 10x memory consumption.

## Test Codes

```
import React, { useState } from 'react'
import * as toggle from "@zag-js/toggle"
import { normalizeProps, useMachine } from "@zag-js/react"

export const Toggle = () =>  {
  const [state, send] = useMachine(toggle.machine({id: "2"}))
  const api = toggle.connect(state, send, normalizeProps)
  return <button {...api.buttonProps}>Toggle me: {api.isPressed + ""}</button>
}

export const RawToggle = () => {
    const [isPressed, setPressed ] = useState(false)
    return <button onClick={() => setPressed(!isPressed)}>Toggle me: {isPressed + ""}</button>
}
```

```
export default function App() {
    const toggles = []
    for (let i = 0;i< 10000;i++) {
        toggles.push(
            <Toggle></Toggle>
        )
    }
  return (
    <Container maxWidth="sm">
      <Box sx={{ my: 4 }}>
        {toggles}
      </Box>
    </Container>
  );
}
```

Using @zag-js/toggle

![Screenshot2023_05_31_150901](https://github.com/chakra-ui/zag/assets/14833440/35d612ff-db39-498b-9e6b-f949cc1d029b)

Using native react

![Screenshot2023_05_31_151527](https://github.com/chakra-ui/zag/assets/14833440/3d9eea3a-0b72-4eaa-812a-676aa099949f)

The memory of both are: 26.1MB, 262MB

**Comment by segunadebayo** [comment]
Hi @Code2Life,

Thanks for reporting this. The perf difference is mostly the setup of the machines for each toggle.

Using useMemo for the `toggle.machine()` and `toggle.connect` calls will reduce the scripting time and memory usage.

You can also try progressive disclosure techniques like Virtualization, Pagination, etc.

**Comment by Code2Life** [comment]
@segunadebayo Thank you, in actual cases there won't be so many components in one page. will try to figure out bottleneck of some benchmark case.
