### ISSUE TITLE
[vue] [slider] SliderMarker does not align with SliderThumb correctly

### ISSUE THREAD

**Issue by renatodeleao** [chakra-ui/zag#675]
### Description

On a 0 to 100 slider, if I set the value to 75, I hope that `SliderThumb` sits perfectly on top of the 75 `SliderMaker`. 
Currently the `SliderMarker` Is not aligned with the `SliderThumb`.

### Link to Reproduction

https://ark-ui.com/docs/vue/components/slider

### Steps to reproduce

Just add a style `background:red;` to the marker elements. Note how even if the value is 75, the `SliderMarker` is not aligned with the `SliderThumb`

<img width="665" alt="Screenshot 2023-06-01 at 10 23 18" src="https://github.com/chakra-ui/ark/assets/5116633/7e14ceb4-bafa-421c-ad94-a21992893c7a">

### Ark UI Version

0.4.0

### Framework

- [ ] React
- [ ] Solid
- [X] Vue

### Browser

all

### Additional Information

Contrary to the `SliderMaker`, the `SliderThumb` is not positioned linearly. When the slider value is 75, the thumb is placed 75% left but it's offset by a ratio derived from its size.

This same offset needs to be applied to marks so that they align perfectly with the thumb.

<img width="1069" alt="Screenshot 2023-06-01 at 10 37 20" src="https://github.com/chakra-ui/ark/assets/5116633/7eb963ce-36b8-4feb-a061-c9dc6a7ce909">

This will align top-left edge of the `SliderMaker` bounding-box with the thumb, we would need to still apply `transform: translateX(-50%)`  to each `SliderMaker` to that its box aligns center with the `SliderThumb`. Here's a screenshot (hardcoded).

<img width="1632" alt="Screenshot 2023-06-01 at 10 49 21" src="https://github.com/chakra-ui/ark/assets/5116633/10a00aaf-0185-4ff9-a02f-fd85caae90b3">

 
**Code references @zag-js/slider:**
- [Offset calculation fn](https://github.com/chakra-ui/zag/blob/e93ecc0c602b3d720a0e32053b3ceadfe0dbdc1f/packages/machines/slider/src/slider.style.ts#L15-L25) 
- [transformer](https://github.com/chakra-ui/zag/blob/e93ecc0c602b3d720a0e32053b3ceadfe0dbdc1f/packages/utilities/numeric-range/src/index.ts#L133-L142)

**Comment by segunadebayo** [comment]
Thanks for such a detailed issue breakdown @renatodeleao.

I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.

**Comment by renatodeleao** [comment]
@segunadebayo thanks for the fix! Latest version of `@ark-ui/vue` (0.6.0) still installs `@zajs/slider@0.13.0`. I'll let you know when you guys cut a new release for `ark-ui/vue`.
