### ISSUE TITLE
[Select] `active` pseudo-class only triggered on close

### ISSUE THREAD

**Issue by hadar759** [chakra-ui/zag#690]
# 🐛 Bug report

`active` pseudo-class only triggered on closing of options, not on opening click.

## 💥 Steps to reproduce

1. Go to https://codesandbox.io/s/select-active-style-l10vz0 - see `styles.css` for active style definition on button
2. Click on the button - bg doesn't turn red
3. Click on the button again to close the menu - bg turns red

## 💻 Link to reproduction

https://codesandbox.io/s/select-active-style-l10vz0

## 🧐 Expected behavior

Active styling actives on all button clicks.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |       0.10.2     |
| Browser          |     Arc browser Version 0.106.1 (39259) - Chromium Engine Version 114.0.5735.45     |
| Operating System |      MacOS 13.3.1      |

## 📝 Additional information

https://github.com/chakra-ui/zag/assets/23258552/311ff62e-5254-401a-8bca-8db91fd66e27

**Comment by anubra266** [comment]
@hadar759 the `:active` pseudo is not from zag, that's just native button pseudo. The reason it's not active when opening the select is because the focus is on the select's content when opening it.

**Comment by hadar759** [comment]
I see, thank you 🙏
