### ISSUE TITLE
link in `Menu` does not work

### ISSUE THREAD

**Issue by allypalanzi** [chakra-ui/zag#693]
# 🐛 Bug report

Using touch screens, links in the menu do not work.

## 💥 Steps to reproduce

1. Go to https://codesandbox.io/s/restless-shadow-3g453e?file=/src/App.js / https://3g453e.csb.app/
2. Click to expand the menu, then click `edit` (which should redirect to google)
3. Open Chrome Dev Tools and use the touch screen simulator to repeat the above
4. See that the menu closes and does not go to the link
5. Try clicking the bing link, which works and is not using `getItemProps`

## 💻 Link to reproduction

https://3g453e.csb.app/
https://codesandbox.io/s/restless-shadow-3g453e?file=/src/App.js 

## 🧐 Expected behavior

Link should work across all devices

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |  0.10.2          |
| Browser          |      Chrome 113.0.5672.126      |
| Operating System |      OSX      |

**Comment by mmellado** [comment]
I just went through this exact same issue. In my case, I'm using NextJS, but the fix could also apply to other frameworks. 

Essentially, my solution was to rely entirely on the onSelect key of the machine

```
 const [state, send] = useMachine(
    menu.machine({
      ...,
      onSelect: ({ value }) => {
        if (value.startsWith('http')) {
          window.open(value, '_blank')?.focus();
        } else if (value.startsWith('/') {
          router.push(value);
        } else {
          myCallback(value);
        }
      },
    })
  );
```

Then, when rendering the component, it looks something like this:

```
<div>
      <button {...api.triggerProps}>
        Actions <span aria-hidden>▾</span>
      </button>
      <div {...api.positionerProps}>
        <div {...api.contentProps}>
          <a href="https://bing.com">Bing</a>
          <ul>
            <li {...api.getItemProps({ id: "https://google.com" })}>Edit</li>
            <li {...api.getItemProps({ id: "/other-page" })}>Duplicate</li>
            <li {...api.getItemProps({ id: "callback-1" })}>Delete</li>
            <li {...api.getItemProps({ id: "callback-2" })}>Export...</li>
          </ul>
        </div>
      </div>
    </div>
```

Hope this helps

**Comment by segunadebayo** [comment]
To get this working, you need to change the markup a bit so that the anchor is a menu item.

Here's a working solution: https://codesandbox.io/s/eager-forest-fsms67?file=/src/App.js

```jsx
export function Menu() {
  const [state, send] = useMachine(
    menu.machine({
      id: "1",
      "aria-label": "File"
    })
  );

  const api = menu.connect(state, send, normalizeProps);

  return (
    <div>
      <button {...api.triggerProps}>
        Actions <span aria-hidden>▾</span>
      </button>
      <div {...api.positionerProps}>
        <div {...api.contentProps}>
          <a {...api.getItemProps({ id: "edit" })} href="https://google.com">
            Edit
          </a>
          <div {...api.getItemProps({ id: "duplicate" })}>Duplicate</div>
          <div {...api.getItemProps({ id: "delete" })}>Delete</div>
          <div {...api.getItemProps({ id: "export" })}>Export...</div>
        </div>
      </div>
    </div>
  );
}
```
