### ISSUE TITLE
[New Component] Media player

### ISSUE THREAD

**Issue by tomByrer** [chakra-ui/zag#71]
# 🚀 Feature request

Media player logic.

## 🧱 Problem Statement / Justification

I wanted a [headless video player](https://github.com/videojs/video.js/issues/5974) for years.  [Thought about using XState](https://github.com/mattpocock/xstate-catalogue/issues/47), but too heavy like you noticed.   Using [Web Components](https://github.com/btwld/vxdk) as an abstraction is too heavy.  Also want same API to [control animation libs](https://tombyrer.github.io/remotion-aspectratio-demo/).

Maybe this + [Mitosis](https://github.com/builderio/mitosis) for 'the one player to rule them all'?

## ✅ Proposed solution or API

Start: https://github.com/mattpocock/xstate-catalogue/issues/47
I can build something via XState visualizer, might take some time.

## ↩️ Alternatives

https://github.com/btwld/vxdk

## 📝 Additional Information

https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement
https://mifi.github.io/react-lottie-player/
https://www.remotion.dev/docs/player
https://github.com/vidstack/vidstack

**Comment by segunadebayo** [comment]
Closing this for now as the complexity of the component is quite high doesn't fit the scope of Zag.js for now.
