### ISSUE TITLE
select cannot open dropmenu

### ISSUE THREAD

**Issue by haoval** [chakra-ui/zag#711]
### if selected option position out of screen, click trigger component will auto select item in-screen and close dropmenu.

![xxx](https://github.com/chakra-ui/zag/assets/39382437/e1aa938c-7a80-471e-9434-91bc536d8ac9)

**Comment by segunadebayo** [comment]
Hi @haoval,

In this scenario, consider setting a `max-height` on the select content

```jsx
[data-scope=select][data-part=content] {
  max-height: min(var(--available-height), 400px)
}
```

We'll update the docs examples accordingly.
