### ISSUE TITLE
select and Custom child node

### ISSUE THREAD

**Issue by duxphp** [chakra-ui/zag#713]
# 🐛 Bug report

Nested in api.positionerProps will report an error if opened by manual control ：

```
[@zag-js/dismissable] node is `null` or `undefined`
```

## 💥 Steps to reproduce

```
<div {...api.positionerProps}>
      <div>
          <ul {...api.contentProps}>
         </ul>
      </div>
<div>
```

## 🧐 Expected behavior

Need to pull open in manual control, handle some special operations, report an error if api.positionerProps is empty or not api.contentProps, should not restrict the use of subcomponents.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |      0.10.2      |

**Comment by segunadebayo** [comment]
Thanks for reporting this issue. However, you needed to provide more information for us to understand and reproduce the problem.

Please send a reproduction, as we cannot act on issues that lack important information.
