### ISSUE TITLE
state.machine is not a function

### ISSUE THREAD

**Issue by webvs2** [chakra-ui/zag#714]
# 🐛 Bug report

When I was learning the chapter on the official website state machine, I followed the tutorial to use the vue framework, but I reported an error

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |   0.10.2          |
| Browser          |    Google |
| Operating System |            |

## 📝 Additional information

![image](https://github.com/chakra-ui/zag/assets/30883395/596458bb-dfc2-4cbe-b49c-316924ccc316)
![image](https://github.com/chakra-ui/zag/assets/30883395/65c0581e-5828-4ea9-9a4e-07fc381a9bbd)
![image](https://github.com/chakra-ui/zag/assets/30883395/1b60604f-5618-4638-aa3c-41653825845a)
![image](https://github.com/chakra-ui/zag/assets/30883395/ec04827c-52af-4af8-b40f-f9bbe21407bc)

**Comment by segunadebayo** [comment]
Hi @webvs2,

There's a miscommunication in the docs or how you interpreted it.

The correct code is `state.matches("active")` not `state.machine("active")`

**Comment by webvs2** [comment]
state.matches is not a function

> Hi @webvs2,
> 
> There's a miscommunication in the docs or how you interpreted it.
> 
> The correct code is `state.matches("active")` not `state.machine("active")`

 This prompt appears after the modification：state.matches is not a function
