### ISSUE TITLE
[Editable] submit on blur doesn't work with conditionally rendered editable

### ISSUE THREAD

**Issue by hadar759** [chakra-ui/zag#721]
# 🐛 Bug report

When an editable is conditionally rendered, submit on blur doesn't work - even when the condition is true.

Note that after submitting with Enter, subsequent blurs will submit as well.

## 💥 Steps to reproduce

1. Go to https://codesandbox.io/s/conditionally-rendered-input-kwj6ww?file=/src/App.js:665-677
2. Click on 'Click to edit' button
3. Open console
4. Enter input and blur out
5. See that submit isn't triggered

## 💻 Link to reproduction

https://codesandbox.io/s/conditionally-rendered-input-kwj6ww?file=/src/App.js:665-677

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |     0.10.2       |
| Browser          |       Arc Browser Version 0.110.1 (39837) Chromium Engine Version 114.0.5735.198   |
| Operating System |     MacOS Ventura 13.3.1       |

## 📝 Additional information

https://github.com/chakra-ui/zag/assets/23258552/b3fa23f6-acff-4565-9f6b-190beefeb576

**Comment by segunadebayo** [comment]
Thanks for reporting this @hadar759.

I think this has to do with how the local state and machine is orchestrated. 

Here's a working solution:
https://codesandbox.io/s/conditionally-rendered-input-forked-dckcvl?file=/src/App.js

I've added requestAnimationFrame to allow some time for the machine to register the "outside click" event listener. I think this was the root cause of why it didn't work.

**Comment by hadar759** [comment]
> Thanks for reporting this @hadar759.
> 
> I think this has to do with how the local state and machine is orchestrated.
> 
> Here's a working solution: https://codesandbox.io/s/conditionally-rendered-input-forked-dckcvl?file=/src/App.js
> 
> I've added requestAnimationFrame to allow some time for the machine to register the "outside click" event listener. I think this was the root cause of why it didn't work.

Thanks for the quick response!

The suggested solution doesn't work when opting for `.isEditing` instead of a custom state:
https://codesandbox.io/s/conditionally-rendered-input-forked-6xynfs?file=/src/App.js

This is our actual use case - apologies for not being more specific (also we are using SolidJS in our codebase rather than React, but I already had a codebase repo setup with React so ran with it)

**Comment by hadar759** [comment]
@segunadebayo just making sure this wasn't missed - do you have a workaround to making `.isEditing` work as the condition?

**Comment by segunadebayo** [comment]
@hadar759, how about using a Signal for the `isEditing` state shown in the example?
[codesandbox.io/s/conditionally-rendered-input-forked-dckcvl?file=/src/App.js](https://codesandbox.io/s/conditionally-rendered-input-forked-dckcvl?file=/src/App.js)
