### ISSUE TITLE
[RangeSlider] `minStepsBetweenThumbs` is not respected when using keyboard

### ISSUE THREAD

**Issue by sifferhans** [chakra-ui/zag#759]
# 🐛 Bug report

Using the arrow keys to increment/decrement the thumbs does not take into account the `minStepsBetweenThumbs` option.

## 💥 Steps to reproduce

1. Set `minStepsBetweenThumbs` to a number
2. Use the arrow keys to change the values to something that should be invalid

The thumbs should now be closer to each other that the `minStepsBetweenThumbs` option.

## 💻 Link to reproduction

Stackblitz reproduction: https://stackblitz.com/edit/zagjs-minsteps-repro?file=src%2Fcomponents%2FRangeSlider.vue

## 🧐 Expected behavior

The `minStepsBetweenThumbs` option should always be respected, both using mouse and keyboard input.

## 🧭 Possible Solution

The state machine's `incrementAtIndex` and `decrementAtIndex` doesn't seem to implement any checks, but immediately increments/decrements. There should probably be some logic here that takes into account the relevant options.

https://github.com/chakra-ui/zag/blob/60df458c005898b35ba81fc381e50e414352e9db/packages/machines/range-slider/src/range-slider.machine.ts#L228C16-L228C16

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |     0.12.0       |
| Browser          |       Chrome 114    |
| Operating System |      MacOS 12.2.1      |

## 📝 Additional information

We encountered this when implementing a Vue component using the range-slider machine, but it seems to be an issue in the machine itself.

**Comment by segunadebayo** [comment]
Thanks for such a detailed bug report and triage @sifferhans.

It made it pretty easy to fix the underlying issue. I've gone ahead to push the fix for this in [91502f2](https://github.com/chakra-ui/zag/commit/91502f27b8639bf357564cf5cce37367c717115a)

We'll release a new version shortly.
