### ISSUE TITLE
popover, nested menu, menu etc. style and container element issue in components

### ISSUE THREAD

**Issue by ramzzo** [chakra-ui/zag#762]
## Bug Report

Components such as popover, nested menu, menu etc. have problems on nuxt 3. When the modal is closed, the contents in it just close and the container element remains open even though it is closed.

## Photo of the Error

1. I pressed the click me button:
![image](https://github.com/chakra-ui/zag/assets/115036895/3f17cca3-4f69-4050-b1d6-53fd75b6148a)
2. I pressed the x button:
![image](https://github.com/chakra-ui/zag/assets/115036895/61fa2b98-9ed7-4660-a84f-589d7361300a)

**Link to reproduction**:  https://stackblitz.com/edit/nuxt-starter-6bpnk9?file=app.vue

| Software  | Version(s) |
| ------------- | ------------- |
| Zag  | 0.12.0  |
| Browser  | All  |
| Linux / Fedora | 38 |

**Comment by segunadebayo** [comment]
Hey @ramzzo,

It is more about how you manage styling. The positioner is always rendered in the DOM to reduce positioning computation; the content will have `display: none` when the popover/dialog is not open.

**You have two options**
- Move the styles to the content or even create an additional element within the content
- Add a `v-if` to the Teleport or positioner elements to hide it when the popover is open

![CleanShot 2023-07-25 at 12 24 29@2x](https://github.com/chakra-ui/zag/assets/6916170/604c7840-a071-4a37-9cab-e26b6211d84f)

**Comment by ramzzo** [comment]
thank you for your consideration
