### ISSUE TITLE
Toasts are not working

### ISSUE THREAD

**Issue by dasmikko** [chakra-ui/zag#764]
# 🐛 Bug report

Following the Vuejs SFC example, I cannot get the toasts to work

## 💥 Steps to reproduce

Click "Make a toast"
Nothing updates in the Vuejs state

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/toast-example-l8jch2?file=/src/components/Toast.vue

## 🧐 Expected behavior

Vuejs state to update, and toast to show up in the list

## 🌍 System information

| Software         | Version(s) |
| ------------------- | ---------------- |
| Zag Version      |     0.12.0       |
| Browser          |     Chrome       |
| Operating System |     Fedora       |

**Comment by segunadebayo** [comment]
Hi @dasmikko,

Here's a working solution: https://codesandbox.io/s/zag-vue-toast-sfc-w9ntk3?file=/src/App.vue

**Comment by dasmikko** [comment]
Hi! Thanks for the link, but It says the sandbox doesn't exist?

**Comment by segunadebayo** [comment]
Hey @dasmikko. Sorry, I forget to make the Sandbox public.

https://codesandbox.io/s/zag-vue-toast-sfc-w9ntk3?file=/src/App.vue
