### ISSUE TITLE
[react][dialog] closeOnOutsideClick doesn't work

### ISSUE THREAD

**Issue by beijaflor** [chakra-ui/zag#765]
# 🐛 Bug report

When using dialog to display modal dialog, `closeOnOutsideClick` option is not working.

## 💥 Steps to reproduce

1. Click on 'modal' button, than modal dialog appears 
2. Click on outside modal dialog and nothing happens

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/wandering-architecture-3wqxkn?file=/src/App.js:0-23

## 🧐 Expected behavior

It supposed to close modal dialog as document says
https://zagjs.com/components/react/dialog#closing-the-dialog-on-overlay-click

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      | 0.13.0           |
| Browser          | Chrome 114           |
| Operating System | Ventura 13.0.1           |

## 📝 Additional information

The hint could be "[@zag-js/dismissable] node is `null` or `undefined`" warning in console.
I dig into code and found that, `getContentEl()` returns `null` while executing `trackDismissableElementImpl()`. And, in console with breakpoint, accessing `ctx` in the scope throws error "Uncaught ReferenceError: ctx is not defined", although `this.state.context` is accessible in upper scope, which is in `core.machine.executeActivities()`.

**Comment by segunadebayo** [comment]
Hey @beijaflor,

This happens because you don't use the `content` part in the code.

Here's a working solution: https://codesandbox.io/s/zag-js-dialog-example-2t4769?file=/src/Modal.js

```diff
import * as dialog from "@zag-js/dialog";
import { useMachine, normalizeProps, Portal } from "@zag-js/react";
import "./modal.css";

export const Modal = () => {
  const [state, send] = useMachine(dialog.machine({ id: "sample dialog" }));
  const api = dialog.connect(state, send, normalizeProps);

  return (
    <>
      <button {...api.triggerProps}>modal</button>
      {api.isOpen && (
        <Portal>
          <div {...api.backdropProps} />
          <div {...api.containerProps}>
+            <div {...api.contentProps}>
              <div {...api.titleProps}>title</div>
              <div>It's Modal</div>
              <button type="button" {...api.closeTriggerProps}>
                close
              </button>
+            </div>
          </div>
        </Portal>
      )}
    </>
  );
};

```
