### ISSUE TITLE
Is progressbar for toast even implemented?

### ISSUE THREAD

**Issue by dasmikko** [chakra-ui/zag#769]
# 🐛 Bug report

When reading the [docs](https://zagjs.com/components/vue-sfc/toast#using-progressbars) for toasts, it states you can add progressbars for the remaining time for toasts, but the actual codes mentions nothing of this.

## 💥 Steps to reproduce

Read the docs here: https://zagjs.com/components/vue-sfc/toast#using-progressbars

## 💻 Link to reproduction
https://github.com/chakra-ui/zag/blob/main/packages/machines/toast/src/toast.connect.ts

## 🧐 Expected behavior

Have actual code for the feature

## 🧭 Possible Solution

Update the docs to reflect this.

**Comment by segunadebayo** [comment]
That's a good catch! We stopped providing API for progress bars since it's a design detail.

I've removed this from the docs.
