### ISSUE TITLE
[Docs][All] View source links for some components are broken.

### ISSUE THREAD

**Issue by ryuhangyeong** [chakra-ui/zag#779]
# 🐛 Bug report

## 💥 Steps to reproduce

1. Go to Link
 - https://zagjs.com/components/react/rating
 - https://zagjs.com/components/react/menu
 - https://zagjs.com/components/react/context-menu
 - https://zagjs.com/components/react/nested-menu
 
2. Click on [View Source] Button
3. Show 404 Page

## 💻 Link to reproduction

CodeSandbox reproduction: https://your-codesandbox-link-goes-here.io

## 🧐 Expected behavior

<img width="612" alt="image" src="https://github.com/chakra-ui/zag/assets/27342882/e59e8b6c-b586-4633-abd2-d82d57b65868">

Go to the normal link.

Example Link - https://github.com/chakra-ui/zag/tree/main/packages/machines/rating-group

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |  None          |
| Browser          |    Chrome        |
| Operating System | Window           |

**Comment by segunadebayo** [comment]
Good catch @ryuhangyeong.

I've gone ahead to update the docs for all components
