### ISSUE TITLE
[typescript] Error when passing api props to some forwarded HTML Elements

### ISSUE THREAD

**Issue by Fredx87** [chakra-ui/zag#784]
# 🐛 Bug report

I have some components from a UI library, which are using `React.forwardRef`. When I pass the spread API props TypeScript complains saying that `Types of property 'ref' are incompatible.`

I am using the Tags Input component and I came across this issue with the label, button, and input, while other parts are working (e.g. the root node).

## 💥 Steps to reproduce

1. Create a component that forwards the ref to an HTML Element, for example, a `Label`
2. Setup the tags-input machine and pass the props to the component (e.g. `<Label {...api.labelProps}>`)
3. See the TS error like the following one

```
Type '{ children: string; ref?: LegacyRef<HTMLLabelElement> | undefined; key?: Key | null | undefined; form?: string | undefined; htmlFor?: string | undefined; ... 255 more ...; onTransitionEndCapture?: TransitionEventHandler<...> | undefined; }' is not assignable to type 'RefAttributes<HTMLLabelElement>'.
  Types of property 'ref' are incompatible.
    Type 'LegacyRef<HTMLLabelElement> | undefined' is not assignable to type 'Ref<HTMLLabelElement> | undefined'.
      Type 'string' is not assignable to type 'Ref<HTMLLabelElement> | undefined'.ts(2322)
```

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/zag-js-react-ref-yhqt2x?file=/src/TagsInput.tsx:426-476

## 🧐 Expected behavior

TS should not complain when spreading props to a forwarded element

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |     0.15.0       |
| Browser          |      N/A      |
| Operating System |      N/A      |

## 📝 Additional information

I look a bit into the zag-js types but I don't understand where the issue is coming from. It seems that for some reason the expected ref is a `LegacyRef`, which should be used for class components

**Comment by MrHaila** [comment]
Possibly related: I started following the Vue SFC version of the Popover implementation, and the sample code has TS errors in the button elements. It seems to return a React type that my Vue project doesn't understand.

Not in a position to do a proper report about it this second, but +1 on some typings voodoo in 0.16.0.

**Comment by segunadebayo** [comment]
Hi @Fredx87,

I just pushed a fix for this. It is inherently a react type bug. Doing this throws the same error:

```tsx
function Demo()
 const labelProps: JSX.IntrinsicElements["label"] = {};
 return <Label {...labelProps}>Add tags</Label>
}
```

@MrHaila 0.16 did not introduce any types voodoo, so I'd recommend creating a reproduction for your issue. You probably need to use `normalizeProps`. There should be no React types leakage
