### ISSUE TITLE
NumberInput Documentation Incorrect For Setting Fraction Digits

### ISSUE THREAD

**Issue by ThomasHintz** [chakra-ui/zag#785]
# 🐛 Bug report

For Number Input: "[Adjusting the precision of the value](https://zagjs.com/components/react/number-input#adjusting-the-precision-of-the-value)" section is incorrect. Based on the source (and testing) the correct params are `minFractionDigits` & `maxFractionDigits`. `precision` does seem to exist.

## 💥 Steps to reproduce

Attempt to use `precision` and it doesn't seem to have any effect. use `min/maxFractionDigits` and it works as expected.

## 💻 Link to reproduction

N/A

## 🧭 Possible Solution

Could update copy to something like:

In some cases, you might need the value to be rounded to specific decimal points. Pass the `minFractionDigits` to set the minimum number of fractional digits and `maxFractionDigits` to set the maximum number of fractional digits.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |  0.14,0.15          |
| Browser          |   Chromium         |
| Operating System |  Linux, Mac          |

**Comment by segunadebayo** [comment]
Good catch!

I've updated the docs as suggested.
