### ISSUE TITLE
"Edit this page on GitHub" link broken on documentation website

### ISSUE THREAD

**Issue by ThomasHintz** [chakra-ui/zag#786]
# 🐛 Bug report

At the bottom of documentation pages zagjs.com there is a link that says "edit this page on github". When clicking the link I get a 404.

## 💥 Steps to reproduce

Go to the bottom of [this page](https://zagjs.com/components/react/number-input#adjusting-the-precision-of-the-value) and click the "edit this page on github" link. It leads to this URI which 404s for me: https://github.com/chakra-ui/zag-docs/edit/main/data/components/number-input.mdx

## 💻 Link to reproduction

N/A

## 🧐 Expected behavior

Expect to be able to edit the page or if it requires some level of permissions a note that it may not work or something.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |            |
| Browser          |            |
| Operating System |            |

**Comment by segunadebayo** [comment]
Good catch! I just fixed the links
