### ISSUE TITLE
Context menu jumps away on hover

### ISSUE THREAD

**Issue by toniengelhardt** [chakra-ui/zag#787]
# 🐛 Bug report

Looks like something broke with `@zag-js/menu` in `0.13.0` (see screen capture). `0.12.0` works perfectly fine, but as soon as I upgrade to `0.13.0` or higher the context menu jumps to top-0 / left-0 as soon as the cursor hovers over the menu.

https://github.com/chakra-ui/zag/assets/2703233/fa7a4e9c-abab-4ef0-b767-89c51b96b0a9

## 💥 Steps to reproduce

See above.

## 💻 Link to reproduction

Code of my ContextMenu Vue component (basically the same as the example from the docs):

```vue
<script setup lang="ts">
import * as menu from '@zag-js/menu'
import { normalizeProps, useMachine } from '@zag-js/vue'

const props = defineProps<{
  contextItems: ContextMenuItems
}>()

const [state, send] = useMachine(
  menu.machine({
    id: getUid(),
    onSelect: details => props.contextItems.find(item => item.id === details.value)?.action(),
  }),
)

const api = computed(() => menu.connect(state.value, send, normalizeProps))
</script>

<template>
  <div class="context-container">
    <div v-bind="api.contextTriggerProps" class="context-trigger">
      <slot />
    </div>
    <div v-bind="api.positionerProps" class="context-menu-container">
      <ul v-bind="api.contentProps" class="context-menu">
        <li
          v-for="item in contextItems"
          :key="item.id"
          v-bind="api.getItemProps({ id: item.id })"
          class="context-menu-item"
        >
          <span class="icon-container">
            <Icon :name="item.icon" />
          </span>
          <span class="label">{{ item.label }}</span>
        </li>
      </ul>
    </div>
  </div>
</template>

<style lang="postcss" scoped>
.context-menu-container {
  @apply p-0 bg-surface text-sm b-solid b-1 b-base rounded shadow-lg z-99;
  .context-menu {
    @apply list-none m-0 px-0 py-0.75 outline-none;
    .context-menu-item {
      @apply flex-center pr-1.5 hover:bg-element cursor-pointer;
      .icon-container {
        @apply flex-center w-5 h-5 text-xs;
        .icon {
          @apply text-dim;
        }
      }
      .label {
        @apply flex-1;
      }
    }
  }
}
</style>
```

## 🧐 Expected behavior

Should work like in v0.12.0 and below.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |  0.13.x +          |
| Browser          |  Chrome          |
| Operating System |  OSX          |

**Comment by segunadebayo** [comment]
Thanks for reporting this @toniengelhardt.

It was related to the timings and how Vue updates the style attributes. I've pushed a fix using a more explicit approach.

The regression should be gone in the next release.
