### ISSUE TITLE
[number-input] precision 0 meaning/behavior

### ISSUE THREAD

**Issue by wKovacs64** [chakra-ui/zag#79]
# 🐛 Bug report

Setting precision to 0 seems to disable rounding (that is, leave the value alone), as opposed to rounding the values to whole numbers (integers). Is this intentional behavior or a bug? If intentional, is there a way to round to whole numbers?

## 💥 Steps to reproduce

1. Go to https://zagjs.com/components/react/number-input
2. Change precision to "0" (if not already)
3. Type "12.34" in the "Enter number" input on the left
4. Tab out
5. Observe the value remains 12.34 as opposed to 12

## 💻 Link to reproduction

N/A, see Zag's own Number Input page linked above.

## 🧐 Expected behavior

I would expect it to round to the nearest whole number when precision is 0 (perhaps some other value like `undefined` would disable rounding all together?).

## 🧭 Possible Solution

Not sure.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI Core   |     N/A      |
| Browser          |      Chrome, Firefox      |
| Operating System |   Windows 10, macOS      |

## 📝 Additional information

Thank you.

**Comment by segunadebayo** [comment]
I think it's important to define the meaning of "precision". Ideally, this represents the "minimum" fractional digits of the number. What you expect from this is more of a "maximum" fractional digit.

We should probably think about supporting both cases (min and max fractional digiits) and removing the precision property altogether.
