### ISSUE TITLE
[number-input] initial values of subsequent instances get replaced with the first

### ISSUE THREAD

**Issue by wKovacs64** [chakra-ui/zag#80]
# 🐛 Bug report

When you render multiple instances of the Number Input, the initial value of every instance following the first instance quickly gets replaced with the initial value of the first instance (after briefly being correctly set to their own initial values).

## 💥 Steps to reproduce

1. Render multiple number inputs with different initial values
2. Observe they all start out correct but quickly change to the initial value of the first

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/stupefied-lake-effyhv?file=/src/App.js

## 🧐 Expected behavior

I would expect all instances to be completely independent (and in this case, respect their individual initial values).

## 🧭 Possible Solution

No clue.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Chakra UI Core   | N/A            |
| Browser          |     Chrome, Firefox       |
| Operating System |      Windows 10      |

## 📝 Additional information

Thank you.

**Comment by segunadebayo** [comment]
This is indeed a bug. Thanks for catching that @wKovacs64.

Working on a fix now.
