### ISSUE TITLE
[Dialog] [React] Controlled dialog unexpected behavior

### ISSUE THREAD

**Issue by my-lalex** [chakra-ui/zag#817]
### Description

When using the Dialog component in controlled mode without an `onClose` listener and clicking outside the dialog, the visual state is updating even if the `open` property is still true...

The dialog should stay visible until the open property is updated

### Link to Reproduction

https://codesandbox.io/s/heuristic-wood-fvvg2t?file=/src/App.tsx

### Steps to reproduce

The dialog is opened by default, and the `open` property is displayed

When clicking outside the dialog, the dialog become hidden, but the `isOpen` state is still `true`
Using the render children prop, we can see that the context's isOpen is different from the open property value

### Ark UI Version

0.13.1

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

**Comment by cschroeter** [comment]
Thanks for taking your time to report this issue. I move this to `@zag-js` because this needs to be addressed here

**Comment by my-lalex** [comment]
Hi @segunadebayo,

I get this, and it makes perfect sense from a headless/vanillaJS point of view, but this leads to `@ark-ui` changing the React controlled paradigm of  the React version of`@ark-ui`... maybe this issue should go back to the [chakra-ui/ark](https://github.com/chakra-ui/ark) repository? 😅
I think that this paradigm shouldn't be remove from a UI library targeting React...

To allow `@ark-ui` to handle this, maybe it would be possible to provide more granular events to the zag flow: I'm not very familiar with finite state machines, but by quickly reading the `Dialog` code, it seem that calling for the OPEN or TOGGLE action is emitting the `onClose` handler...
Wouldn't it be a good idea to create several handlers: the `onClose` event would be triggered by the DOM event(s) and could be prevented the `event.preventDefault()` way, and an `onClosed` event, triggered by entering the "close" state...
When not prevented, the default behavior would remain the same as the current one...

For better understandability, maybe the event names should be more like `onDOMClose` or whatever...
