### ISSUE TITLE
[Menu] [Vue] closeOnSelect prop seems to not work on MenuItem

### ISSUE THREAD

**Issue by toniengelhardt** [chakra-ui/zag#818]
# 🐛 Bug report

The interface of `getItemProps` indicates that it has a closeOnSelect property, but that property doesn't do anything.

E.g. an item with

```html
<li v-bind="api.getItemProps({ id: getUid(), closeOnSelect: false })" class="menu-item">
    My item
</li>
```

will still close the menu on click.

Using the property on the menu itself works for all items.

## 💥 Steps to reproduce

Create a menu with the above item and props and select the item. The menu will close.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      | 0.12.0 - 0.17.0           |
| Browser          | Chrome           |
| Operating System | OSX            |

**Comment by segunadebayo** [comment]
Good catch @toniengelhardt.

I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.

**Comment by toniengelhardt** [comment]
Epic! 🙏🏽
