### ISSUE TITLE
Segmented Control - readOnly does not seem to work

### ISSUE THREAD

**Issue by TPReal** [chakra-ui/zag#829]
# 🐛 Bug report

At least on the [demo page](https://zagjs.com/components/react/segmented-control), it looks like the readOnly control does not lock the control.

## 💥 Steps to reproduce

1. Go to https://zagjs.com/components/react/segmented-control
2. Select readOnly
3. Try changing the selected control value by clicking on it.
Expected: It's not possible.
Actual: It's possible, readOnly seems to be ignored.

## 💻 Link to reproduction

https://zagjs.com/components/react/segmented-control

## 🧐 Expected behavior

readOnly should block clicks to the control.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      | 0.17.0           |
| Browser          | Chrome           |
| Operating System | Windows           |

**Comment by segunadebayo** [comment]
Hi @TPReal,

Thanks for bringing this up. The `readOnly` property is not supported.

I've gone ahead to remove it from the types.

**Comment by TPReal** [comment]
Yeah, after filling in the report I thought maybe it was never meant to be there :)
