### ISSUE TITLE
[Tooltip] focused input inside tooltip trigger prevents clicks on tooltip from registering

### ISSUE THREAD

**Issue by hadar759** [chakra-ui/zag#835]
# 🐛 Bug report

When an input inside a tooltip trigger is focused it doesn't register clicks inside that tooltip

## 💥 Steps to reproduce

1. Go to https://codesandbox.io/s/input-inside-button-with-tooltip-6xynfs?file=/src/App.js
3. Focus the input
4. Hover over the button
5. Attempt to click the button in the tooltip

## 💻 Link to reproduction

https://codesandbox.io/s/input-inside-button-with-tooltip-6xynfs?file=/src/App.js

## 🧐 Expected behavior

Clicks are registered

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |      0.17.0      |
| Browser          |     Arc Version 1.6.0 (41215) Chromium Engine Version 116.0.5845.140       |
| Operating System |     MacOS Ventura 13.3.1     |

## 📝 Additional information

https://github.com/chakra-ui/zag/assets/23258552/9f43217c-2744-4cbc-b063-982dfda75df6

**Comment by segunadebayo** [comment]
This is primarily because `closeOnPointerDown: false` didn't work. You also should use `interactive: true` when you want users to interact with the content tooltip.

> Generally speaking, this behavior is better suited for a popover not a tooltip since they shouldn't include interactive elements (like buttons)

**Comment by hadar759** [comment]
> This is primarily because `closeOnPointerDown: false` didn't work. You also should use `interactive: true` when you want users to interact with the content tooltip.
> 
> > Generally speaking, this behavior is better suited for a popover not a tooltip since they shouldn't include interactive elements (like buttons)

I'm using tooltip because I want the button to show up on hover and not on click.

With the recent version (0.18.0), `interactive: true` and `closeOnPointerDown: false` this still doesn't work :(

**Comment by hadar759** [comment]
@segunadebayo just making sure this wasn't missed ^

**Comment by segunadebayo** [comment]
@hadar759

Handling the pointerdown and click events correctly should get you pretty far.

Here's a solution for this:

```tsx
import "./styles.css";
import React, { useId } from "react";
import * as tooltip from "@zag-js/tooltip";
import { normalizeProps, useMachine } from "@zag-js/react";

export default function App() {
  const [state, send] = useMachine(
    tooltip.machine({
      id: useId(),
      interactive: true,
      closeOnPointerDown: false,
      closeOnEsc: false,
      positioning: { offset: { mainAxis: 8 }, placement: "right" },
    })
  );

  const api = tooltip.connect(state, send, normalizeProps);

  return (
    <>
      <button {...api.triggerProps} style={{ padding: "16px" }}>
        <input onClick={(e) => e.stopPropagation()} />
      </button>
      {api.isOpen && (
        <div {...api.positionerProps}>
          <div {...api.contentProps} onPointerDown={(e) => e.preventDefault()}>
            <button onClick={() => console.log("clicked button")}>
              Click on me!
            </button>
          </div>
        </div>
      )}
    </>
  );
}

```

**Comment by hadar759** [comment]
> @hadar759
> 
> Handling the pointerdown and click events correctly should get you pretty far.
> 
> Here's a solution for this:
> 
> ```tsx
> import "./styles.css";
> import React, { useId } from "react";
> import * as tooltip from "@zag-js/tooltip";
> import { normalizeProps, useMachine } from "@zag-js/react";
> 
> export default function App() {
>   const [state, send] = useMachine(
>     tooltip.machine({
>       id: useId(),
>       interactive: true,
>       closeOnPointerDown: false,
>       closeOnEsc: false,
>       positioning: { offset: { mainAxis: 8 }, placement: "right" },
>     })
>   );
> 
>   const api = tooltip.connect(state, send, normalizeProps);
> 
>   return (
>     <>
>       <button {...api.triggerProps} style={{ padding: "16px" }}>
>         <input onClick={(e) => e.stopPropagation()} />
>       </button>
>       {api.isOpen && (
>         <div {...api.positionerProps}>
>           <div {...api.contentProps} onPointerDown={(e) => e.preventDefault()}>
>             <button onClick={() => console.log("clicked button")}>
>               Click on me!
>             </button>
>           </div>
>         </div>
>       )}
>     </>
>   );
> }
> ```

Thanks 🙏  This solved the issue :D
