### ISSUE TITLE
[Tooltip] `closeOnPointerDown: false` not respected

### ISSUE THREAD

**Issue by hadar759** [chakra-ui/zag#836]
# 🐛 Bug report

`closeOnPointerDown: false` option is not respected

## 💥 Steps to reproduce

1. Go to https://zagjs.com/components/react/tooltip
2. Tick off the `closeOnPointerDown` option
3. Hover over the button
4. Click on the button

## 💻 Link to reproduction

https://zagjs.com/components/react/tooltip

## 🧐 Expected behavior

Tooltip is closed

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |      0.17.0      |
| Browser          |     Arc Version 1.6.0 (41215) Chromium Engine Version 116.0.5845.140       |
| Operating System |     MacOS Ventura 13.3.1     |

**Comment by segunadebayo** [comment]
Good catch @hadar759,

I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
