### ISSUE TITLE
Number Input Vue Error Maximum call stack size exceeded

### ISSUE THREAD

**Issue by visualjerk** [chakra-ui/zag#837]
# 🐛 Bug report

Since Zag version 0.17.0 in Vue projects typing in the number input results in the following error:

```
Uncaught RangeError: Maximum call stack size exceeded.
```

## 💥 Steps to reproduce

1. Click inside the number input
2. Start typing
3. See error in the browser developer console

## 💻 Link to reproduction

StackBlitz reproduction: https://stackblitz.com/edit/vitejs-vite-gjobtx?file=src%2FApp.vue

## 🧐 Expected behavior

No error is thrown

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      | 0.17.0 |
| Browser          | Chrome |
| Operating System | MacOS |

## 📝 Additional information

Currently `number-input.connect` uses an `onChange` handler for updating the value, which in turn dispatches a custom `input` event on the input element. The props normalizer for Vue binds the `onChange` handler to `onInput`. This leads to an infinite loop: `onInput` -> `onChange` -> dispatch `input` -> `onInput`

**Comment by segunadebayo** [comment]
Good catch @visualjerk.

I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
