### ISSUE TITLE
[Editable] `startWithEditView: true` not respected

### ISSUE THREAD

**Issue by hadar759** [chakra-ui/zag#838]
# 🐛 Bug report

`startWithEditView: true` option is not respected

## 💥 Steps to reproduce

1. Go to https://codesandbox.io/s/startwitheditview-not-respected-q6tm7z
2. Refresh the console screen (to make sure nothing steals focus)
3. See that input is not focused

## 💻 Link to reproduction

https://codesandbox.io/s/startwitheditview-not-respected-q6tm7z

## 🧐 Expected behavior

Input is focused

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |      0.17.0      |
| Browser          |     Arc Version 1.6.0 (41215) Chromium Engine Version 116.0.5845.140       |
| Operating System |     MacOS Ventura 13.3.1     |

**Comment by segunadebayo** [comment]
Hi @hadar759,

`startsWithEditView` doesn't autofocus the input; it only ensures that the "edit mode" is activated, not the preview mode.

To make it autoFocus, you can add `autoFocus` to the input element directly.

https://codesandbox.io/s/startwitheditview-not-respected-forked-pcrwf9?file=/src/App.js
