### ISSUE TITLE
[Tooltip] slanting tooltip setting positioning.offset.mainAxis with arrow

### ISSUE THREAD

**Issue by beijaflor** [chakra-ui/zag#841]
# 🐛 Bug report

Tooltip is moving up each time I hover a trigger element when I set positioning.offset.mainAxis and arrowProps together.

## 💥 Steps to reproduce

1. hover pointer device to 'Hover me', then Tooltip shows up
2. move out pointer device and hover again, then Tooltip appear slightly upper position than first time
3. Tooltip will keep moving, each time you hover a trigger

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/busy-visvesvaraya-s5fnft?file=/src/Tooltip.js

## 🧐 Expected behavior

Tooltip should be keep in place

## 🧭 Possible Solution

I dig into code a bit, and found `offset` object is reused each time here
https://github.com/chakra-ui/zag/blob/4678c19/packages/machines/tooltip/src/tooltip.machine.ts#L13

It may better not reusing the object, or do not override offset object here
https://github.com/chakra-ui/zag/blob/4678c19/packages/utilities/popper/src/get-placement.ts#L48-L49

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      | 0.18.0     |
| Browser          | Chrome 116 |
| Operating System | Mac OS Vetura 13.0.1 |

**Comment by segunadebayo** [comment]
Good catch @beijaflor.

Indeed, avoiding the mutation fixes the issue.

I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
