### ISSUE TITLE
Event triggering duplicate

### ISSUE THREAD

**Issue by FlatMapIO** [chakra-ui/zag#843]
# 🐛 Bug report

In the tabs component, mouse press triggers onChange twice, once when pressed and once when released, the data in change did not change. I suspect some other components may have this problem too?

## 💻 Link to reproduction

CodeSandbox reproduction: https://stackblitz.com/edit/vitejs-vite-pgpxpw?file=src%2FApp.tsx&terminal=dev

## 🧐 Expected behavior

You know

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |            |
| Browser          |            |
| Operating System |            |

**Comment by cschroeter** [comment]
Thanks for taking your time to report this issue. I can confirm this is an issue.

@segunadebayo I also noticed that clicking an active tab invokes on Change. IMHO not changing the active tab should not invoke onChange

**Comment by segunadebayo** [comment]
Good catch @FlatMapIO.

I've gone ahead to update all components to ensure the callback is only called when changed.

Cheers.
