### ISSUE TITLE
Menu item does not receive focus when navigating with keyboard

### ISSUE THREAD

**Issue by luciorubeens** [chakra-ui/zag#872]
# 🐛 Bug report

The Menu and Select components, when set with a fixed content height, do not scroll to the highlighted element when using keyboard navigation (Tab or Arrow Keys).

## 💥 Steps to reproduce

1. Go to the reproduction link below
2. Click on the Open button
3. Press the Tab key

## 💻 Link to reproduction

CodeSandbox reproduction: https://stackblitz.com/edit/vitejs-vite-cxrt6j?file=src%2FApp.tsx

## 🧐 Expected behavior

The highlighted element should receive focus during keyboard navigation.

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |        0.19.1    |
| Browser          |        Chrome   |
| Operating System |        Mac |

**Comment by segunadebayo** [comment]
Good catch!

I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
