### ISSUE TITLE
[ColorPicker] ColorPickerChannelInput for alpha channel resets value to 1 when hex input loses focus

### ISSUE THREAD

**Issue by moxxuk** [chakra-ui/zag#884]
### Description

The alpha `ColorPickerChannelInput`, as shown on Ark UI homepage, resets its value to 1 when the hex `ColorPickerChannelInput` loses focus.

The expected result is that the alpha channel input retains its value.

### Link to Reproduction

https://ark-ui.com/

### Steps to reproduce

- Go to the color picker at https://ark-ui.com/
- Change the alpha value to anything other than 1
- Click on the hex color input element
- Click anywhere except for the `ColorPickerArea` or the slider tracks
- The alpha value is reset to 1

### Ark UI Version

@ark-ui/react@0.14.0

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

**Comment by segunadebayo** [comment]
Good catch @moxxuk,

I've gone ahead to fix the underlying issue in the state machine.

We'll release an update for Zag and Ark shortly.

If the issue persists after upgrading, I'll re-open it.
