### ISSUE TITLE
Dialog closes when a toast is visible and clicked, despite closeOnOutsideClick set to false

### ISSUE THREAD

**Issue by damzobridge** [chakra-ui/zag#885]
### Description

When a `toast` is triggered within the `Dialog`, any touch or click with the toast causes the `Dialog` to close, even though the `closeOnOutsideClick` prop is set to false on the Dialog component.

When I trigger a toast within the dialog, I expected the dialog to remain open until I explicitly close it, but it closes unexpectedly upon interacting with the toast.

### Link to Reproduction

https://codesandbox.io/p/sandbox/elastic-oskar-5vnq2k

### Steps to reproduce

1. Go to the provided CodeSandbox link.
2. Click on the `Open Dialog` button to open the dialog.
3. Within the dialog, click on the `Add Toast` button to trigger a toast.
4. Click on the toast.
5. Observe that the dialog closes unexpectedly.

### Ark UI Version

0.14.0

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
