### ISSUE TITLE
Function to re-calculate the position of portaled popovers

### ISSUE THREAD

**Issue by MrHaila** [chakra-ui/zag#887]
# 🚀 Feature request

Add a function to re-calculate the position of portaled popovers and tooltips.

## 🧱 Problem Statement / Justification

I have an issue where elements get server-side rendered (Nuxt) and the position of all tooltips, selects and popovers is in the upper left corner. I can fix the issue by triggering the element in question to re-render on the client side. Ideally, I'd like to be able to call a function on the underlying machine to do this one bit of recalculation when I know the UI is ready instead of refreshing the whole component.

## ✅ Proposed solution or API

For example `api.reposition()`

Many thanks for your work on this project!

**Comment by segunadebayo** [comment]
The machines provide an `api.setPositioning(...)`  function you can call to reposition the component.

> The select machine misses this API but I'll add it shortly.
