### ISSUE TITLE
Pressable usage

### ISSUE THREAD

**Issue by cschroeter** [chakra-ui/zag#901]
### Discussed in https://github.com/chakra-ui/ark/discussions/1461

<div type='discussions-op-text'>

<sup>Originally posted by **arekrgw** September 24, 2023</sup>
I've been using Pressable component as a base for Button and IconButton components.

Here's my implementation
```js

// styles...

export type ButtonProps = PressableProps & VariantProps<typeof buttonVariants>;

const Button = forwardRef<HTMLButtonElement, ButtonProps>((props, ref) => {
  const { variant, color, size, className, ...otherProps } = props;

  return <Pressable ref={ref} {...otherProps} className={cn(buttonVariants({ variant, color, size }), className)} />;
});

Button.displayName = 'Button';

export default Button;
```

And I've been using it like that:

```js
<Button onPress={e => console.log(e)}>Hello</Button
```

And everything worked until I started testing app on mobile. The issue I came around was that the press event wasn't firing on mobile, after some digging I recreated this on desktop also. 

1. It looks like moving cursor by even small amount of px inside button between pressing and release cancels event. I've managed to log the pointerType on mobile and it was "virtual" (maybe it will help). 

https://github.com/chakra-ui/ark/assets/34128433/acad54cf-8780-4a1c-8cc8-e4979e5822ba

2. It happens on my POCO F3 with Android 13 with Chromium based browsers (works on Firefox). What's strange, everything is fine on Realme with Android 12. Haven't tested on other devices.

After that I was confused and wasn't sure if this Pressable component is for simple buttons, that's why for now I moved to onClick handlers but because of that I'm opting out of some cool accessibility features?

Ark version: 0.15.0</div>

**Comment by unbiased-dev** [comment]
The machine was great for long press detection. It's a shame to remove a feature just like that. Makes no sense to me.
