### ISSUE TITLE
Pin input takes two character in one spot!

### ISSUE THREAD

**Issue by raminrez** [chakra-ui/zag#908]
# 🐛 Bug report
![Screenshot 2023-09-30 at 3 03 32 PM](https://github.com/chakra-ui/zag/assets/7345325/a1f256ed-3ccb-472b-ac22-d8a8b1f1531b)

## 💥 Steps to reproduce

1. Go to [Pin Input](https://zagjs.com/components/react/pin-input)
2. Click on input
3. pres two or three key at once!

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |0.22.0|
| Browser          |chrome|
| Operating System |macos|

**Comment by segunadebayo** [comment]
Good catch @raminrez.

I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
