### ISSUE TITLE
Popover with third-party frames triggers DOMExceptions

### ISSUE THREAD

**Issue by wilcoschoneveld** [chakra-ui/zag#933]
# 🐛 Bug report

We have a website with third-party frames (cookiebot and google tag manager) and when using the Popover component from ark-ui we are getting the following warnings in the console:

`DOMException: Blocked a frame with origin "http://localhost:3000" from accessing a cross-origin frame.`

This is coming from `zag-js/interact-outside` which is setup as a utility for the popover component.

## 💥 Steps to reproduce

Hard to reproduce,

we traced the source code and it seems that the `zag-js/interact-outside` tries to attach event handlers to all window frames including the ones from cookiebot and google tag manager, and they reject the event handlers due to cross-origin policy.

## 💻 Link to reproduction

on request

## 🧐 Expected behavior

no console warnings/errors, no dom exceptions

## 🧭 Possible Solution

remove console warnings

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |      0.19.1      |
| Browser          |    Chrome        |
| Operating System |        MacOS    |

## 📝 Additional information

![image](https://github.com/chakra-ui/zag/assets/3064588/b5bd096b-93c6-4fa1-bd6a-860f9317b750)

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
