### ISSUE TITLE
[Combobox] wrong property is added to positioner props

### ISSUE THREAD

**Issue by samadadi** [chakra-ui/zag#938]
Hi. In combobox component you are adding `hidden` property to positioner props and in select component you are adding same property to content props. I explained rest in this issue for ark-ui: [https://github.com/chakra-ui/ark/issues/1538](https://github.com/chakra-ui/ark/issues/1538)

**Comment by segunadebayo** [comment]
Good catch @samadadi 

I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
