### ISSUE TITLE
Number input should clamp to default value on blur if left empty and min set to 0

### ISSUE THREAD

**Issue by johtso** [chakra-ui/zag#98]
If you delete the contents of the number input and blur out, it should revert to the default value rather than remaining as an empty string. Or this should at least be an option.

**Comment by anubra266** [comment]
@johtso Have you tried the `clampValueOnBlur` key in the context?

**Comment by anubra266** [comment]
@johtso A number input is like any other input, just it handles numbers. In either a text or number input, I think this is something you have to control yourself, as it's not the default behaviour of inputs.

**Comment by johtso** [comment]
I'm suggesting that, in keeping with the `clampValueOnBlur` functionality which ensures the input can't have a value that's out of range when edited manually, `""`/`NaN` should be considered an out of range value and result in clamping.

Otherwise it seems strange to have to handle that one specific exceptional case manually.

**Comment by anubra266** [comment]
@johtso how do you get NaN into the input?

**Comment by anubra266** [comment]
@johtso, for the `""` usecase, that means the input can't be left empty.

**Comment by johtso** [comment]
> @johtso how do you get NaN into the input?

Ah, I see that `valueAsNumber` is actually `0` if value is `""`.  I'm using a form submission so the server was getting an empty string when it was expecting a number.

> @johtso, for the `""` usecase, that means the input can't be left empty.

If needing empty number inputs is a possible use-case, then this could be behind an option.

**Comment by anubra266** [comment]
@johtso I see, my perspective is that when we have optional fields, It'll be better to receive "". Because in cases where you're expecting a number, `0` is just another number, `""` will be better to recognise falsy inputs when the input is optional. We won't be able to do a `if(value===0)` check because `0` could be an acceptable value.

**Comment by johtso** [comment]
@anubra266 how would I make the number input field not optional?

**Comment by anubra266** [comment]
> @anubra266 how would I make the number input field not optional?

By using the valueAsNumber

**Comment by anubra266** [comment]
Oh...I'm just understanding your question @johtso

**Comment by anubra266** [comment]
That's a normal input behavior @johtso you have to validate. If the user enters nothing, you validate and say input is required, like any other input.

**Comment by johtso** [comment]
I'm just saying that zag already does a lot of this validation for you, that's the purpose of using the component. It seems like something that it might make sense for the component to handle.

Just like it doesn't allow you to type text into the input, or enter a number that's outside of the range, you should also be able to specify that it is a required field and therefor an empty string is not a valid value and it should clamp/default to the most sensible value.

**Comment by anubra266** [comment]
cc @segunadebayo

**Comment by johtso** [comment]
Actually, I just experimented a bit more, and the behaviour I was describing _does_ already happen, but only if the `min` is set to something greater than `0`.

I guess that's because `""` is interpreted as being `0`.

**Comment by johtso** [comment]
Sorry just to clarify, that means the current behaviour is inconsistent and there's probably a clear case for making a number input with `min=0` clamp to `0` onBlur if the input is empty.

**Comment by johtso** [comment]
This seems to be the code responsible for interpreting `""` as `0` https://github.com/chakra-ui/zag/blob/main/packages/utilities/number/src/number.ts#L54

**Comment by johtso** [comment]
> @johtso could you shed light afresh on the behavior you're expecting here?

When you blur out of an empty input with `min` set to `0`, the value should reset to `0`

**Comment by johtso** [comment]
> @johtso and what of when the min is not 0

There's is no issue when the min is set to something else, in that case it is correctly defaulted to that value when you blur out.

**Comment by anubra266** [comment]
> > @johtso and what of when the min is not 0
> 
> 
> 
> There's is no issue when the min is set to something else, in that case it is correctly defaulted to that value when you blur out.

@johtso how do you expect it to behave when the mom value is a negative number?

**Comment by johtso** [comment]
@anubra266 chakra-ui also has clamping, but it just leaves the field empty on blur if the user deletes the value https://chakra-ui.com/docs/components/number-input#setting-a-minimum-and-maximum-value

**Comment by anubra266** [comment]
Yeah...@johtso, that onBlur behaviour os what I'm looking for so Chakra UI can't help there.

**Comment by johtso** [comment]
I mean, unless we want to do the same and leave the input empty..

**Comment by anubra266** [comment]
Yeah makes sense @johtso Couldn't find any implementation that does it differently
