### ISSUE TITLE
Error: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by namjul** [chakra-ui/zag#980]
# 🐛 Bug report

I believe this is related to https://github.com/lukeed/klona/issues/44 which suggests that circular dependencies are somehow created. Maybe through using vue@2.7 composition API.

## 💥 Steps to reproduce

I encounted this while using zag-js with vue@2.7 (using its composition API) and implementing `zag-js/combobox`.

## 💻 Link to reproduction

CodeSandbox reproduction: https://codesandbox.io/s/nice-wind-pty88z

## 🧭 Possible Solution

~~A quick test suggests that using `klona/json` works as meant to be done here https://github.com/chakra-ui/zag/commit/a04304885dba0a86336f492408199bf44dcdcbfd but the main code now uses `klona/full` https://github.com/chakra-ui/zag/blob/1923cb2efdb854b0aebe58dfb38e1c550c5f3342/packages/core/src/utils.ts#L4~~

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |    0.27.0        |
| Browser          |      118.0.5993.88 (       |
| Operating System |       Ubuntu@22.04     |

**Comment by segunadebayo** [comment]
Hi @namjul,

I can't seem to reproduce this in Vite + Vue. I recommend using Vite or Nuxt when building components.

Here's a working example without the maximum call stack issue:
https://stackblitz.com/edit/vitejs-vite-avmvjf?file=src%2Fcomponents%2FSelect.jsx
