### ISSUE TITLE
[Nested Menu] Polygon to safely open nested menu

### ISSUE THREAD

**Issue by ps73** [chakra-ui/zag#983]
# 🚀 Feature request

It would be great if Nested Menu uses a safe polygon for opening / closing the submenu.
Currently the submenu sometimes closes when the user is on his way to the submenu.

## 🧱 Problem Statement / Justification

I think this should be a standard implementation for UI Libraries focusing on accessibility.

## ✅ Proposed solution or API

There is a great blogpost from linear:
https://linear.app/blog/invisible-details

## 📝 Additional Information

https://github.com/chakra-ui/zag/assets/17291660/930226b7-f28e-4447-922c-65479b0bc959

**Comment by segunadebayo** [comment]
Hi @ps73,

We use a combination of timer and safe polygon for the nested menu navigation.

Perhaps the timer could be increased a bit. So this is accounted for already.
