### ISSUE TITLE
[mobile] Number input triggers not registering touch events

### ISSUE THREAD

**Issue by etnbrd** [chakra-ui/zag#987]
# 🐛 Bug report

The `NumberInput` component triggers [only register mouse events](https://github.com/chakra-ui/zag/blob/abef1cc1d1d89ba1536e6fa225df9b7217f8e8bc/packages/machines/number-input/src/number-input.connect.ts#L208C18-L208C18), and doesn't work on mobile.

## 💥 Steps to reproduce

1. Go to [number-input documentation](https://zagjs.com/components/react/number-input)
2. Open responsive mode in devtools, and enable a touch based device (mobile or Desktop(touch)) (see device toolbar on 
 the top of the screenshot below)
3. Try to click on increment and decrement triggers
4. The value doesn't increase nor decrease

<img width="783" alt="Screenshot 2023-11-04 at 16 45 38" src="https://github.com/chakra-ui/zag/assets/5691124/db75abbe-3531-41d2-8cae-aa962db9229f">

## 💻 Link to reproduction

Reproduction is possible right from the documentation.

## 🧐 Expected behavior

The expected behavior is for the triggers to register touch events as well as mouse events.

## 🧭 Possible Solution

In the `decrementTriggerProps` and `incrementTriggerProps `, respectively [here](https://github.com/chakra-ui/zag/blob/abef1cc1d1d89ba1536e6fa225df9b7217f8e8bc/packages/machines/number-input/src/number-input.connect.ts#L196-L222) and [here](https://github.com/chakra-ui/zag/blob/abef1cc1d1d89ba1536e6fa225df9b7217f8e8bc/packages/machines/number-input/src/number-input.connect.ts#L206-L215), (the code is the same):
```diff
      onPointerDown(event) {
        if (isIncrementDisabled || !isLeftClick(event)) return
-       if (event.pointerType === "mouse") {
+       if (["mouse", "touch"].includes(event.pointerType)) {
          send({ type: "TRIGGER.PRESS_DOWN", hint: "increment" })
          return event.preventDefault()
        }
        if (isHTMLElement(event.target)) {
          event.target?.focus()
        }
      },
```

## 🌍 System information

| Software                | Version(s) |
| ------------------ | ---------- |
| Zag Version           | 0.27.1         |
| Browser                  | Chrome 119.0.6045.105 (Official Build) (arm64)  |
| Operating System | macOS Ventura 13.6 |

## 📝 Additional information

The behaviour works as expected in the Firefox devtools because the touch implementation sends both the `mouse` event and the `touch` event.

Sorry if I missed some part of the documentation that explained how to support touch events, some workaround, or the reason for not supporting them.
Thanks a lot 🙏

**Comment by segunadebayo** [comment]
Good catch @etnbrd,

I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
