### ISSUE TITLE
Number Input - Fraction digits not working as expected

### ISSUE THREAD

**Issue by nyerslaszlo** [chakra-ui/zag#996]
# 🐛 Bug report

When setting minimum and maximum fraction digit values for Number input, the input fields don't work as expected. It's impossible to correctly type in numbers when minimum fraction digit is set, and there is no way to type in decimal point when only maximum fraction digit is set.

## 💥 Steps to reproduce

1. Create number Input fields.
2. Set "minimumFractionDigits" and/or "maximumFractionDigits"
3. Try to type into the input field.

## 💻 Reproduction
CodeSandbox reproduction: https://codesandbox.io/p/sandbox/sleepy-cache-xly8xv?file=%2Fsrc%2FApp.vue%3A15%2C8

## 🧐 Expected behavior

When minimum fraction digits are set, I expect to be able to delete the value in the input and type in my own value. If I don't include a fraction, then I except it automatically include as many fractions as set with the "minimumFractionDigits".

If "minimumFractionValues" are not set, I expect to be able to type in the locale's decimal point (which is usually a . or a , character).

## 🌍 System information

| Software         | Version(s) |
| ---------------- | ---------- |
| Zag Version      |0.27.1|
| Browser          |Microsoft Edge|
| Operating System |Windows 11|

## 📝 Additional information

Using the 0.21.0 version of Number input is my current workaround, which did not include Int formatting, but was able to set fractions correctly. Intl formatting is a welcome addition I would love to use it when this issue is resolved.

**Comment by segunadebayo** [comment]
Hi @nyerslaszlo,

This has been fixed in a recent commit 7751c728ccd9b909b1455345bc4919491e1bc3f2; we'll publish a new version shortly.
